"""Gut Reset with Sun Yoon: 26 additional recipes (G01–G26). Same tuple format as recipes.py; USDA FDC SR Legacy (E52)."""

G = []


def recipe(**k):
    G.append(k)


recipe(id="G01", cat="Base", name="Mixed-grain rice with black beans", native="japgok-bap (Korean)", serves=8, active=5, total=10,
       intro="White rice every day? Fine when you were twenty. Now mix in barley and beans. More fiber, same rice cooker.",
       ings=[("3 cups", "cooked brown rice", 585, 169704), ("1 1/2 cups", "cooked pearled barley", 235, 170285),
             ("1 can (15 oz), drained and rinsed", "low-sodium black beans", 258, 175238)],
       steps=["Cook brown rice and barley ahead (or buy them cooked and frozen). Rinse the beans in a colander.",
              "Mix everything in a big bowl while the grains are warm.",
              "Portion 2/3 cup per person. Freeze the rest in flat bags."],
       soft="Cook the brown rice and barley with 25% more water, and mash the beans lightly.",
       store="Fridge 4 days, freezer 3 months. Reheat until steaming (165°F).", tags=["fiber"])

recipe(id="G02", cat="Soup", name="Soybean-paste stew with tofu and shrimp", native="doenjang-jjigae (Korean)", serves=4, active=15, total=30,
       intro="Every Korean house has this on the stove three nights a week. Doenjang is fermented soybean paste. If you can't find it, miso works. Don't tell my mother.",
       ings=[("1 block (14 oz)", "firm tofu, in cubes", 397, 172448), ("8 oz", "raw shrimp, peeled", 227, 175179),
             ("2 Tbsp", "doenjang or miso", 34, 172442), ("1 medium", "zucchini, in half-moons", 196, 169291),
             ("1 medium", "onion, diced", 110, 170000), ("4 oz", "fresh shiitake mushrooms, sliced", 113, 169242),
             ("1 small", "russet potato, in small cubes", 150, 170027), ("1", "garlic clove, minced", 3, 169230),
             ("1 tsp", "Korean chili flakes (optional)", 1.8, 170932), ("2", "scallions, sliced", 30, 170005),
             ("4 cups", "water", 0, None), ("2 cups", "cooked brown rice, to serve", 390, 169704)],
       steps=["Stir the doenjang into the water in a pot until dissolved. Add the potato, onion and garlic. Boil, then simmer 8 minutes.",
              "Add the zucchini and mushrooms. Simmer 5 minutes.",
              "Add the tofu and shrimp. Simmer 3 to 4 minutes, until the shrimp are pink and opaque all the way through.",
              "Add chili flakes if you like. Top with scallions. Serve with rice."],
       soft="Dice everything small and cook the potato until very soft. Chop the shrimp.",
       store="Fridge 3 days. Reheat until steaming.", tags=["shellfish", "salty"])

recipe(id="G03", cat="Side", name="Two banchan: sesame spinach and soybean sprouts", native="sigeumchi-namul and kongnamul-muchim (Korean)", serves=4, active=15, total=15,
       intro="Banchan are the little side dishes. They're how Koreans eat vegetables without noticing. Make both on Sunday, eat them all week.",
       ings=[("10 oz", "fresh spinach", 284, 168462), ("12 oz", "soybean sprouts (always cooked)", 340, 168460),
             ("2", "garlic cloves, grated", 6, 169230), ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("2 tsp", "toasted sesame oil", 9, 171016), ("2 tsp", "toasted sesame seeds", 6, 170151),
             ("1/4 tsp", "salt", 1.5, 173468), ("2", "scallions, finely chopped", 30, 170005)],
       steps=["Bring a pot of water to a boil. Add the soybean sprouts, cover, and cook 6 minutes. Lift out, drain, and cool.",
              "In the same water, blanch the spinach 30 seconds. Drain, rinse cold, squeeze dry and chop.",
              "Toss the sprouts with half the garlic, sesame oil, sesame seeds, scallions and the salt.",
              "Toss the spinach with the rest of the garlic, sesame oil, sesame seeds, scallions and the soy sauce.",
              "Serve cold or at room temperature."],
       soft="Chop both finely after cooking. Cook the sprouts 2 minutes longer.",
       store="Fridge 3 days in covered containers.", tags=["leafy_greens"])

recipe(id="G04", cat="Side", name="Soy-braised black soybeans", native="kongjaban (Korean)", serves=6, active=5, total=20,
       intro="Sweet, salty, chewy. Children eat them like candy. Old people should too: fiber and protein in a spoon.",
       ings=[("2 cups", "cooked black soybeans (canned, drained, or home-cooked)", 344, 174299),
             ("2 Tbsp", "low-sodium soy sauce", 32, 172473), ("1 Tbsp", "honey", 21, 169640),
             ("1/2 cup", "water", 0, None), ("1 tsp", "toasted sesame oil", 4.5, 171016), ("1 tsp", "toasted sesame seeds", 3, 170151)],
       steps=["Put the beans, soy sauce, honey and water in a small pan.",
              "Simmer on low, stirring now and then, 12 to 15 minutes, until the liquid is almost gone and the beans look glossy.",
              "Stir in the sesame oil and seeds. Cool. Serve 1/3 cup as a side."],
       soft="Simmer 10 minutes longer with extra water and mash lightly.",
       store="Fridge 1 week.", tags=["honey", "braise_overcount"])

recipe(id="G05", cat="Lunch", name="Mung bean pancakes with kimchi and pork", native="bindaetteok (Korean)", serves=4, active=30, total=40,
       intro="Soak the beans the night before. That's the only hard part. The rest is frying and eating and pretending you'll save some for later.",
       ings=[("1 cup dried (soaked overnight)", "peeled split mung beans", 207, 174256), ("4 oz", "pork loin, minced finely", 113, 168230),
             ("1 cup", "kimchi, chopped and squeezed", 150, 170392), ("1 cup", "cooked soybean sprouts, chopped", 70, 168460),
             ("2", "scallions, sliced", 30, 170005), ("1", "large egg", 50, 171287), ("1/4 tsp", "salt", 1.5, 173468),
             ("2 Tbsp", "canola oil", 28, 172336), ("1 Tbsp", "low-sodium soy sauce (dip)", 16, 172473),
             ("1 Tbsp", "rice or white vinegar (dip)", 15, 172237)],
       steps=["Drain the soaked mung beans. Blend with 1/2 cup water to a thick, slightly gritty batter.",
              "Stir in the pork, kimchi, sprouts, scallions, egg and salt.",
              "Heat 1/2 Tbsp oil in a nonstick skillet over medium heat. Spoon in 1/2 cup batter and flatten to a 4-inch round.",
              "Cook 4 to 5 minutes a side, until deep golden and cooked through (pork reaches 160°F in the center; press to check no pink batter remains).",
              "Repeat with the rest. Serve with the soy-vinegar dip."],
       soft="Make them thinner and smaller, and cut into pieces.",
       store="Fridge 3 days, freezer 2 months. Reheat in a dry skillet until steaming.", tags=["kimchi", "fiber", "salty"])

recipe(id="G06", cat="Dinner", name="Stir-fried tofu with broccoli and garlic", native="suàn róng xī lán chǎo dòufu (Chinese)", serves=2, active=15, total=20,
       intro="Twenty minutes. Nobody in this house has ever refused it. Chang tried once. Once.",
       ings=[("1 block (14 oz)", "extra-firm tofu, pressed and cubed", 397, 174290), ("12 oz", "broccoli florets", 340, 170379),
             ("4", "garlic cloves, minced", 12, 169230), ("1 Tbsp", "minced ginger", 6, 169231),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473), ("1 tsp", "oyster sauce", 5, 174529),
             ("1 tsp + 3 Tbsp water", "cornstarch", 2.7, 169698), ("1 Tbsp", "canola oil", 14, 172336),
             ("1 cup", "cooked brown rice", 195, 169704)],
       steps=["Pat the tofu dry. Heat half the oil in a nonstick skillet and cook the tofu, turning, until golden, 6 to 8 minutes. Move to a plate.",
              "Add the rest of the oil, the broccoli and 3 Tbsp water. Cover and steam-fry 4 minutes.",
              "Add garlic and ginger, stir 30 seconds.",
              "Return the tofu. Stir the soy sauce, oyster sauce, cornstarch and water together and pour in. Toss 1 minute until glossy.",
              "Serve with rice."],
       soft="Use firm (not extra-firm) tofu and cook the broccoli 3 minutes longer.",
       store="Fridge 3 days.", tags=["leafy_greens", "fiber", "high_protein"])

recipe(id="G07", cat="Dinner", name="Cod braised with tomato and ginger", native="fānqié mèn yú (Chinese)", serves=2, active=15, total=25,
       intro="Soft fish, soft tomatoes, lots of sauce for the grains. My dentist would approve if he could eat it.",
       ings=[("12 oz", "cod fillets, in 2 pieces", 340, 171955), ("3 medium", "tomatoes, in wedges", 369, 170457),
             ("1 Tbsp", "minced ginger", 6, 169231), ("2", "scallions, sliced", 30, 170005), ("1 tsp", "sugar", 4.2, 169655),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473), ("1 Tbsp", "canola oil", 14, 172336),
             ("8 oz", "baby bok choy, halved", 227, 170390), ("1 cup", "cooked pearled barley or brown rice", 157, 170285)],
       steps=["Heat the oil in a skillet with a lid. Add the ginger and tomatoes. Cook 5 minutes until the tomatoes collapse into a sauce. Add sugar and soy sauce.",
              "Nestle the cod into the sauce and lay the bok choy around it. Cover.",
              "Simmer on low 8 to 10 minutes, until the fish flakes easily and reads 145°F.",
              "Top with scallions. Serve over the barley."],
       soft="Already soft. Chop the bok choy stems small.",
       store="Best fresh; fridge 1 day.", tags=["leafy_greens", "high_protein"])

recipe(id="G08", cat="Lunch", name="Egg and chive stir-fry with kimchi", native="jiǔcài chǎo jīdàn (Chinese)", serves=2, active=10, total=12,
       intro="Garlic chives are the flat ones at the Asian grocery. Regular chives work. Ten minutes. Eggs cooked firm. Always.",
       ings=[("5", "large eggs", 250, 171287), ("4 oz (1 bunch)", "garlic chives or regular chives, in 1-inch pieces", 113, 169994),
             ("1 Tbsp", "canola oil", 14, 172336), ("1/4 tsp", "salt", 1.5, 173468),
             ("1 cup", "cooked brown rice", 195, 169704), ("1/2 cup", "kimchi, to serve", 75, 170392),
             ("1 cup", "frozen shelled edamame, cooked", 155, 168411)],
       steps=["Beat the eggs with the salt.",
              "Heat the oil in a nonstick skillet over medium heat. Add the chives and stir 1 minute.",
              "Pour in the eggs. Stir slowly until they set into large, fully cooked curds, about 2 minutes.",
              "Serve with rice, edamame and a little kimchi."],
       soft="Chop the chives finely; mash the edamame.",
       store="Best fresh.", tags=["kimchi", "eggs", "fiber"])

recipe(id="G09", cat="Breakfast", name="Sweet potato porridge with walnuts", native="goguma-juk (Korean)", serves=2, active=10, total=35,
       intro="Orange, sweet, soft, warm. Made with soy milk so it has protein, and eggs on the side so it has more. Breakfast, not dessert.",
       ings=[("1 medium", "sweet potato, peeled and cubed", 200, 168482), ("1/3 cup", "short-grain rice, rinsed", 67, 168931),
             ("2 cups", "unsweetened soy milk", 486, 175215), ("1 cup", "water", 0, None), ("pinch", "salt", 0.8, 173468),
             ("2", "hard-boiled eggs, on the side", 100, 171287), ("1 Tbsp", "chopped walnuts", 7, 170187)],
       steps=["Simmer the sweet potato and rice in the water, covered, 15 minutes, until soft.",
              "Add the soy milk. Simmer 10 more minutes, stirring often so it doesn't stick.",
              "Mash or blend until smooth. Add the salt.",
              "Top with walnuts. Serve with a hard-boiled egg each (boiled 10 minutes, yolk firm)."],
       soft="Blend completely smooth; skip the walnuts or grind them.",
       store="Fridge 3 days. Thin with water when you reheat.", tags=["eggs"])

recipe(id="G10", cat="Soup", name="Chicken, barley and mushroom soup", native="Sun's winter pot", serves=4, active=15, total=45,
       intro="Barley has the kind of fiber that makes soup thick and your gut happy. Also Chang can't tell it's healthy, which is my favorite kind of recipe.",
       ings=[("1 lb", "boneless, skinless chicken thighs", 454, 173627), ("1 1/2 cups", "cooked pearled barley", 235, 170285),
             ("8 oz", "fresh shiitake mushrooms, sliced", 227, 169242), ("2 medium", "carrots, diced", 122, 170393),
             ("2 stalks", "celery, diced", 80, 169988), ("1 medium", "onion, diced", 110, 170000),
             ("3", "garlic cloves, minced", 9, 169230), ("1 Tbsp", "minced ginger", 6, 169231),
             ("6 cups", "low-sodium chicken broth", 1440, 171609), ("1/4 tsp", "salt", 1.5, 173468),
             ("3 cups (3 oz)", "baby spinach", 85, 168462)],
       steps=["Put the chicken, carrots, celery, onion, garlic, ginger and broth in a pot. Boil, then simmer 20 minutes.",
              "Lift out the chicken (it should read 165°F), shred it, and return it.",
              "Add the mushrooms and barley. Simmer 10 minutes.",
              "Stir in the spinach until wilted. Taste, then add the salt only if needed."],
       soft="Dice the vegetables small and shred the chicken finely.",
       store="Fridge 4 days, freezer 3 months. Reheat to 165°F.", tags=["leafy_greens", "high_protein", "fiber"])

recipe(id="G11", cat="Soup", name="Napa cabbage, beef and tofu soybean soup", native="baechu doenjang-guk (Korean)", serves=4, active=15, total=35,
       intro="Cabbage, soybean paste, a little beef. Tastes like a Korean grandmother's kitchen in November. Which is where I learned it.",
       ings=[("1 lb", "napa cabbage, cut in 2-inch pieces", 454, 169979), ("8 oz", "lean beef chuck, thinly sliced", 227, 174051),
             ("1 block (14 oz)", "soft tofu, in cubes", 397, 172449), ("2 Tbsp", "doenjang or miso", 34, 172442),
             ("2", "garlic cloves, minced", 6, 169230), ("2", "scallions, sliced", 30, 170005), ("6 cups", "water", 0, None),
             ("2 cups", "cooked brown rice, to serve", 390, 169704)],
       steps=["Stir the doenjang into the water in a pot. Add the beef and garlic. Boil, skim the foam, then simmer 10 minutes.",
              "Add the cabbage. Simmer 12 minutes, until soft and sweet.",
              "Add the tofu. Simmer 3 minutes. Top with scallions. Serve with rice."],
       soft="Chop the cabbage and beef small.",
       store="Fridge 4 days.", tags=["salty"])

recipe(id="G12", cat="Soup", name="Korean radish and beef soup", native="soegogi-muguk (Korean)", serves=4, active=15, total=45,
       intro="Clear, clean, and the radish goes soft and sweet. When your stomach isn't sure about anything, it's sure about this.",
       ings=[("12 oz", "lean beef chuck, in thin bite-size slices", 340, 174051), ("1 lb", "daikon radish, in thin squares", 454, 168451),
             ("3", "garlic cloves, minced", 9, 169230), ("2 Tbsp", "low-sodium soy sauce", 32, 172473),
             ("1 Tbsp", "toasted sesame oil", 13.6, 171016), ("8 cups", "water", 0, None), ("3", "scallions, sliced", 45, 170005),
             ("1/4 tsp", "salt", 1.5, 173468), ("2 cups", "cooked brown rice, to serve", 390, 169704)],
       steps=["Heat the sesame oil in a pot. Cook the beef and garlic 3 minutes.",
              "Add the radish and 1 Tbsp soy sauce. Stir 3 minutes.",
              "Add the water. Boil, skim, then simmer 25 minutes until the radish is translucent.",
              "Season with the rest of the soy sauce, then salt if needed. Scallions on top. Rice on the side."],
       soft="Cut the beef and radish very small; cook 10 minutes longer.",
       store="Fridge 4 days, freezer 3 months.", tags=[])

recipe(id="G13", cat="Lunch", name="Kimchi pancake with shrimp", native="kimchi-jeon (Korean)", serves=3, active=15, total=20,
       intro="The best use of kimchi that's gone sour. Whole-wheat flour, shrimp for protein. Rainy-day food. In California that's four days a year, so I make it when it's cloudy.",
       ings=[("1 cup", "whole-wheat flour", 120, 168893), ("1", "large egg", 50, 171287),
             ("1 cup + 2 Tbsp juice", "sour kimchi, chopped", 150, 170392), ("6 oz", "raw shrimp, chopped", 170, 175179),
             ("3", "scallions, in 1-inch pieces", 45, 170005), ("3/4 cup", "cold water", 0, None), ("2 Tbsp", "canola oil", 28, 172336)],
       steps=["Mix the flour, egg, kimchi and juice, and water into a thick batter. Fold in the shrimp and scallions.",
              "Heat 1 Tbsp oil in a large nonstick skillet over medium heat. Spread half the batter thin.",
              "Cook 4 minutes until the edges crisp, flip, and cook 4 more minutes until cooked through and the shrimp are opaque.",
              "Repeat. Cut in squares."],
       soft="Make it thinner and cut it small; use soft white flour if whole-wheat is too coarse.",
       store="Fridge 2 days. Re-crisp in a dry skillet until steaming.", tags=["kimchi", "shellfish", "fiber", "eggs"])

recipe(id="G14", cat="Dinner", name="Garlic eggplant with ground turkey", native="mild yú xiāng qiézi (Chinese)", serves=4, active=25, total=30,
       intro="Eggplant soaks up sauce like a sponge. I use turkey so it's lean. The name translates to 'fish-fragrant' but there's no fish. Don't ask me. Ask Sichuan.",
       ings=[("1 1/2 lb", "eggplant (Chinese or globe), in finger-size strips", 680, 169228), ("1 lb", "ground turkey", 454, 171505),
             ("3", "garlic cloves, minced", 9, 169230), ("1 Tbsp", "minced ginger", 6, 169231), ("3", "scallions, sliced", 45, 170005),
             ("2 Tbsp", "low-sodium soy sauce", 32, 172473), ("1 Tbsp", "rice or white vinegar", 15, 172237),
             ("1 tsp", "sugar", 4.2, 169655), ("1 Tbsp + 3 Tbsp water", "cornstarch", 8, 169698),
             ("2 Tbsp", "canola oil", 28, 172336), ("1 cup", "low-sodium chicken broth", 240, 171609),
             ("3 cups", "cooked brown rice", 585, 169704)],
       steps=["Heat 1 Tbsp oil in a large skillet. Add the eggplant and 1/4 cup water, cover, and cook 8 minutes, stirring once, until soft. Move to a bowl.",
              "Add the remaining oil and the turkey. Cook, breaking it up, 6 to 8 minutes, until no pink remains (165°F).",
              "Add garlic, ginger and most of the scallions. Stir 1 minute.",
              "Return the eggplant. Add broth, soy sauce, vinegar and sugar. Simmer 3 minutes.",
              "Stir in the cornstarch mixed with water until glossy. Top with scallions. Serve with rice."],
       soft="Peel the eggplant and cook it 5 minutes longer.",
       store="Fridge 3 days.", tags=["high_protein", "fiber"])

recipe(id="G15", cat="Dinner", name="Hand-torn cabbage with pork", native="shǒu sī bāo cài (Chinese)", serves=3, active=15, total=20,
       intro="You tear the cabbage with your hands. Good for grip, good for dinner. Chang says it's his 'grip program'. It's not. It's cabbage.",
       ings=[("1 lb", "green cabbage, torn into pieces", 454, 169975), ("12 oz", "pork loin, thinly sliced", 340, 168230),
             ("3", "garlic cloves, sliced", 9, 169230), ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1 Tbsp", "rice or white vinegar", 15, 172237), ("1/2 tsp", "sugar", 2, 169655),
             ("1 Tbsp", "canola oil", 14, 172336), ("1/2 tsp", "red pepper flakes (optional)", 0.9, 170932),
             ("1 1/2 cups", "cooked brown rice", 293, 169704)],
       steps=["Heat the oil in a wok or large skillet over high heat. Cook the pork 3 to 4 minutes, until no pink remains (145°F). Move to a plate.",
              "Add garlic and pepper flakes for 20 seconds, then the cabbage. Stir-fry 4 to 5 minutes until wilted with some crisp edges.",
              "Return the pork. Add soy sauce, vinegar and sugar. Toss 1 minute. Serve with rice."],
       soft="Cut the cabbage in small pieces and cook it 3 minutes longer, covered.",
       store="Fridge 3 days.", tags=["high_protein", "fiber"])

recipe(id="G16", cat="Lunch", name="Edamame, corn and cucumber salad with tofu", native="Sun's summer bowl", serves=2, active=10, total=10,
       intro="No cooking except thawing. Crunchy, sweet, sesame. Twenty-something grams of protein and a lot of fiber in a bowl you can eat cold on the porch.",
       ings=[("1 1/2 cups", "frozen shelled edamame, cooked and cooled", 233, 168411), ("1 cup", "frozen corn, thawed", 136, 168398),
             ("1 medium", "cucumber, diced", 200, 168409), ("1/2 block (7 oz)", "extra-firm tofu, cubed", 198, 174290),
             ("1", "scallion, sliced", 15, 170005), ("1 Tbsp", "rice or white vinegar", 15, 172237),
             ("1 tsp", "toasted sesame oil", 4.5, 171016), ("1 tsp", "low-sodium soy sauce", 5, 172473), ("1 tsp", "toasted sesame seeds", 3, 170151)],
       steps=["Whisk the vinegar, sesame oil and soy sauce in a bowl.",
              "Add the edamame, corn, cucumber, tofu and scallion. Toss.",
              "Top with sesame seeds. Eat cold."],
       soft="Use soft tofu, peel and seed the cucumber, and mash the edamame lightly.",
       store="Fridge 2 days.", tags=["fiber"])

recipe(id="G17", cat="Dinner", name="Beef and vegetable glass noodles, lighter", native="japchae (Korean)", serves=4, active=35, total=40,
       intro="Japchae is party food. I made it Tuesday food: more vegetables, more beef, fewer noodles. Nobody at the party complained.",
       ings=[("4 oz dry", "sweet potato glass noodles (dangmyeon)", 113, 174258), ("12 oz", "top sirloin, in thin strips", 340, 174055),
             ("5 oz", "fresh spinach", 142, 168462), ("2 medium", "carrots, in matchsticks", 122, 170393),
             ("1 medium", "onion, sliced", 110, 170000), ("4 oz", "fresh shiitake mushrooms, sliced", 113, 169242),
             ("1 medium", "red bell pepper, in strips", 119, 170108), ("2", "large eggs (thin omelet, cooked firm)", 100, 171287),
             ("3 Tbsp", "low-sodium soy sauce", 48, 172473), ("1 Tbsp", "honey", 21, 169640), ("1 Tbsp", "toasted sesame oil", 13.6, 171016),
             ("1 Tbsp", "canola oil", 14, 172336), ("3", "garlic cloves, grated", 9, 169230), ("1 Tbsp", "toasted sesame seeds", 9, 170151)],
       steps=["Cook the noodles in boiling water 6 minutes, drain, rinse, and cut with scissors into shorter lengths.",
              "Blanch the spinach 30 seconds, rinse cold, squeeze dry.",
              "Beat the eggs and cook as a thin omelet in a nonstick pan until fully set. Roll and slice into strips.",
              "Stir-fry the beef in half the oil until no pink remains. Remove. Stir-fry the onion, carrots, mushrooms and pepper in the rest, 4 minutes.",
              "Mix soy sauce, honey, sesame oil and garlic. Toss everything together with the sauce. Top with sesame seeds."],
       soft="Cut the noodles and vegetables short and cook the vegetables 2 minutes longer.",
       store="Fridge 3 days. Eat at room temperature or warm gently.", tags=["leafy_greens", "honey", "high_protein", "eggs"])

recipe(id="G18", cat="Lunch", name="Cold soy-milk noodle soup", native="kongguksu (Korean)", serves=2, active=15, total=20,
       intro="The summer noodle. Cold, creamy, nutty. Traditionally you grind soaked soybeans; this shortcut uses soy milk and tofu. My mother would call it lazy. My knees call it smart.",
       ings=[("3 cups", "unsweetened soy milk, chilled", 729, 175215), ("1/2 block (7 oz)", "soft tofu", 198, 172449),
             ("2 Tbsp", "toasted sesame seeds", 18, 170151), ("1/2 tsp", "salt", 3, 173468),
             ("4 oz dry (about 2 cups cooked)", "whole-wheat spaghetti", 280, 168910), ("1/2 medium", "cucumber, in matchsticks", 100, 168409),
             ("2", "hard-boiled eggs, halved", 100, 171287)],
       steps=["Blend the soy milk, tofu, sesame seeds and salt until smooth. Chill.",
              "Cook the noodles, then rinse under cold water until cold.",
              "Divide noodles into bowls, pour the cold soy broth over, top with cucumber and a hard-boiled egg (boiled 10 minutes, yolk firm)."],
       soft="Cook the noodles 2 minutes longer and cut them short; skip the cucumber.",
       store="Broth keeps 3 days in the fridge. Assemble fresh.", tags=["high_protein", "fiber", "eggs"])

recipe(id="G19", cat="Soup", name="Tomato, tofu and egg soup with peas", native="fānqié dòufu dàn huā tāng (Chinese)", serves=4, active=10, total=25,
       intro="Sweet-sour broth, soft tofu, egg ribbons. When a grandchild is sick, I make this. When I'm tired, Chang makes this. He's getting better at it. Seven out of ten.",
       ings=[("4 medium", "tomatoes, in wedges", 492, 170457), ("1 block (14 oz)", "firm tofu, in cubes", 397, 172448),
             ("3", "large eggs, beaten", 150, 171287), ("4 cups", "low-sodium chicken broth", 960, 171609), ("2 cups", "water", 0, None),
             ("1 cup", "frozen peas", 134, 170016), ("1 tsp", "sugar", 4.2, 169655), ("1/2 tsp", "salt", 3, 173468),
             ("2", "scallions, sliced", 30, 170005), ("1 Tbsp", "canola oil", 14, 172336)],
       steps=["Heat the oil in a pot. Cook the tomatoes 5 minutes, pressing them, until saucy.",
              "Add broth, water, sugar and salt. Simmer 8 minutes.",
              "Add tofu and peas. Simmer 3 minutes.",
              "Stir the soup in a circle and drizzle in the eggs. Simmer 1 minute more so the egg is fully cooked. Top with scallions."],
       soft="Already soft.",
       store="Fridge 3 days. Reheat until steaming.", tags=["eggs", "salty"])

recipe(id="G20", cat="Dinner", name="Gochujang chicken with sweet potato and broccoli", native="Sun's sheet-pan dinner", serves=4, active=15, total=45,
       intro="One pan. You chop, you toss, you sit down. Forty-five minutes later dinner happens. This is how women my age should cook on weeknights: sitting down.",
       ings=[("1 1/2 lb", "boneless, skinless chicken thighs, in large pieces", 680, 173627), ("2 medium", "sweet potatoes, in 1-inch cubes", 260, 168482),
             ("1 lb", "broccoli florets", 454, 170379), ("1 medium", "onion, in wedges", 110, 170000),
             ("2 Tbsp", "gochujang", 38, "gochujang"), ("1 Tbsp", "honey", 21, 169640), ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1 Tbsp", "canola oil", 14, 172336), ("2", "garlic cloves, grated", 6, 169230), ("1 tsp", "toasted sesame seeds", 3, 170151)],
       steps=["Heat the oven to 425°F. Line a large sheet pan with foil or parchment.",
              "Mix gochujang, honey, soy sauce, oil and garlic. Toss the chicken in half; toss the sweet potato and onion in the rest.",
              "Spread the sweet potato and onion on the pan. Roast 15 minutes.",
              "Add the chicken and broccoli. Roast 20 to 25 minutes more, until the chicken reads 165°F and the sweet potato is soft.",
              "Sprinkle with sesame seeds."],
       soft="Cut everything small and roast the sweet potato 10 minutes longer.",
       store="Fridge 3 days. Reheat to 165°F.", tags=["high_protein", "fiber", "honey", "leafy_greens"])

recipe(id="G21", cat="Breakfast", name="Overnight oats with soy milk, kiwi and flax", native="Sun's night-before breakfast", serves=1, active=5, total=5,
       intro="Make it before bed. In the morning, breakfast is waiting and you have no excuse. Twenty-nine grams of protein. Nine of fiber.",
       ings=[("1/2 cup", "old-fashioned rolled oats", 40, 173904), ("1/2 cup", "unsweetened soy milk", 122, 175215),
             ("3/4 cup", "plain nonfat Greek yogurt", 170, 170894), ("1 Tbsp", "ground flaxseed", 7, 169414),
             ("1", "green kiwi, diced", 75, 168153), ("1 Tbsp", "chopped walnuts", 7, 170187)],
       steps=["Stir the oats, soy milk, yogurt and flaxseed together in a jar.",
              "Cover and refrigerate overnight (at least 6 hours).",
              "In the morning, top with kiwi and walnuts."],
       soft="Use quick oats; swap the kiwi for a ripe mashed banana or persimmon; grind the walnuts.",
       store="Up to 2 days in the fridge without the fruit.", tags=["fiber", "kiwi"])

recipe(id="G22", cat="Snack", name="Steamed sweet potato and egg plate", native="goguma and salted eggs, the Korean train snack", serves=1, active=5, total=30,
       intro="Korean grandmothers pack this for train trips. Sweet potato, eggs, a little kimchi. Fifteen grams of protein and it travels.",
       ings=[("1 small", "sweet potato, steamed or boiled in its skin", 130, 168484), ("2", "hard-boiled eggs", 100, 171287),
             ("1/4 cup", "kimchi", 38, 170392)],
       steps=["Steam or boil the whole sweet potato 25 to 30 minutes, until a knife slides in.",
              "Boil the eggs 10 minutes, until the yolks are completely firm; cool and peel.",
              "Plate with kimchi. Eat warm or cold."],
       soft="Mash the sweet potato and chop the eggs.",
       store="Cooked sweet potatoes and peeled eggs keep 4 days in the fridge.", tags=["kimchi", "eggs"])

recipe(id="G23", cat="Dessert", name="Steamed Asian pear with jujube and ginger", native="baesuk (Korean)", serves=2, active=10, total=40,
       intro="Korean mothers steam pears when someone has a cough. Tradition, not medicine. The honey part has some evidence for a cough from a cold. The rest is just a lovely dessert with 5 grams of fiber.",
       ings=[("1 large", "Asian pear, halved and cored", 275, 168177), ("4", "dried jujubes, sliced", 16, 168152),
             ("3 thin slices", "fresh ginger", 6, 169231), ("1 tsp (optional)", "honey", 7, 169640)],
       steps=["Put the pear halves cut-side up in a heatproof bowl. Tuck jujube slices and ginger into the hollows. Drizzle honey if using.",
              "Steam, covered, over simmering water 25 to 30 minutes, until soft.",
              "Eat warm with the juices, with a spoon."],
       soft="Already soft. Remove the ginger slices.",
       store="Fridge 2 days.", tags=["honey"])

recipe(id="G24", cat="Snack", name="Persimmon, walnut and yogurt cup", native="Sun's autumn snack", serves=1, active=3, total=3,
       intro="In October our tree drops more persimmons than two people can eat. So you get this. Out of season, use a ripe pear.",
       ings=[("1", "ripe Fuyu persimmon, diced", 168, 169941), ("1/2 cup", "plain nonfat Greek yogurt", 113, 170894),
             ("1 Tbsp", "chopped walnuts", 7, 170187), ("pinch", "cinnamon", 0, None)],
       steps=["Spoon the yogurt into a cup.", "Top with persimmon, walnuts and cinnamon."],
       soft="Use a very ripe persimmon, peeled; grind the walnuts.",
       store="Assemble fresh.", tags=["fiber"])

recipe(id="G25", cat="Side", name="Cucumber and seaweed salad", native="oi-miyeok-muchim (Korean)", serves=4, active=10, total=20,
       intro="Cold, sour, crunchy. Good next to anything fried. Seaweed: small portions, and ask your doctor if you have a thyroid condition.",
       ings=[("1/4 oz dry (about 1/2 cup soaked)", "dried wakame (calculated as 70 g soaked)", 70, 170496), ("2 medium", "cucumbers, thinly sliced", 400, 168409),
             ("2 Tbsp", "rice or white vinegar", 30, 172237), ("1 tsp", "sugar", 4.2, 169655), ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1 tsp", "toasted sesame seeds", 3, 170151), ("1/4 tsp", "salt", 1.5, 173468), ("1/2 tsp", "Korean chili flakes (optional)", 0.9, 170932)],
       steps=["Soak the wakame in cold water 10 minutes. Drain, squeeze, and chop.",
              "Toss the cucumber with the salt; wait 10 minutes; squeeze out the water.",
              "Mix vinegar, sugar and soy sauce. Toss with cucumber and seaweed. Top with sesame seeds and chili."],
       soft="Peel and seed the cucumber; chop the seaweed finely.",
       store="Fridge 2 days.", tags=["seaweed"])

recipe(id="G26", cat="Soup", name="Soybean sprout soup with tofu and egg", native="kongnamul-guk (Korean)", serves=4, active=10, total=25,
       intro="Clean, light, crunchy sprouts. Koreans eat it the morning after a big night. I eat it the morning after a big K-drama night. Same thing.",
       ings=[("12 oz", "soybean sprouts (cooked in the soup)", 340, 168460), ("1/2 block (7 oz)", "soft tofu, cubed", 198, 172449),
             ("2", "large eggs, beaten", 100, 171287), ("3", "garlic cloves, minced", 9, 169230), ("2", "scallions, sliced", 30, 170005),
             ("4 cups", "low-sodium chicken broth", 960, 171609), ("2 cups", "water", 0, None), ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1/4 tsp", "salt", 1.5, 173468), ("1 tsp", "Korean chili flakes (optional)", 1.8, 170932)],
       steps=["Put the sprouts, garlic, broth and water in a pot. Cover and boil 8 minutes without lifting the lid (the sprouts stay crunchy and lose their raw smell).",
              "Add tofu, soy sauce and salt. Simmer 2 minutes.",
              "Drizzle in the eggs while stirring. Simmer 1 minute so the egg is fully cooked. Scallions and chili on top."],
       soft="Chop the sprouts after cooking.",
       store="Fridge 3 days.", tags=["eggs"])
