"""The six 12-week Strong Years programs. Movement programs have 6 program sessions each (phase 1–3 × A/B);
Gut Reset is food-led (12 weekly kitchen lessons + recipes). Same segment schema as the Daily Practice sessions."""
from sessions_spec import seg, same


def T(r, s, st, i):
    return dict(rebuild=r, steady=s, strong=st, iron=i)


def intro(title, lines, extra=()):
    return seg("Welcome", "intro", 35, vo=lines + ["Chest pain, dizziness or sharp pain: stop, sit, and call your doctor."],
               ost=[title, "Stop if chest pain, dizziness or sharp pain"] + list(extra))


def close(lines, sun=()):
    return seg("Close", "close", 25, vo=lines, sun=list(sun))


def warm_std():
    return [seg("Ankle pumps", "warmup", 25, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4)),
            seg("March", "warmup", 40, T(("seated_march", "main", "40 seconds"), ("standing_march", "main", "40 seconds"),
                                         ("standing_march", "harder", "40 seconds"), ("standing_march", "harder", "40 seconds")),
                vo=["Stand slowly. Hand on the counter.", "March. Easy rhythm. Breathe steady."]),
            seg("Shoulder rolls", "warmup", 20, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls", "8 rolls + circles", ("main", "main", "main", "harder")))]


def cool_std(secs=60):
    return [seg("Calf stretch", "cooldown", 40, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
            seg("Cyclic sighing", "cooldown", secs - 20 if secs > 40 else 30, same("cyclic_sigh", "30 seconds", "40 seconds", "40 seconds", "40 seconds", ("main",) * 4),
                vo=["Sit. Two sniffs in through the nose. One long sigh out.", "No holding."])]


CHECK_NOTE = "Same chair, shoes and time of day each checkpoint. Fitness checks, not medical tests."

PROGRAMS = []


def program(**k):
    PROGRAMS.append(k)


# =================================================================== STRONG AT 70
program(id="S70", name="Strong at 70",
    promise="Build the leg, arm and grip strength daily life asks for: chairs, stairs, the floor, the groceries.",
    who="Adults 60+ who can stand from a chair (hands allowed) and want structured strength training at home. Every level from Rebuild to Iron.",
    ask_first="Chest pain or unusual breathlessness with activity, fainting, recent surgery or fracture, a heart or kidney condition with symptoms, or a new hip or knee (follow your surgeon's precautions; kneeling may be off-limits).",
    equipment="Sturdy chair against a wall, kitchen counter, stairs with a rail, water jugs or grocery bags, a folded towel. Optional: the Strong Years band kit.",
    evidence=["E01", "E02", "E03", "E04", "E06", "E08", "E11", "E39", "E40", "E41", "E42", "E43", "E45", "E49"],
    week_days={"Mon": "A", "Tue": "Mobility", "Wed": "Balance", "Thu": "B", "Fri": "Breath + qigong", "Sat": "Walk-and-talk", "Sun": "Rest + stretch"},
    checkpoints=[("30-second chair stand", "Full stands in 30 s, arms crossed (H if hands used)", "E11, E49"),
                 ("Five chair stands, timed", "Seconds for 5 stands, arms crossed. More than 15 s is one of the European screening signs of low muscle strength: mention it to your doctor", "E06"),
                 ("30-second arm curl", "Full curls, same weight each time", "E49"),
                 ("Floor level", "0 = chair stands only · 1 = half-kneel and back with the chair · 2 = kneel and rise with the chair · 3 = sit to the floor and rise with the chair (someone home)", "E45, E08"),
                 ("Two-bag carry", "Seconds carrying two bags or jugs along the counter, up to 60 s", "E01")],
    sessions={
    "A1": dict(title="Legs and push", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Strong at 70 · A1", ["Strong at 70, phase one. Legs and push.", "Weeks one to four we learn the moves and own them.", "Chair against the wall. Counter close."]),
        *warm_std(),
        seg("Legs", "block", 110, T(("sit_to_stand", "easier", "2 sets of 8, hands on thighs"), ("sit_to_stand", "main", "3 sets of 8"),
                                    ("sit_to_stand", "harder", "3 sets of 10, 3-second lower"), ("sit_to_stand", "harder", "3 sets of 10, jug at chest"))),
        seg("Push", "block", 90, T(("seated_chest_press", "main", "2 sets of 10"), ("wall_pushup", "main", "3 sets of 8"),
                                   ("counter_pushup", "main", "3 sets of 8"), ("counter_pushup", "harder", "3 sets of 10, 3-second lower"))),
        seg("Suitcase lift", "block", 80, T(("seated_hinge", "main", "2 sets of 8"), ("suitcase_lift", "main", "2 sets of 8 each side"),
                                            ("suitcase_lift", "main", "3 sets of 8 each side"), ("suitcase_lift", "harder", "3 sets of 8 each side, heavy bag"))),
        seg("Heel raises", "block", 50, T(("heel_raise", "easier", "2 sets of 12, seated"), ("heel_raise", "main", "2 sets of 10"),
                                          ("heel_raise", "harder", "2 sets of 12, one hand"), ("heel_raise", "harder", "2 sets of 8 each leg"))),
        seg("Floor practice", "block", 80, T(("sit_to_stand", "easier", "1 set of 5 (no floor)"), ("floor_practice", "easier", "2 half-kneels each side"),
                                             ("floor_practice", "easier", "3 half-kneels each side"), ("floor_practice", "main", "2 kneel-and-rise")),
            vo=["Chair or sofa beside you. Towel down. Someone else home.", "Step back, lower one knee to the towel. Hands on the chair.", "Push up through the front foot. Breathe out. Stand still a moment."],
            ost=["Only with a sturdy chair and someone home"]),
        *cool_std(),
        close(["Legs first. Push second. Deposit made.", "Thursday: pull and carry."])]),
    "B1": dict(title="Pull and carry", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Strong at 70 · B1", ["Strong at 70. Pull and carry.", "Your back and your grip do the work you don't notice.", "Bags, jugs, the band if you have it."]),
        *warm_std(),
        seg("Row", "block", 90, T(("towel_row", "main", "4 pulls, 3-second squeeze"), ("jug_row", "main", "2 sets of 10 each arm"),
                                  ("band_row", "main", "3 sets of 10"), ("band_row", "harder", "3 sets of 12, pause"))),
        seg("Step-ups", "block", 90, T(("seated_march", "harder", "2 × 30 seconds, knees high"), ("step_up", "easier", "2 sets of 10 toe taps"),
                                       ("step_up", "main", "2 sets of 8 each leg"), ("step_up", "harder", "3 sets of 8 each leg, bag"))),
        seg("Hinge", "block", 80, T(("seated_hinge", "main", "2 sets of 8"), ("hip_hinge", "main", "2 sets of 10"),
                                    ("hip_hinge", "harder", "3 sets of 8, jug from the chair"), ("hip_hinge", "harder", "3 sets of 8, bag from the step"))),
        seg("Curls", "block", 55, same("bottle_curl", "2 sets of 10, bottles", "2 sets of 10, half-gallon jug", "3 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", ("main", "harder", "harder", "harder"))),
        seg("One-side carry", "block", 70, T(("towel_wring", "main", "3 wrings each way"), ("suitcase_carry", "easier", "2 × 20 seconds each side"),
                                             ("suitcase_carry", "main", "2 × 30 seconds each side"), ("suitcase_carry", "harder", "3 × 30 seconds each side"))),
        seg("Towel wring", "block", 40, same("towel_wring", "2 each way", "3 each way", "3 each way", "3 each way, damp towel", ("easier", "main", "main", "harder"))),
        *cool_std(),
        close(["Pull and carry. That's groceries, grandkids and doors.", "Monday: legs again."])]),
    "A2": dict(title="Power and floor", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Strong at 70 · A2", ["Phase two. Power and the floor.", "Fast up, slow down. Then practise the floor.", "Chair against the wall. Someone home for the floor part."]),
        *warm_std(),
        seg("Power stands", "block", 100, T(("sit_to_stand", "easier", "3 sets of 6, normal speed"), ("power_stand", "main", "3 sets of 5"),
                                            ("power_stand", "harder", "3 sets of 6, jug"), ("power_stand", "harder", "3 sets of 8, jug (advanced)"))),
        seg("Push", "block", 85, T(("seated_chest_press", "harder", "3 sets of 10, band"), ("counter_pushup", "main", "2 sets of 8"),
                                   ("counter_pushup", "harder", "3 sets of 10, 3-second lower"), ("counter_pushup", "harder", "3 sets of 12, 3-second lower"))),
        seg("Floor practice", "block", 90, T(("sit_to_stand", "easier", "1 set of 6 (no floor)"), ("floor_practice", "main", "2 kneel-and-rise"),
                                             ("floor_practice", "main", "3 kneel-and-rise"), ("floor_practice", "harder", "2 sit-to-floor and rise")),
            vo=["Chair beside you. Towel down. Someone else home.", "Kneel. Then front foot flat. Push up with hands on the chair.", "Breathe out as you rise. Earn the floor."],
            ost=["Only with a sturdy chair and someone home"]),
        seg("Suitcase lift", "block", 75, T(("seated_hinge", "harder", "2 sets of 8, bottle at chest"), ("suitcase_lift", "main", "3 sets of 8 each side"),
                                            ("suitcase_lift", "harder", "3 sets of 8 each side, from the step"), ("suitcase_lift", "harder", "3 sets of 10 each side, heavier"))),
        seg("High wall sit", "block", 55, T(("seated_knee_ext", "main", "2 sets of 10 each leg"), ("wall_sit_high", "main", "2 holds of 20 seconds"),
                                            ("wall_sit_high", "main", "3 holds of 20 seconds"), ("wall_sit_high", "harder", "3 holds of 30 seconds")),
            vo=["Back on the wall. A few inches down. Chair beside you.", "Keep talking. Count out loud.", "High blood pressure? Short holds, and ask your doctor about longer ones."],
            ost=["Keep breathing: count out loud"]),
        *cool_std(),
        close(["Getting up fast is what saves you when you trip.", "Thursday: stairs and carries."])]),
    "B2": dict(title="Stairs and carries", set="SET-STOOP", wardrobe="C-TRAIN-A", segments=[
        intro("Strong at 70 · B2", ["Phase two. Stairs and carries.", "Rail hand never lets go.", "Bags ready."]),
        *warm_std(),
        seg("Stair practice", "block", 100, T(("seated_march", "harder", "3 × 30 seconds, knees high"), ("stair_climb", "easier", "Bottom 3 steps, 4 times"),
                                              ("stair_climb", "main", "1 flight, twice"), ("stair_climb", "harder", "2 flights, bag in free hand"))),
        seg("Row", "block", 80, T(("band_row", "easier", "2 sets of 10, close to the door"), ("band_row", "main", "3 sets of 10"),
                                  ("band_row", "harder", "3 sets of 12, pause"), ("band_row", "harder", "3 sets of 12, stronger band"))),
        seg("Two-hand carry", "block", 70, T(("towel_wring", "main", "3 wrings each way"), ("carry", "main", "2 × 30 seconds"),
                                             ("carry", "harder", "3 × 40 seconds"), ("carry", "harder", "3 × 45 seconds, heavy"))),
        seg("Band pull-apart", "block", 50, same("band_pull_apart", "2 sets of 8", "2 sets of 10", "3 sets of 10", "3 sets of 12", ("easier", "main", "main", "harder"))),
        seg("Overhead press", "block", 60, T(("seated_press", "easier", "2 sets of 6, one arm at a time"), ("seated_press", "main", "2 sets of 8"),
                                             ("seated_press", "main", "3 sets of 10"), ("seated_press", "harder", "3 sets of 10, half-gallon jugs"))),
        seg("Towel wring", "block", 40, same("towel_wring", "2 each way", "3 each way", "3 each way", "3 each way, damp towel", ("easier", "main", "main", "harder"))),
        *cool_std(),
        close(["Stairs and bags. You trained real life today.", "Rest well."])]),
    "A3": dict(title="Strong", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Strong at 70 · A3", ["Phase three. Strong.", "Heavier where you can, slower where you can't.", "Chair against the wall. Someone home for the floor."]),
        *warm_std(),
        seg("Legs", "block", 110, T(("sit_to_stand", "main", "3 sets of 8, arms crossed if you can"), ("sit_to_stand", "harder", "3 sets of 10, jug at chest"),
                                    ("split_squat", "main", "3 sets of 8 each leg"), ("split_squat", "harder", "3 sets of 10 each leg, jug (advanced)"))),
        seg("Push", "block", 80, T(("seated_chest_press", "harder", "3 sets of 12, band"), ("counter_pushup", "main", "3 sets of 10"),
                                   ("counter_pushup", "harder", "3 sets of 12, 3-second lower"), ("counter_pushup", "harder", "3 sets of 12, pause at the bottom"))),
        seg("Floor practice", "block", 90, T(("sit_to_stand", "easier", "2 sets of 6 (no floor)"), ("floor_practice", "main", "3 kneel-and-rise"),
                                             ("floor_practice", "harder", "2 sit-to-floor and rise"), ("floor_practice", "harder", "3 sit-to-floor and rise")),
            vo=["Chair beside you. Towel down. Someone home.", "Down with control. Up with a push. Breathe out.", "Stand still a moment before you walk."],
            ost=["Only with a sturdy chair and someone home"]),
        seg("Suitcase lift", "block", 75, T(("seated_hinge", "harder", "3 sets of 8, bottle at chest"), ("suitcase_lift", "harder", "3 sets of 8 each side, from the step"),
                                            ("suitcase_lift", "harder", "3 sets of 10 each side, heavier"), ("suitcase_lift", "harder", "3 sets of 12 each side, heavy bag"))),
        seg("Heel raises", "block", 50, T(("heel_raise", "easier", "3 sets of 12, seated"), ("heel_raise", "harder", "3 sets of 12, one hand"),
                                          ("heel_raise", "harder", "3 sets of 8 each leg"), ("heel_raise", "harder", "3 sets of 12 each leg"))),
        *cool_std(),
        close(["Twelve weeks ago, this was a lot. Look at you.", "Thursday: the last B session."])]),
    "B3": dict(title="Strong carries", set="SET-STOOP", wardrobe="C-TRAIN-A", segments=[
        intro("Strong at 70 · B3", ["Phase three. Strong carries, stairs, pulls.", "Rail hand never lets go.", "Bags ready."]),
        *warm_std(),
        seg("Step-ups", "block", 95, T(("seated_march", "harder", "3 × 30 seconds, knees high"), ("step_up", "main", "3 sets of 8 each leg"),
                                       ("step_up", "harder", "3 sets of 8 each leg, bag"), ("step_up", "harder", "3 sets of 10 each leg, heavier bag"))),
        seg("Row", "block", 80, T(("band_row", "main", "3 sets of 10"), ("band_row", "harder", "3 sets of 12, pause"),
                                  ("band_row", "harder", "3 sets of 12, stronger band"), ("jug_row", "harder", "3 sets of 12 each arm, heavy bag"))),
        seg("Band press-out", "block", 60, T(("pallof_press", "easier", "2 sets of 6 each side, seated"), ("pallof_press", "main", "2 sets of 8 each side"),
                                             ("pallof_press", "harder", "3 sets of 8 each side, 5-second hold"), ("pallof_press", "harder", "3 sets of 10 each side, 5-second hold"))),
        seg("Two-hand carry", "block", 75, T(("towel_wring", "main", "4 wrings each way"), ("carry", "harder", "3 × 30 seconds, heavier"),
                                             ("carry", "harder", "3 × 45 seconds, heavy"), ("carry", "harder", "3 × 60 seconds, heavy"))),
        seg("Curls", "block", 55, same("bottle_curl", "2 sets of 10, half-gallon jug", "3 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", "3 sets of 12, gallon jug", ("harder",) * 4)),
        *cool_std(),
        close(["Strong at 70. Not a slogan. A checkpoint.", "Your final checkpoint is this weekend."])]),
    })

# =================================================================== BACK STRONG
program(id="BKS", name="Back Strong",
    promise="A back-friendly strength program to help you move with less stiffness: bend, carry, turn and walk with more confidence.",
    who="Adults 60+ with an everyday stiff or achy back who are cleared for exercise. Not a treatment for any back condition.",
    ask_first="Back pain after a fall, fever with back pain, night pain that wakes you and doesn't change with position, numbness in the saddle area, new leg weakness or loss of bladder or bowel control: those are for your doctor, today, not this program. Osteoporosis or a past spine fracture: you can do this program, following the long-back rule on every bend, and check with your doctor first.",
    equipment="Chair against a wall, kitchen counter, your bed, a grocery bag or jug, walking shoes. Optional: a resistance band with door anchor.",
    evidence=["E30", "E30b", "E40", "E41", "E60", "E22", "E43", "E46"],
    week_days={"Mon": "A", "Tue": "Mobility", "Wed": "B", "Thu": "Strength", "Fri": "Breath + qigong", "Sat": "Walk-and-talk", "Sun": "Rest + stretch"},
    walking=["10 min, 3 days", "12 min, 3 days", "15 min, 4 days", "12 min, 3 days (easy week)", "18 min, 4 days", "20 min, 4 days", "22 min, 5 days", "18 min, 4 days (easy week)",
             "25 min, 5 days", "25 min, 5 days", "30 min, 5 days", "30 min, 5 days"],
    checkpoints=[("Morning stiffness", "0–10, first 10 minutes after getting up (0 = none)", "self-rating"),
                 ("Sock test", "Putting on socks seated: easy / some effort / hard / need help", "self-rating"),
                 ("Jug pick-up comfort", "Hinge a half-gallon jug from a chair seat and back, 5 times: discomfort 0–10", "E40, E41"),
                 ("Comfortable walking", "Minutes you can walk at an easy pace before stiffness makes you stop, up to 30", "E60, E22"),
                 ("30-second chair stand", "Full stands", "E11")],
    sessions={
    "A1": dict(title="Hinge and brace", set="SET-KITCHEN", wardrobe="C-TRAIN-B", segments=[
        intro("Back Strong · A1", ["Back Strong. Phase one: hinge and brace.", "Our goal is moving with less stiffness. A stronger, more confident back.",
                                   "Pain rule: up to three out of ten, settled by tomorrow, is okay. Worse the next day, back off."]),
        *warm_std(),
        seg("Seated hinge", "block", 60, same("seated_hinge", "6 small hinges", "8 hinges", "10 hinges", "10 hinges, bottle at chest", ("easier", "main", "main", "harder"))),
        seg("Counter hip hinge", "block", 80, T(("seated_hinge", "main", "2 sets of 8"), ("hip_hinge", "easier", "2 sets of 8, hands on the counter"),
                                                ("hip_hinge", "main", "2 sets of 10"), ("hip_hinge", "harder", "3 sets of 8, jug from the chair"))),
        seg("Standing bird-dog", "block", 70, T(("standing_birddog", "easier", "4 each side, leg only"), ("standing_birddog", "main", "6 each side"),
                                                ("standing_birddog", "harder", "8 each side, 3-second hold"), ("standing_birddog", "harder", "10 each side, 3-second hold"))),
        seg("Side lean at the counter", "block", 60, T(("chest_lift", "main", "8 lifts, seated"), ("counter_side_plank", "easier", "2 × 5 seconds each side"),
                                                        ("counter_side_plank", "main", "2 × 10 seconds each side"), ("counter_side_plank", "harder", "3 × 15 seconds each side"))),
        seg("Bridge on the bed", "block", 60, same("bed_bridge", "6 squeezes", "2 sets of 8", "2 sets of 10, 3-second hold", "3 sets of 10, 3-second hold", ("easier", "main", "harder", "harder"))),
        seg("Clamshell on the bed", "block", 60, same("clam_bed", "6 each side, small", "8 each side", "10 each side", "10 each side, band", ("easier", "main", "main", "harder"))),
        seg("Stand up slowly", "cooldown", 30, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4),
            vo=["Roll to your side. Push up to sitting. Ankle pumps.", "Sit a moment before you stand. Then stand slowly, holding something."], ost=["Sit a moment before you stand"]),
        seg("4-6 breathing", "cooldown", 40, same("breath_46", "40 seconds", "40 seconds", "40 seconds", "40 seconds", ("main",) * 4)),
        close(["Long back, strong hips. That's the foundation.", "Walk today: check your walking minutes on the plan."])]),
    "B1": dict(title="Turn and carry", set="SET-LIVING", wardrobe="C-CASUAL", segments=[
        intro("Back Strong · B1", ["Back Strong. Turn and carry.", "Gentle turning, then carrying on one side, standing tall.", "Osteoporosis: turns stay small and gentle. Never force a twist."]),
        seg("Pelvic tilt on the bed", "warmup", 50, same("pelvic_tilt_bed", "6 small tilts", "8 tilts", "10 tilts, 2-second hold", "10 tilts, 5-second hold", ("easier", "main", "main", "harder"))),
        seg("Knee rocks on the bed", "warmup", 50, same("knee_rock_bed", "4 each side, tiny", "6 each side", "8 each side", "8 each side, pause", ("easier", "main", "main", "harder"))),
        seg("Stand up slowly", "warmup", 30, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4),
            vo=["Roll to your side, push up to sitting. Ankle pumps.", "Sit a moment, then stand slowly, holding something."], ost=["Sit a moment before you stand"]),
        seg("Chest lift", "block", 45, same("chest_lift", "6 lifts", "8 lifts", "8 lifts, 3-second hold", "10 lifts, 3-second hold", ("easier", "main", "harder", "harder"))),
        seg("Wall slides", "block", 45, same("wall_slide", "6 finger walks", "8 slides", "10 slides", "10 slides, 2-second hold", ("easier", "main", "main", "harder"))),
        seg("Band press-out", "block", 70, T(("pallof_press", "easier", "2 sets of 6 each side, seated"), ("pallof_press", "main", "2 sets of 8 each side"),
                                             ("pallof_press", "main", "3 sets of 8 each side"), ("pallof_press", "harder", "3 sets of 8 each side, 5-second hold"))),
        seg("One-side carry", "block", 75, T(("towel_wring", "main", "3 wrings each way"), ("suitcase_carry", "easier", "2 × 20 seconds each side"),
                                             ("suitcase_carry", "main", "2 × 30 seconds each side"), ("suitcase_carry", "harder", "3 × 30 seconds each side, heavier"))),
        seg("Standing hip-front stretch", "block", 60, T(("hip_flexor", "easier", "20 seconds each side, both hands down"), ("hip_flexor", "main", "2 × 20 seconds each side"),
                                                         ("hip_flexor", "main", "2 × 20 seconds each side"), ("hip_flexor", "harder", "2 × 30 seconds each side, arm up"))),
        seg("Gentle seated turn", "block", 45, same("seated_rotation", "4 each side, small", "6 each side", "6 each side", "8 each side", ("easier", "main", "main", "main"))),
        seg("Cyclic sighing", "cooldown", 40, same("cyclic_sigh", "40 seconds", "40 seconds", "40 seconds", "40 seconds", ("main",) * 4)),
        close(["Stand tall. Turn gently. Carry proud.", "Walk today, and log your stiffness tomorrow morning."])]),
    "A2": dict(title="Hinge with load", set="SET-KITCHEN", wardrobe="C-TRAIN-B", segments=[
        intro("Back Strong · A2", ["Phase two. We add load to the hinge.", "The long back stays. The jug gets heavier.", "Pain above three out of ten that doesn't settle by morning: go back a step."]),
        *warm_std(),
        seg("Counter hip hinge", "block", 70, T(("seated_hinge", "harder", "2 sets of 8, bottle at chest"), ("hip_hinge", "main", "3 sets of 8"),
                                                ("hip_hinge", "harder", "3 sets of 8, jug from the chair"), ("hip_hinge", "harder", "3 sets of 10, jug from the step"))),
        seg("Suitcase lift", "block", 80, T(("seated_hinge", "main", "2 sets of 8"), ("suitcase_lift", "easier", "2 sets of 6 each side, from a higher surface"),
                                            ("suitcase_lift", "main", "2 sets of 8 each side"), ("suitcase_lift", "harder", "3 sets of 8 each side, from the step"))),
        seg("Standing bird-dog", "block", 60, T(("standing_birddog", "easier", "6 each side, leg only"), ("standing_birddog", "harder", "8 each side, 3-second hold"),
                                                ("standing_birddog", "harder", "10 each side, 3-second hold"), ("standing_birddog", "harder", "12 each side, 3-second hold"))),
        seg("Side lean at the counter", "block", 60, T(("chest_lift", "harder", "8 lifts, 3-second hold"), ("counter_side_plank", "main", "2 × 10 seconds each side"),
                                                        ("counter_side_plank", "harder", "3 × 15 seconds each side"), ("counter_side_plank", "harder", "3 × 20 seconds each side"))),
        seg("Bridge on the bed", "block", 60, same("bed_bridge", "8 squeezes", "2 sets of 10", "3 sets of 10, 3-second hold", "3 sets of 12, 3-second hold", ("easier", "main", "harder", "harder"))),
        seg("Stand up slowly", "cooldown", 30, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4),
            vo=["Roll to your side. Sit up. Ankle pumps.", "Sit a moment before you stand. Then stand slowly, holding something."], ost=["Sit a moment before you stand"]),
        seg("4-6 breathing", "cooldown", 50, same("breath_46", "50 seconds", "50 seconds", "50 seconds", "50 seconds", ("main",) * 4)),
        close(["You lifted more with a long back. That's the whole program in one sentence.", "Walk today."])]),
    "B2": dict(title="Carry and walk", set="SET-YARD", wardrobe="C-TRAIN-B", segments=[
        intro("Back Strong · B2", ["Phase two. Carry, then walk.", "In a big trial of adults who'd recently recovered from low back pain, people who followed a walking program plus education sessions went longer before it came back: a median of 208 days versus 112.",
                                   "Walking is part of this program on purpose."], extra=["Study: 701 adults, walking + education, 6 months"]),
        seg("Pelvic tilt on the bed", "warmup", 45, same("pelvic_tilt_bed", "6 small tilts", "10 tilts", "10 tilts, 3-second hold", "12 tilts, 5-second hold", ("easier", "main", "harder", "harder"))),
        seg("Stand up slowly", "warmup", 30, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4),
            vo=["Sit up. Ankle pumps.", "Sit a moment, then stand slowly, holding something."], ost=["Sit a moment before you stand"]),
        seg("Band press-out", "block", 70, T(("pallof_press", "easier", "2 sets of 8 each side, seated"), ("pallof_press", "main", "3 sets of 8 each side"),
                                             ("pallof_press", "harder", "3 sets of 8 each side, 5-second hold"), ("pallof_press", "harder", "3 sets of 10 each side, 5-second hold"))),
        seg("One-side carry", "block", 75, T(("towel_wring", "main", "3 wrings each way"), ("suitcase_carry", "main", "2 × 30 seconds each side"),
                                             ("suitcase_carry", "harder", "3 × 30 seconds each side, heavier"), ("suitcase_carry", "harder", "3 × 45 seconds each side, heavy"))),
        seg("Walk", "block", 240, T(("seated_march", "main", "4 minutes: 1 on, 30 seconds off"), ("walk", "easier", "4 minutes easy"),
                                    ("walk", "main", "4 minutes, easy to brisk"), ("walk", "main", "4 minutes brisk")),
            vo=["Good shoes. Out the door or down the hallway.", "Tall. Arms swing. Easy pace to start.", "Stiff at first? Often it eases as you warm up. Sharp pain, stop.", "Breathe easy. You should be able to talk."]),
        seg("Standing hip-front stretch", "cooldown", 45, T(("hip_flexor", "easier", "20 seconds each side, both hands down"), ("hip_flexor", "main", "20 seconds each side"),
                                                            ("hip_flexor", "main", "20 seconds each side"), ("hip_flexor", "harder", "30 seconds each side"))),
        close(["Carry, walk, stretch. Your back likes all three.", "Log your walking minutes."])]),
    "A3": dict(title="Confident bending", set="SET-KITCHEN", wardrobe="C-TRAIN-B", segments=[
        intro("Back Strong · A3", ["Phase three. Confident bending.", "Pick up, put down, carry, turn. Like a real day.", "Long back. Always."]),
        *warm_std(),
        seg("Suitcase lift", "block", 85, T(("seated_hinge", "harder", "3 sets of 8, bottle at chest"), ("suitcase_lift", "main", "3 sets of 8 each side"),
                                            ("suitcase_lift", "harder", "3 sets of 8 each side, from the step"), ("suitcase_lift", "harder", "3 sets of 10 each side, heavy bag"))),
        seg("Hinge pick-up", "block", 75, T(("seated_hinge", "main", "2 sets of 10"), ("hip_hinge", "harder", "3 sets of 8, jug from the chair"),
                                            ("hip_hinge", "harder", "3 sets of 10, jug from the step"), ("hip_hinge", "harder", "3 sets of 10, heavy bag from the step"))),
        seg("Side lean at the counter", "block", 60, T(("chest_lift", "harder", "10 lifts, 3-second hold"), ("counter_side_plank", "harder", "3 × 15 seconds each side"),
                                                        ("counter_side_plank", "harder", "3 × 20 seconds each side"), ("counter_side_plank", "harder", "3 × 20 seconds each side, feet farther")),
            vo=["Forearm on the counter. Lean in a straight line.", "Keep talking. Count out loud.", "High blood pressure: keep holds short."]),
        seg("Standing bird-dog", "block", 60, T(("standing_birddog", "easier", "8 each side, leg only"), ("standing_birddog", "harder", "10 each side, 3-second hold"),
                                                ("standing_birddog", "harder", "12 each side, 3-second hold"), ("standing_birddog", "harder", "12 each side, 5-second hold"))),
        seg("Two-hand carry", "block", 60, T(("towel_wring", "main", "4 wrings each way"), ("carry", "main", "2 × 40 seconds"),
                                             ("carry", "harder", "3 × 40 seconds, heavier"), ("carry", "harder", "3 × 60 seconds, heavy"))),
        *cool_std(),
        close(["Twelve weeks of long-back bending. That's a habit now.", "Final checkpoint this weekend."])]),
    "B3": dict(title="Turn, carry, walk", set="SET-PROM", wardrobe="C-TRAIN-B", segments=[
        intro("Back Strong · B3", ["Phase three. Turn, carry, walk.", "Longer walk today.", "Good shoes. Flat route."]),
        seg("Gentle seated turn", "warmup", 45, same("seated_rotation", "4 each side, small", "6 each side", "8 each side", "8 each side", ("easier", "main", "main", "main"))),
        seg("Chest lift", "warmup", 35, same("chest_lift", "6 lifts", "8 lifts", "8 lifts, 3-second hold", "10 lifts, 3-second hold", ("easier", "main", "harder", "harder"))),
        seg("Band press-out", "block", 65, T(("pallof_press", "main", "2 sets of 8 each side, seated"), ("pallof_press", "harder", "3 sets of 8 each side, 5-second hold"),
                                             ("pallof_press", "harder", "3 sets of 10 each side, 5-second hold"), ("pallof_press", "harder", "3 sets of 12 each side, 5-second hold"))),
        seg("One-side carry", "block", 70, T(("towel_wring", "main", "4 wrings each way"), ("suitcase_carry", "harder", "3 × 30 seconds each side"),
                                             ("suitcase_carry", "harder", "3 × 45 seconds each side"), ("suitcase_carry", "harder", "3 × 60 seconds each side, heavy"))),
        seg("Walk", "block", 300, T(("seated_march", "main", "5 minutes: 1 on, 30 seconds off"), ("walk", "main", "5 minutes steady"),
                                    ("walk", "main", "5 minutes brisk"), ("walk", "harder", "5 minutes brisk, hills")),
            vo=["Out the door or down the hallway. Tall. Arms swing.", "Steady pace. Can talk, can't sing.", "Breathe easy. Notice how your back feels at minute five compared with week one."]),
        seg("Calf stretch at the rail", "cooldown", 40, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
        close(["Twelve weeks. Stronger back, more walking. Keep both.", "Final checkpoint this weekend."])]),
    })

# =================================================================== BALANCE & STEADY FEET
program(id="BAL", name="Balance & Steady Feet",
    promise="Otago-style leg strength and balance practice plus simplified tai chi, to help you feel steadier on your feet.",
    who="Adults 60+ who want to feel steadier on their feet and more confident on stairs, curbs and uneven ground. Every exercise is done at the kitchen counter.",
    ask_first="Dizziness or fainting, a fall with injury or head strike (especially on blood thinners), sudden new unsteadiness, or new numbness: see your doctor first. Using a walker: start at Rebuild, with both hands on the counter.",
    equipment="Kitchen counter, sturdy chair against a wall, a rolled bath towel, stairs with a rail (optional), shoes with grippy soles.",
    evidence=["E09", "E11", "E13", "E15", "E17", "E45", "E50", "E51"],
    week_days={"Mon": "Strength", "Tue": "A", "Wed": "Balance", "Thu": "B", "Fri": "Breath + qigong", "Sat": "Walk-and-talk", "Sun": "Rest + stretch"},
    checkpoints=[("Four-stage balance", "Last stage held 10 s (0–4). Under 10 s on heel-to-toe is worth mentioning to your doctor (CDC screening checkpoint)", "E50"),
                 ("Timed Up and Go", "Seconds, normal pace, helper beside you. 12 s or more = tell your doctor", "E51"),
                 ("One-leg stand", "Seconds up to 30, hand hovering over the counter, each leg", "E09"),
                 ("30-second chair stand", "Full stands", "E11"),
                 ("Confidence on your feet", "0–10: stairs, curbs, getting up at night, walking on grass", "self-rating")],
    sessions={
    "A1": dict(title="Otago foundations", set="SET-KITCHEN", wardrobe="C-TRAIN-B", segments=[
        intro("Balance · A1", ["Balance and Steady Feet. Phase one.", "These moves come from the Otago home program: leg strength, balance and walking, built for people in their 70s and 80s. Balance is one of the most trainable things there is.",
                               "We live at the counter. Hands hover, they don't wander."], extra=["Hands hover, they don't wander"]),
        seg("Weight shifts", "warmup", 45, same("weight_shift", "5 each way, seated", "6 each way", "8 each way", "8 each way, hand hovering", ("easier", "main", "harder", "harder"))),
        seg("Seated knee straightening", "block", 60, same("seated_knee_ext", "1 set of 8 each leg", "2 sets of 8 each leg", "2 sets of 10 each leg", "2 sets of 10 each leg, 3-second hold", ("main", "main", "main", "harder"))),
        seg("Side steps", "block", 50, same("side_step", "1 set of 6 each way", "2 sets of 10 each way", "2 sets of 10 each way, knees bent", "2 sets of 12 each way, knees bent", ("easier", "main", "harder", "harder"))),
        seg("Heel-to-toe stand", "block", 70, T(("tandem_stand", "easier", "3 × 10 seconds each side, half-step"), ("tandem_stand", "main", "3 × 10 seconds each side"),
                                                ("tandem_stand", "harder", "3 × 15 seconds each side, hand hovering"), ("tandem_stand", "harder", "3 × 20 seconds each side, hands hovering"))),
        seg("One-leg stand", "block", 70, T(("single_leg", "easier", "3 × 10 seconds each side, toe down"), ("single_leg", "main", "3 × 10 seconds each side"),
                                            ("single_leg", "harder", "3 × 15 seconds each side, hand hovering"), ("single_leg", "harder", "3 × 20 seconds each side, hands hovering"))),
        seg("Heel-to-toe walk", "block", 60, T(("heel_toe_walk", "easier", "2 lengths, feet apart"), ("heel_toe_walk", "main", "2 lengths"),
                                               ("heel_toe_walk", "harder", "2 lengths, hand hovering"), ("heel_toe_walk", "harder", "3 lengths, hand hovering"))),
        seg("Toe and heel walks", "block", 60, T(("heel_raise", "easier", "10 seated heel raises + 10 toe lifts"), ("toe_walk", "easier", "10 heel raises + 10 toe lifts at the counter"),
                                                 ("toe_walk", "main", "1 length toes + 1 length heels"), ("toe_walk", "main", "2 lengths toes + 2 heels"))),
        seg("Sit-to-stand, no hands", "block", 45, T(("sit_to_stand", "easier", "1 set of 5"), ("sit_stand_nohands", "main", "1 set of 6"),
                                                     ("sit_stand_nohands", "main", "2 sets of 6"), ("sit_stand_nohands", "harder", "2 sets of 6, feet together"))),
        seg("Cyclic sighing", "cooldown", 35, same("cyclic_sigh", "35 seconds", "35 seconds", "35 seconds", "35 seconds", ("main",) * 4)),
        close(["Steady feet are trained feet.", "Toothbrush balance tonight. Hand on the sink."])]),
    "B1": dict(title="Tai chi: shifting and clouds", set="SET-YARD", wardrobe="C-TRAIN-B", segments=[
        intro("Balance · B1", ["Tai chi day. Taught as exercise.", "Tai chi is slow balance practice: weight shifts, short steps and turns, done with control. We start small.",
                               "Fence or counter within reach. Chair behind you."], extra=["Slow like honey"]),
        seg("Cyclic sighing", "warmup", 60, same("cyclic_sigh", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4)),
        seg("Weight shifts", "block", 60, same("weight_shift", "6 each way, seated", "8 each way", "8 each way, bigger", "10 each way, hand hovering", ("easier", "main", "harder", "harder"))),
        seg("Cloud hands", "block", 120, same("cloud_hands", "2 minutes, seated", "2 minutes, near the fence", "2 minutes", "2 minutes with side steps", ("easier", "main", "main", "harder"))),
        seg("Brush knee", "block", 100, same("brush_knee", "4 each side, arms only", "4 each side", "6 each side", "4 steps across and back", ("easier", "main", "main", "harder"))),
        seg("Holding up the sky", "block", 60, same("sky_lift", "4 reps, seated", "5 reps", "6 reps", "6 reps, rise onto toes", ("easier", "main", "main", "harder"))),
        seg("Heel-to-toe stand", "block", 60, T(("tandem_stand", "easier", "2 × 10 seconds each side, half-step"), ("tandem_stand", "main", "2 × 15 seconds each side"),
                                                ("tandem_stand", "harder", "2 × 20 seconds each side, hand hovering"), ("tandem_stand", "harder", "2 × 30 seconds each side, hands hovering"))),
        seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4)),
        close(["Slow like honey. Soft knees.", "Weekend: walk."])]),
    "A2": dict(title="Otago steps", set="SET-KITCHEN", wardrobe="C-TRAIN-B", segments=[
        intro("Balance · A2", ["Phase two. New steps.", "Backward, over, around. Every step next to the counter.", "Shoes on. Clear floor."]),
        seg("Weight shifts", "warmup", 40, same("weight_shift", "5 each way, seated", "6 each way", "8 each way", "8 each way, hand hovering", ("easier", "main", "harder", "harder"))),
        seg("Backward walk", "block", 60, T(("weight_shift", "easier", "6 front-to-back shifts, seated"), ("backward_walk", "easier", "5 small steps, twice"),
                                            ("backward_walk", "main", "2 × 10 steps"), ("backward_walk", "harder", "3 × 10 steps, slower"))),
        seg("Step over a towel", "block", 60, T(("seated_march", "harder", "10 high knee lifts, seated"), ("step_over", "main", "8 each way"),
                                                ("step_over", "harder", "8 forward and back"), ("step_over", "harder", "10 forward and back"))),
        seg("Clock reach", "block", 55, same("clock_reach", "3 each way, front and side", "4 each direction", "4 each direction, one foot at 12", "5 each direction, one foot at 12", ("easier", "main", "harder", "harder"))),
        seg("One-leg stand", "block", 70, T(("single_leg", "easier", "3 × 15 seconds each side, toe down"), ("single_leg", "main", "3 × 15 seconds each side"),
                                            ("single_leg", "harder", "3 × 20 seconds each side, hand hovering"), ("single_leg", "harder", "3 × 30 seconds each side, hands hovering"))),
        seg("Stair practice", "block", 80, T(("seated_march", "harder", "2 × 30 seconds, knees high"), ("stair_climb", "easier", "Bottom 3 steps, 3 times"),
                                             ("stair_climb", "main", "1 flight, twice"), ("stair_climb", "main", "2 flights"))),
        seg("Heel raises", "block", 45, T(("heel_raise", "easier", "2 sets of 10, seated"), ("heel_raise", "main", "2 sets of 10"),
                                          ("heel_raise", "harder", "2 sets of 12, one hand"), ("heel_raise", "harder", "2 sets of 8 each leg"))),
        seg("Cyclic sighing", "cooldown", 35, same("cyclic_sigh", "35 seconds", "35 seconds", "35 seconds", "35 seconds", ("main",) * 4)),
        close(["New steps, same counter.", "Tai chi on Thursday."])]),
    "B2": dict(title="Tai chi: three forms", set="SET-YARD", wardrobe="C-TRAIN-B", segments=[
        intro("Balance · B2", ["Tai chi, phase two. Three forms today.", "Cloud hands, brush knee, and parting the horse's mane.", "Fence within reach."]),
        seg("Cyclic sighing", "warmup", 50, same("cyclic_sigh", "50 seconds", "50 seconds", "50 seconds", "50 seconds", ("main",) * 4)),
        seg("Cloud hands", "block", 90, same("cloud_hands", "90 seconds, seated", "90 seconds", "90 seconds with side steps", "2 minutes with side steps", ("easier", "main", "harder", "harder"))),
        seg("Brush knee", "block", 90, same("brush_knee", "4 each side, arms only", "6 each side", "4 steps across and back", "6 steps across and back", ("easier", "main", "harder", "harder"))),
        seg("Parting the horse's mane", "block", 100, same("parting_mane", "4 each side, arms only", "6 each side", "4 steps across and back", "6 steps across and back", ("easier", "main", "harder", "harder"))),
        seg("Drawing the bow", "block", 50, same("draw_bow", "3 each side, seated", "4 each side", "5 each side", "5 each side, lower stance", ("easier", "main", "main", "harder"))),
        seg("One-leg stand", "block", 60, T(("single_leg", "easier", "2 × 10 seconds each side, toe down"), ("single_leg", "main", "2 × 15 seconds each side"),
                                            ("single_leg", "harder", "2 × 20 seconds each side, hand hovering"), ("single_leg", "harder", "2 × 30 seconds each side, hands hovering"))),
        seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4)),
        close(["Three forms. Soft knees, slow weight shifts.", "Checkpoint at the end of week eight."])]),
    "A3": dict(title="Steady in real life", set="SET-KITCHEN", wardrobe="C-TRAIN-B", segments=[
        intro("Balance · A3", ["Phase three. Steady in real life.", "Floor practice, stepping, turning.", "Someone home for the floor part."]),
        seg("Weight shifts", "warmup", 40, same("weight_shift", "5 each way, seated", "6 each way", "8 each way", "8 each way, hand hovering", ("easier", "main", "harder", "harder"))),
        seg("Floor practice", "block", 90, T(("sit_to_stand", "easier", "1 set of 6 (no floor)"), ("floor_practice", "easier", "2 half-kneels each side"),
                                             ("floor_practice", "main", "2 kneel-and-rise"), ("floor_practice", "harder", "2 sit-to-floor and rise")),
            vo=["Sturdy chair beside you. Towel down. Someone else home.", "Kneel with your hands on the chair. Rise through the front foot.", "Breathe out as you push up. Stand still before you walk.",
                "Practise getting up before you ever need to."], ost=["Only with a sturdy chair and someone home"]),
        seg("Step over a towel", "block", 60, T(("seated_march", "harder", "12 high knee lifts, seated"), ("step_over", "harder", "8 forward and back"),
                                                ("step_over", "harder", "10 forward and back"), ("step_over", "harder", "12 forward and back"))),
        seg("Big-step drill", "block", 60, T(("seated_march", "harder", "30 seconds, big knee lifts"), ("big_steps", "easier", "2 × 10 steps along the counter"),
                                             ("big_steps", "main", "2 × 10 big steps"), ("big_steps", "harder", "2 × 20 big steps"))),
        seg("Heel-to-toe walk", "block", 60, T(("heel_toe_walk", "easier", "2 lengths, feet apart"), ("heel_toe_walk", "harder", "3 lengths, hand hovering"),
                                               ("heel_toe_walk", "harder", "4 lengths, hand hovering"), ("heel_toe_walk", "harder", "4 lengths, hand hovering + 2 backward, hand on counter"))),
        seg("One-leg stand + reach", "block", 70, T(("single_leg", "easier", "3 × 15 seconds each side, toe down"), ("clock_reach", "main", "4 each direction"),
                                                    ("clock_reach", "harder", "4 reaches on one foot each side"), ("clock_reach", "harder", "6 reaches on one foot each side"))),
        seg("Sit-to-stand, no hands", "block", 45, T(("sit_to_stand", "easier", "2 sets of 5"), ("sit_stand_nohands", "harder", "2 sets of 6, feet together"),
                                                     ("sit_stand_nohands", "harder", "2 sets of 8, feet together"), ("sit_stand_nohands", "harder", "3 sets of 8, feet together"))),
        seg("Cyclic sighing", "cooldown", 35, same("cyclic_sigh", "35 seconds", "35 seconds", "35 seconds", "35 seconds", ("main",) * 4)),
        close(["Floor, steps, turns. Real life.", "Tai chi Thursday."])]),
    "B3": dict(title="Tai chi: the full flow", set="SET-PROM", wardrobe="C-TRAIN-B", segments=[
        intro("Balance · B3", ["Phase three. The full flow, three rounds.", "Rail within reach.", "Slow like honey."]),
        seg("Cyclic sighing", "warmup", 50, same("cyclic_sigh", "50 seconds", "50 seconds", "50 seconds", "50 seconds", ("main",) * 4)),
        seg("Flow round 1: cloud hands", "block", 80, same("cloud_hands", "80 seconds, seated", "80 seconds", "80 seconds with side steps", "80 seconds with side steps", ("easier", "main", "harder", "harder"))),
        seg("Flow round 1: brush knee", "block", 80, same("brush_knee", "4 each side, arms only", "6 each side", "4 steps across and back", "6 steps across and back", ("easier", "main", "harder", "harder"))),
        seg("Flow round 1: parting the mane", "block", 80, same("parting_mane", "4 each side, arms only", "6 each side", "4 steps across and back", "6 steps across and back", ("easier", "main", "harder", "harder"))),
        seg("Flow round 2: all three", "block", 150, same("cloud_hands", "Cloud hands, brush knee, parting the mane: arms only, seated", "All three forms, 2 each", "All three forms with steps", "All three forms with steps, slower", ("easier", "main", "harder", "harder")),
            vo=["Near the rail. Now all three, one after another.", "Cloud hands. Brush knee. Parting the mane.", "Breathe slowly. Soft knees. Weight moves first, then the hands."]),
        seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4)),
        close(["Twelve weeks. That's a flow you can keep for as long as you like.", "Final checkpoint this weekend."])]),
    })

# =================================================================== GRIP & HANDS
program(id="GRP", name="Grip & Hands",
    promise="Hand mobility, grip and forearm strength for jars, bags, doors and hobbies.",
    who="Adults 60+ who want stronger, more capable hands, including people with everyday hand stiffness. It trains the hands you have; it doesn't change arthritis itself.",
    ask_first="A hot, red, swollen finger joint; new numbness or tingling that's getting worse; hand or wrist surgery or a fracture in the last few months: ask your doctor or hand therapist first.",
    equipment="A hand towel, a soft ball or rolled sock, thick rubber bands, a paperback, water bottles, a jar with a lid, grocery bags. Optional: an inexpensive hand-grip dynamometer.",
    evidence=["E01", "E06", "E07", "E41", "E59"],
    week_days={"Mon": "Strength", "Tue": "A", "Wed": "Balance", "Thu": "Strength", "Fri": "B", "Sat": "Walk-and-talk", "Sun": "Rest + stretch"},
    checkpoints=[("Jar test", "Opening a new, sealed jar: easily / with effort / need a tool / no", "self-rating"),
                 ("Book pinch hold", "Seconds holding a paperback by the spine, up to 30, each hand", "E07"),
                 ("Two-bag carry", "Seconds carrying two bags or jugs, up to 60", "E07"),
                 ("30-second arm curl", "Full curls, same weight each time", "E49"),
                 ("Hand stiffness", "Finger stiffness 0–10 on waking; hand pain 0–10 after the session (pain rule)", "E59, E41"),
                 ("Grip (optional)", "Dynamometer, best of 2, each hand. Under 27 kg (men) or 16 kg (women) is a screening sign worth mentioning to your doctor", "E06")],
    sessions={
    "A1": dict(title="Hands awake", set="SET-TABLE", wardrobe="C-CASUAL", segments=[
        intro("Grip & Hands · A1", ["Grip and Hands. Phase one: wake the hands up.", "Hand exercise may help a little with stiffness and hand use. Small, honest effects in the research.",
                                    "Hand pain rule: mild ache up to three out of ten that settles by tomorrow is okay. A hot, swollen joint is for your doctor."], extra=["Study: 7 trials, 534 people"]),
        seg("Shoulder rolls", "warmup", 30, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls", "8 rolls + circles", ("main", "main", "main", "harder"))),
        seg("Prayer and wrist stretch", "warmup", 40, same("hand_stretch", "10 seconds, twice", "20 seconds, twice", "20 seconds, twice", "20 seconds, twice", ("easier", "main", "main", "main"))),
        seg("Fist, flat, hook", "block", 70, same("fist_flat", "5 rounds each hand, small", "8 rounds each hand", "10 rounds each hand", "10 rounds, 3-second holds", ("easier", "main", "main", "harder"))),
        seg("Thumb touches", "block", 60, same("thumb_touch", "2 rounds each hand, pads", "3 rounds each hand", "4 rounds each hand", "4 rounds, 2-second press", ("easier", "main", "main", "harder"))),
        seg("Finger spreads", "block", 60, same("finger_spread", "6 each hand, no band", "8 each hand", "10 each hand, band", "12 each hand, band", ("easier", "main", "harder", "harder"))),
        seg("Soft ball squeeze", "block", 60, same("ball_squeeze", "6 each hand, sock", "8 each hand", "10 each hand, 5-second squeeze", "12 each hand, firmer ball", ("easier", "main", "harder", "harder"))),
        seg("Wrist curls", "block", 70, same("wrist_curl", "8 up + 8 down each hand, no weight", "10 up + 10 down, bottle", "12 up + 12 down, bottle", "12 up + 12 down, half-gallon jug", ("easier", "main", "main", "harder"))),
        seg("Jar lid practice", "block", 60, same("jar_twist", "5 each hand, loose lid", "6 each hand", "8 each hand", "8 each hand, rubber band on lid", ("easier", "main", "main", "harder"))),
        seg("Towel wring", "block", 50, same("towel_wring", "2 each way, gentle", "3 each way", "3 each way", "4 each way, damp towel", ("easier", "main", "main", "harder"))),
        seg("Cyclic sighing", "cooldown", 40, same("cyclic_sigh", "40 seconds", "40 seconds", "40 seconds", "40 seconds", ("main",) * 4)),
        close(["Hands are tools. We sharpen them a little every week.", "Friday: grip and carry."])]),
    "B1": dict(title="Grip and carry", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Grip & Hands · B1", ["Grip and carry.", "In 142,861 adults in 17 countries, lower grip strength was linked with higher death rates. A link, not a cause. Grip is how you live.",
                                    "Flaring joints today? Gentle versions only."], extra=["Study: 142,861 adults, 17 countries"]),
        seg("Prayer and wrist stretch", "warmup", 35, same("hand_stretch", "10 seconds, twice", "20 seconds, twice", "20 seconds, twice", "20 seconds, twice", ("easier", "main", "main", "main"))),
        seg("Fist, flat, hook", "warmup", 45, same("fist_flat", "5 rounds each hand", "6 rounds each hand", "8 rounds each hand", "8 rounds each hand", ("easier", "main", "main", "main"))),
        seg("Towel wring", "block", 60, same("towel_wring", "3 each way, gentle", "3 each way", "4 each way", "4 each way, damp towel", ("easier", "main", "main", "harder"))),
        seg("Book pinch hold", "block", 70, same("book_pinch", "2 × 5 seconds each hand, thin book", "2 × 10 seconds each hand", "3 × 15 seconds each hand", "3 × 20 seconds each hand, thick book", ("easier", "main", "main", "harder"))),
        seg("Curls", "block", 60, same("bottle_curl", "2 sets of 8, bottles", "2 sets of 10, bottles", "2 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", ("main", "main", "harder", "harder"))),
        seg("Row", "block", 70, T(("towel_row", "main", "4 pulls, 3-second squeeze"), ("jug_row", "main", "2 sets of 10 each arm"),
                                  ("band_row", "main", "3 sets of 10"), ("jug_row", "harder", "3 sets of 12 each arm, heavy bag"))),
        seg("Two-hand carry", "block", 75, T(("towel_wring", "easier", "3 gentle wrings each way, seated"), ("carry", "easier", "2 × 20 seconds, one light bag"),
                                             ("carry", "main", "2 × 30 seconds"), ("carry", "harder", "3 × 45 seconds, heavy"))),
        seg("Soft ball squeeze", "cooldown", 40, same("ball_squeeze", "6 each hand, gentle", "8 each hand", "8 each hand", "10 each hand", ("easier", "main", "main", "main"))),
        seg("Cyclic sighing", "cooldown", 35, same("cyclic_sigh", "35 seconds", "35 seconds", "35 seconds", "35 seconds", ("main",) * 4)),
        close(["Carry your groceries in two bags this week.", "Tuesday: hands again."])]),
    "A2": dict(title="Hands stronger", set="SET-TABLE", wardrobe="C-CASUAL", segments=[
        intro("Grip & Hands · A2", ["Phase two. Hands stronger.", "Bands on the fingers, heavier bottles, tighter lids.", "Pain rule still applies."]),
        seg("Prayer and wrist stretch", "warmup", 40, same("hand_stretch", "10 seconds, twice", "20 seconds, twice", "20 seconds, twice", "20 seconds, twice", ("easier", "main", "main", "main"))),
        seg("Fist, flat, hook", "warmup", 50, same("fist_flat", "6 rounds each hand", "8 rounds each hand", "10 rounds, 3-second holds", "10 rounds, 3-second holds", ("easier", "main", "harder", "harder"))),
        seg("Finger spreads", "block", 60, same("finger_spread", "8 each hand, no band", "10 each hand, band", "12 each hand, band", "12 each hand, two bands", ("easier", "harder", "harder", "harder"))),
        seg("Thumb touches", "block", 50, same("thumb_touch", "3 rounds, pads", "4 rounds", "4 rounds, 2-second press", "5 rounds, 2-second press", ("easier", "main", "harder", "harder"))),
        seg("Wrist curls", "block", 70, same("wrist_curl", "10 up + 10 down, bottle", "12 up + 12 down, bottle", "12 up + 12 down, half-gallon jug", "2 × 12 up + 12 down, half-gallon jug", ("main", "main", "harder", "harder"))),
        seg("Soft ball squeeze", "block", 60, same("ball_squeeze", "8 each hand", "10 each hand, 5-second squeeze", "12 each hand, firmer ball", "12 each hand, firmer ball, 5 s", ("easier", "harder", "harder", "harder"))),
        seg("Jar lid practice", "block", 60, same("jar_twist", "6 each hand", "8 each hand, rubber band", "10 each hand, tighter", "10 each hand, tighter", ("easier", "harder", "harder", "harder"))),
        seg("Book pinch hold", "block", 60, same("book_pinch", "2 × 8 seconds each hand", "3 × 12 seconds each hand", "3 × 20 seconds each hand", "3 × 20 seconds, thick book", ("easier", "main", "harder", "harder"))),
        seg("Cyclic sighing", "cooldown", 40, same("cyclic_sigh", "40 seconds", "40 seconds", "40 seconds", "40 seconds", ("main",) * 4)),
        close(["Try a real jar this week. Tell me.", "Friday: grip and carry."])]),
    "B2": dict(title="Heavier carries", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Grip & Hands · B2", ["Phase two. Heavier carries.", "Pick up with a hinge. Always.", "Clear path."]),
        seg("Fist, flat, hook", "warmup", 45, same("fist_flat", "5 rounds each hand", "6 rounds each hand", "8 rounds each hand", "8 rounds each hand", ("easier", "main", "main", "main"))),
        seg("Shoulder rolls", "warmup", 30, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls + circles", "8 rolls + circles", ("main", "main", "harder", "harder"))),
        seg("Towel wring", "block", 55, same("towel_wring", "3 each way", "4 each way", "4 each way, damp", "5 each way, damp", ("main", "main", "harder", "harder"))),
        seg("One-side carry", "block", 75, T(("towel_wring", "easier", "3 gentle wrings, seated"), ("suitcase_carry", "easier", "2 × 20 seconds each side"),
                                             ("suitcase_carry", "main", "2 × 30 seconds each side"), ("suitcase_carry", "harder", "3 × 40 seconds each side"))),
        seg("Two-hand carry", "block", 75, T(("ball_squeeze", "main", "10 each hand"), ("carry", "main", "2 × 30 seconds"),
                                             ("carry", "harder", "3 × 40 seconds"), ("carry", "harder", "3 × 60 seconds, heavy"))),
        seg("Row", "block", 70, T(("band_row", "easier", "2 sets of 10, close to the door"), ("band_row", "main", "3 sets of 10"),
                                  ("band_row", "harder", "3 sets of 12, pause"), ("jug_row", "harder", "3 sets of 12 each arm, heavy bag"))),
        seg("Curls", "block", 55, same("bottle_curl", "2 sets of 10, bottles", "2 sets of 10, half-gallon jug", "3 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", ("main", "harder", "harder", "harder"))),
        seg("Prayer and wrist stretch", "cooldown", 40, same("hand_stretch", "10 seconds, twice", "20 seconds, twice", "20 seconds, twice", "20 seconds, twice", ("easier", "main", "main", "main"))),
        seg("Cyclic sighing", "cooldown", 35, same("cyclic_sigh", "35 seconds", "35 seconds", "35 seconds", "35 seconds", ("main",) * 4)),
        close(["Strong hands carry the groceries in one trip. Carefully.", "Checkpoint at the end of week eight."])]),
    "A3": dict(title="Hands for hobbies", set="SET-TABLE", wardrobe="C-CASUAL", segments=[
        intro("Grip & Hands · A3", ["Phase three. Hands for your hobbies: gardening, knitting, cards, tools.", "Control and endurance.", "Pain rule applies."]),
        seg("Prayer and wrist stretch", "warmup", 40, same("hand_stretch", "10 seconds, twice", "20 seconds, twice", "20 seconds, twice", "20 seconds, twice", ("easier", "main", "main", "main"))),
        seg("Thumb touches", "block", 55, same("thumb_touch", "3 rounds, pads", "5 rounds", "5 rounds, 2-second press", "6 rounds, 2-second press", ("easier", "main", "harder", "harder"))),
        seg("Finger spreads", "block", 55, same("finger_spread", "10 each hand, no band", "12 each hand, band", "12 each hand, two bands", "12 each hand, two bands, 3 s", ("easier", "harder", "harder", "harder"))),
        seg("Fist, flat, hook", "block", 55, same("fist_flat", "8 rounds", "10 rounds, 3-second holds", "12 rounds, 3-second holds", "12 rounds, 3-second holds", ("main", "harder", "harder", "harder"))),
        seg("Wrist curls", "block", 70, same("wrist_curl", "12 up + 12 down, bottle", "2 × 12 each way, bottle", "2 × 12 each way, half-gallon jug", "3 × 12 each way, half-gallon jug", ("main", "main", "harder", "harder"))),
        seg("Book pinch hold", "block", 60, same("book_pinch", "3 × 10 seconds each hand", "3 × 15 seconds each hand", "3 × 20 seconds, thick book", "3 × 30 seconds, thick book", ("easier", "main", "harder", "harder"))),
        seg("Soft ball squeeze", "block", 55, same("ball_squeeze", "10 each hand", "12 each hand, 5 s", "12 each hand, firmer ball, 5 s", "2 × 12 each hand, firmer ball", ("main", "harder", "harder", "harder"))),
        seg("Jar lid practice", "block", 55, same("jar_twist", "8 each hand", "10 each hand, tighter", "10 each hand, tightest", "12 each hand, tightest", ("main", "harder", "harder", "harder"))),
        seg("Cyclic sighing", "cooldown", 40, same("cyclic_sigh", "40 seconds", "40 seconds", "40 seconds", "40 seconds", ("main",) * 4)),
        close(["Hands that open jars are hands that stay independent.", "Friday: the last carry session."])]),
    "B3": dict(title="Strong grip", set="SET-GARAGE", wardrobe="C-TRAIN-A", segments=[
        intro("Grip & Hands · B3", ["Phase three. Strong grip.", "Longest carries, heaviest curls you can do with good form.", "Hinge to pick up."]),
        seg("Fist, flat, hook", "warmup", 45, same("fist_flat", "6 rounds each hand", "8 rounds each hand", "8 rounds each hand", "8 rounds each hand", ("easier", "main", "main", "main"))),
        seg("Towel wring", "warmup", 40, same("towel_wring", "3 each way", "4 each way", "4 each way, damp", "5 each way, damp", ("main", "main", "harder", "harder"))),
        seg("Two-hand carry", "block", 90, T(("ball_squeeze", "harder", "12 each hand, 5-second squeeze"), ("carry", "harder", "3 × 30 seconds, heavier"),
                                             ("carry", "harder", "3 × 45 seconds, heavy"), ("carry", "harder", "3 × 60 seconds, heavy"))),
        seg("One-side carry", "block", 80, T(("towel_wring", "main", "4 wrings each way"), ("suitcase_carry", "main", "2 × 30 seconds each side"),
                                             ("suitcase_carry", "harder", "3 × 40 seconds each side"), ("suitcase_carry", "harder", "3 × 60 seconds each side, heavy"))),
        seg("Book pinch hold", "block", 60, same("book_pinch", "3 × 10 seconds", "3 × 15 seconds", "3 × 20 seconds, thick book", "3 × 30 seconds, thick book", ("easier", "main", "harder", "harder"))),
        seg("Curls", "block", 55, same("bottle_curl", "2 sets of 10, half-gallon jug", "3 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", "3 sets of 12, gallon jug", ("harder",) * 4)),
        seg("Row", "block", 65, T(("band_row", "main", "3 sets of 10"), ("band_row", "harder", "3 sets of 12, pause"),
                                  ("jug_row", "harder", "3 sets of 12 each arm, heavy bag"), ("jug_row", "harder", "3 sets of 12 each arm, heavier bag"))),
        seg("Prayer and wrist stretch", "cooldown", 40, same("hand_stretch", "10 seconds, twice", "20 seconds, twice", "20 seconds, twice", "20 seconds, twice", ("easier", "main", "main", "main"))),
        close(["Twelve weeks of grip. Test a real jar this weekend.", "Final checkpoint this weekend."])]),
    })

# =================================================================== WALK STRONGER
program(id="WLK", name="Walk Stronger",
    promise="Walk farther, a little faster and more confidently: walking technique, leg strength, stairs and gradual step goals.",
    who="Adults 60+ who walk (with or without a cane) and want to walk more. Walker users start at Rebuild with hallway lengths.",
    ask_first="Chest pain, pressure or unusual breathlessness when you walk; calf pain that comes on with walking and eases with rest; dizziness; or a recent fall: see your doctor first.",
    equipment="Walking shoes, a safe route (hallway, mall, sidewalk), stairs with a rail, a step counter or phone, a tape measure and timer for checkpoints.",
    evidence=["E10", "E13", "E22", "E23", "E49", "E51", "E43"],
    week_days={"Mon": "Strength", "Tue": "A", "Wed": "Balance", "Thu": "B", "Fri": "Breath + qigong", "Sat": "Walk-and-talk", "Sun": "Rest + stretch"},
    steps=["Baseline week: just count", "Baseline + 500/day", "Baseline + 500", "Baseline + 500 (easy week)", "Baseline + 1,000", "Baseline + 1,000", "Baseline + 1,500", "Baseline + 1,000 (easy week)",
           "Baseline + 2,000, up to 6,000–8,000", "Baseline + 2,000", "Baseline + 2,500", "Keep 6,000–8,000 if you're there"],
    checkpoints=[("Walking speed", "Time to walk 13 feet (4 m) at your usual pace, with a 3-foot run-up. Speed (m/s) = 4 ÷ seconds. About 5 s = 0.8 m/s; 4 s = 1.0 m/s", "E10"),
                 ("Timed Up and Go", "Seconds, normal pace, helper beside you. 12 s or more = tell your doctor", "E51"),
                 ("Two-minute step test", "Right-knee lifts to the tape mark in 2 minutes, holding the counter", "E49"),
                 ("Average daily steps", "Average of the last 7 days", "E22")],
    sessions={
    "A1": dict(title="Walk tall, legs strong", set="SET-STOOP", wardrobe="C-TRAIN-B", segments=[
        intro("Walk Stronger · A1", ["Walk Stronger. Phase one.", "Good walking is strong calves, strong hips, and a tall body.", "In 34,485 adults over 65, faster usual walking speed was linked with longer survival. A link, not a race."],
              extra=["Study: 34,485 adults 65+"]),
        seg("Ankle pumps and circles", "warmup", 40, same("ankle_pumps", "10 pumps + circles", "10 pumps + circles", "10 pumps + circles, foot lifted", "10 pumps + circles, foot lifted", ("main", "main", "harder", "harder"))),
        seg("Heel raises", "block", 60, T(("heel_raise", "easier", "2 sets of 12, seated"), ("heel_raise", "main", "2 sets of 10"),
                                          ("heel_raise", "harder", "2 sets of 12, one hand"), ("heel_raise", "harder", "2 sets of 10 each leg"))),
        seg("Toe and heel walks", "block", 60, T(("ankle_pumps", "main", "15 toe lifts + 15 heel lifts, seated"), ("toe_walk", "easier", "10 heel raises + 10 toe lifts at the counter"),
                                                 ("toe_walk", "main", "1 length toes + 1 length heels"), ("toe_walk", "main", "2 lengths each"))),
        seg("Step-ups", "block", 80, T(("seated_march", "harder", "2 × 30 seconds, knees high"), ("step_up", "easier", "2 sets of 10 toe taps"),
                                       ("step_up", "main", "2 sets of 8 each leg"), ("step_up", "harder", "3 sets of 8 each leg, bag"))),
        seg("Sit-to-stand", "block", 70, T(("sit_to_stand", "easier", "2 sets of 6"), ("sit_to_stand", "main", "2 sets of 10"),
                                           ("sit_to_stand", "harder", "3 sets of 10, 3-second lower"), ("power_stand", "harder", "3 sets of 6, jug"))),
        seg("Big-step drill", "block", 60, T(("seated_march", "harder", "30 seconds, big knee lifts"), ("big_steps", "easier", "2 × 10 steps along the counter"),
                                             ("big_steps", "main", "2 × 10 big steps"), ("big_steps", "harder", "2 × 20 big steps"))),
        seg("Walk", "block", 150, T(("seated_march", "main", "2 minutes 30, or walker lengths of the hallway"), ("walk", "easier", "2 minutes 30 easy"),
                                    ("walk", "main", "2 minutes 30, easy to brisk"), ("walk", "main", "2 minutes 30 brisk"))),
        seg("Standing hip-front stretch", "cooldown", 45, T(("hip_flexor", "easier", "20 seconds each side, both hands down"), ("hip_flexor", "main", "20 seconds each side"),
                                                            ("hip_flexor", "main", "20 seconds each side"), ("hip_flexor", "harder", "30 seconds each side"))),
        seg("Calf stretch", "cooldown", 40, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
        close(["Walk tall. Heel, roll, push.", "Thursday: intervals."])]),
    "B1": dict(title="Easy-brisk intervals", set="SET-PROM", wardrobe="C-TRAIN-B", segments=[
        intro("Walk Stronger · B1", ["Intervals. Easy, then a little brisk, then easy.", "Brisk means you can talk but you can't sing.", "Indoors counts."]),
        seg("Easy walk", "block", 120, T(("seated_march", "main", "2 minutes"), ("walk", "easier", "2 minutes easy"), ("walk", "easier", "2 minutes easy"), ("walk", "easier", "2 minutes easy"))),
        seg("Brisk", "block", 60, T(("seated_march", "harder", "1 minute faster"), ("walk", "main", "1 minute a little faster"), ("walk", "main", "1 minute brisk"), ("walk", "harder", "1 minute brisk"))),
        seg("Easy", "block", 60, T(("seated_march", "main", "1 minute easy"), ("walk", "easier", "1 minute easy"), ("walk", "easier", "1 minute easy"), ("walk", "easier", "1 minute easy"))),
        seg("Brisk", "block", 60, T(("seated_march", "harder", "1 minute faster"), ("walk", "main", "1 minute a little faster"), ("walk", "main", "1 minute brisk"), ("walk", "harder", "1 minute brisk"))),
        seg("Easy", "block", 60, T(("seated_march", "main", "1 minute easy"), ("walk", "easier", "1 minute easy"), ("walk", "easier", "1 minute easy"), ("walk", "easier", "1 minute easy"))),
        seg("Brisk", "block", 60, T(("seated_march", "harder", "1 minute faster"), ("walk", "main", "1 minute a little faster"), ("walk", "main", "1 minute brisk"), ("walk", "harder", "1 minute brisk"))),
        seg("Cool-down walk", "cooldown", 90, T(("seated_march", "easier", "90 seconds slow"), ("walk", "easier", "90 seconds slow"), ("walk", "easier", "90 seconds slow"), ("walk", "easier", "90 seconds slow"))),
        seg("Calf stretch at the rail", "cooldown", 40, same("calf_stretch", "20 seconds each leg, both hands on the rail", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
        close(["Log your steps. Aim for your number this week.", "Walk after your biggest meal too. Even a few minutes helps the blood-sugar rise after eating."])]),
    "A2": dict(title="Stairs and power", set="SET-STOOP", wardrobe="C-TRAIN-B", segments=[
        intro("Walk Stronger · A2", ["Phase two. Stairs and power.", "Rail hand never lets go.", "Shoes on."]),
        seg("Ankle pumps and circles", "warmup", 35, same("ankle_pumps", "10 pumps + circles", "10 pumps + circles", "10 pumps + circles", "10 pumps + circles", ("main",) * 4)),
        seg("March", "warmup", 40, T(("seated_march", "main", "40 seconds"), ("standing_march", "main", "40 seconds"), ("standing_march", "harder", "40 seconds"), ("standing_march", "harder", "40 seconds")),
            vo=["Hand on the counter. March.", "Breathe steady."]),
        seg("Stair practice", "block", 110, T(("seated_march", "harder", "3 × 30 seconds, knees high"), ("stair_climb", "easier", "Bottom 3 steps, 4 times"),
                                              ("stair_climb", "main", "1 flight, 3 times"), ("stair_climb", "harder", "2 flights, twice"))),
        seg("Power stands", "block", 90, T(("sit_to_stand", "easier", "3 sets of 5, normal speed"), ("power_stand", "main", "3 sets of 5"),
                                           ("power_stand", "harder", "3 sets of 6, jug"), ("power_stand", "harder", "3 sets of 8, jug (advanced)"))),
        seg("Heel raises", "block", 55, T(("heel_raise", "easier", "3 sets of 10, seated"), ("heel_raise", "harder", "2 sets of 12, one hand"),
                                          ("heel_raise", "harder", "2 sets of 8 each leg"), ("heel_raise", "harder", "3 sets of 10 each leg"))),
        seg("Big-step drill", "block", 60, T(("seated_march", "harder", "30 seconds, big knee lifts"), ("big_steps", "main", "2 × 10 big steps"),
                                             ("big_steps", "harder", "2 × 20 big steps"), ("big_steps", "harder", "3 × 20 big steps, faster"))),
        seg("Walk", "block", 150, T(("seated_march", "main", "2 minutes 30"), ("walk", "main", "2 minutes 30 steady"),
                                    ("walk", "main", "2 minutes 30 brisk"), ("walk", "harder", "2 minutes 30 brisk, hill"))),
        seg("Calf stretch", "cooldown", 40, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
        close(["Stairs are the best free gym you own.", "Thursday: longer intervals."])]),
    "B2": dict(title="Longer brisk", set="SET-PROM", wardrobe="C-TRAIN-B", segments=[
        intro("Walk Stronger · B2", ["Phase two. Longer brisk minutes.", "Can talk, can't sing.", "Stop for chest pain, pressure, or calf pain that comes on with walking."]),
        seg("Easy walk", "block", 120, T(("seated_march", "main", "2 minutes"), ("walk", "easier", "2 minutes easy"), ("walk", "easier", "2 minutes easy"), ("walk", "easier", "2 minutes easy"))),
        seg("Brisk", "block", 120, T(("seated_march", "harder", "1 minute faster, 1 easy"), ("walk", "main", "2 minutes a little faster"), ("walk", "main", "2 minutes brisk"), ("walk", "harder", "2 minutes brisk"))),
        seg("Easy", "block", 60, T(("seated_march", "main", "1 minute easy"), ("walk", "easier", "1 minute easy"), ("walk", "easier", "1 minute easy"), ("walk", "easier", "1 minute easy"))),
        seg("Brisk", "block", 120, T(("seated_march", "harder", "1 minute faster, 1 easy"), ("walk", "main", "2 minutes a little faster"), ("walk", "main", "2 minutes brisk"), ("walk", "harder", "2 minutes brisk, hill"))),
        seg("Cool-down walk", "cooldown", 90, T(("seated_march", "easier", "90 seconds slow"), ("walk", "easier", "90 seconds slow"), ("walk", "easier", "90 seconds slow"), ("walk", "easier", "90 seconds slow"))),
        seg("Calf stretch at the rail", "cooldown", 40, same("calf_stretch", "20 seconds each leg, both hands on the rail", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
        close(["In adults over 60, the benefit linked with daily steps levelled off around six to eight thousand a day.", "Not ten thousand. Six to eight. Log yours."],
              sun=["He counts steps to the fridge. They count, apparently."])]),
    "A3": dict(title="Walk anywhere", set="SET-STOOP", wardrobe="C-TRAIN-B", segments=[
        intro("Walk Stronger · A3", ["Phase three. Walk anywhere: stairs, curbs, uneven ground.", "Step practice, then a longer walk.", "Rail and counter for the drills."]),
        seg("Ankle pumps and circles", "warmup", 35, same("ankle_pumps", "10 pumps + circles", "10 pumps + circles", "10 pumps + circles", "10 pumps + circles", ("main",) * 4)),
        seg("Step over a towel", "block", 60, T(("seated_march", "harder", "12 high knee lifts, seated"), ("step_over", "main", "8 each way"),
                                                ("step_over", "harder", "8 forward and back"), ("step_over", "harder", "10 forward and back"))),
        seg("Step-ups", "block", 80, T(("seated_march", "harder", "3 × 30 seconds, knees high"), ("step_up", "main", "3 sets of 8 each leg"),
                                       ("step_up", "harder", "3 sets of 8 each leg, bag"), ("step_up", "harder", "3 sets of 10 each leg, heavier bag"))),
        seg("Stair practice", "block", 90, T(("seated_march", "harder", "2 × 30 seconds"), ("stair_climb", "main", "1 flight, 3 times"),
                                             ("stair_climb", "harder", "2 flights, twice"), ("stair_climb", "harder", "3 flights, bag in free hand"))),
        seg("Walk", "block", 240, T(("seated_march", "main", "4 minutes: 1 on, 30 seconds off"), ("walk", "main", "4 minutes steady"),
                                    ("walk", "main", "4 minutes brisk"), ("walk", "harder", "4 minutes brisk, hills"))),
        seg("Calf stretch", "cooldown", 40, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main"))),
        close(["Curbs, stairs, grass. You trained for all of them.", "Thursday: the long brisk session."])]),
    "B3": dict(title="The long brisk walk", set="SET-PROM", wardrobe="C-TRAIN-B", segments=[
        intro("Walk Stronger · B3", ["Phase three. The long brisk walk.", "Three brisk blocks. Easy between.", "Stop for chest pain, pressure, or calf pain that comes on with walking."]),
        seg("Easy walk", "block", 100, T(("seated_march", "main", "100 seconds"), ("walk", "easier", "100 seconds easy"), ("walk", "easier", "100 seconds easy"), ("walk", "easier", "100 seconds easy"))),
        seg("Brisk", "block", 120, T(("seated_march", "harder", "1 minute faster, 1 easy"), ("walk", "main", "2 minutes brisk-ish"), ("walk", "main", "2 minutes brisk"), ("walk", "harder", "2 minutes brisk, hill"))),
        seg("Easy", "block", 45, T(("seated_march", "main", "45 seconds easy"), ("walk", "easier", "45 seconds easy"), ("walk", "easier", "45 seconds easy"), ("walk", "easier", "45 seconds easy"))),
        seg("Brisk", "block", 120, T(("seated_march", "harder", "1 minute faster, 1 easy"), ("walk", "main", "2 minutes brisk-ish"), ("walk", "main", "2 minutes brisk"), ("walk", "harder", "2 minutes brisk"))),
        seg("Easy", "block", 45, T(("seated_march", "main", "45 seconds easy"), ("walk", "easier", "45 seconds easy"), ("walk", "easier", "45 seconds easy"), ("walk", "easier", "45 seconds easy"))),
        seg("Brisk", "block", 120, T(("seated_march", "harder", "1 minute faster, 1 easy"), ("walk", "main", "2 minutes brisk-ish"), ("walk", "main", "2 minutes brisk"), ("walk", "harder", "2 minutes brisk, hill"))),
        seg("Cool-down walk", "cooldown", 60, T(("seated_march", "easier", "1 minute slow"), ("walk", "easier", "1 minute slow"), ("walk", "easier", "1 minute slow"), ("walk", "easier", "1 minute slow"))),
        close(["Twelve weeks. Walk stronger. Keep walking.", "Final checkpoint this weekend: your walking speed."])]),
    })

# =================================================================== GUT RESET (food-led)
GUT_WEEKS = [
    dict(w=1, theme="Count what you eat now", habit="Write down one normal day of food and add up the fiber with the recipe numbers. No changes yet. Walk 5 minutes after your biggest meal.",
         recipes=["G21", "G06", "G11"], extra=["B4"], evidence=["E24", "E23"], rung="Baseline",
         lesson="Before you change anything, count. Most people have no idea how much fiber they eat. Grams, not vibes."),
    dict(w=2, theme="Two kiwis a day", habit="Two green kiwis every day (rung 1). Drink a glass of water with them.",
         recipes=["G01", "G02", "G22"], extra=["B4"], evidence=["E25", "E24"], rung="Rung 1: 2 kiwis",
         lesson="In a 4-week study of 75 people with chronic constipation, 2 kiwis a day worked about as well as prunes or psyllium, with the fewest side effects."),
    dict(w=3, theme="Whole grains", habit="Swap one bowl of white rice for mixed-grain or brown rice every day (rung 2).",
         recipes=["G10", "G12", "G24"], extra=["G01"], evidence=["E24"], rung="Rung 2: brown or mixed-grain rice",
         lesson="Barley, brown rice, beans in the rice cooker. Same bowl, more fiber."),
    dict(w=4, theme="Easy week + checkpoint", habit="Keep rungs 1–2. No new rung. Do the 3-day checkpoint.",
         recipes=["G08", "G16", "G19"], extra=["S4"], evidence=["E24", "E28"], rung="Hold", checkpoint=True,
         lesson="An easy week is part of the plan. Your gut adjusts. You count again."),
    dict(w=5, theme="Beans and soy", habit="Half a cup of edamame or soybeans a day (rung 3).",
         recipes=["G04", "G05", "G18"], extra=["N1"], evidence=["E24", "E28"], rung="Rung 3: 1/2 cup edamame",
         lesson="Soybeans give you protein and fiber in one spoon. Go slowly: beans are famous for a reason."),
    dict(w=6, theme="Fermented foods, small amounts", habit="One small serving of a fermented food a day: plain yogurt, kefir or a few bites of kimchi.",
         recipes=["G13", "G26", "S2"], extra=["G03"], evidence=["E26"], rung="Hold rungs 1–3",
         lesson="In a 10-week study of 36 adults, a high-fermented-food diet increased gut-microbe diversity and lowered 19 inflammation-related proteins. Small study. Interesting, not proven. Kimchi is salty: small portions."),
    dict(w=7, theme="Prunes and flax", habit="Five prunes and one tablespoon of ground flaxseed a day (rung 4).",
         recipes=["G09", "G15", "G23"], extra=["G21"], evidence=["E25", "E27"], rung="Rung 4: prunes + flax",
         lesson="In the Prune Study, postmenopausal women eating about 50 grams of prunes a day kept their hip bone density steady for a year compared with controls. And prunes help regularity (E25)."),
    dict(w=8, theme="Easy week + checkpoint", habit="Keep rungs 1–4. No new rung. Do the 3-day checkpoint.",
         recipes=["G20", "G03", "G19"], extra=["D2"], evidence=["E24"], rung="Hold", checkpoint=True,
         lesson="Halfway. Look at your numbers. Keep what works. Drop what doesn't."),
    dict(w=9, theme="A vegetable at every meal", habit="A vegetable at breakfast, lunch and dinner (rung 6). Oatmeal breakfast twice this week (rung 5).",
         recipes=["G14", "G17", "G25"], extra=["G03"], evidence=["E24"], rung="Rungs 5–6: oats + vegetables",
         lesson="Banchan are how Koreans eat vegetables without noticing. Make two on Sunday."),
    dict(w=10, theme="Protein at every meal", habit="25 to 30 grams of protein at each meal. Breakfast counts most. (Kidney disease: ask your doctor for your number.)",
         recipes=["G07", "G16", "L1"], extra=["B3"], evidence=["E28"], rung="Hold",
         lesson="Adults over 65: 1.0 to 1.2 grams of protein per kilogram a day, spread across meals, unless your doctor sets a different number."),
    dict(w=11, theme="Walk after meals, cook for one", habit="A 5 to 15 minute walk after your biggest meal every day. Freeze single portions.",
         recipes=["G08", "G22", "G21"], extra=["G10"], evidence=["E23"], rung="Hold",
         lesson="Light walking after meals, even 2 to 5 minutes, lowers the blood-sugar rise after eating compared with sitting."),
    dict(w=12, theme="Your keep list + final checkpoint", habit="Pick the 5 recipes and 3 habits you'll keep. Do the final 3-day checkpoint.",
         recipes=["G02", "G10", "G24"], extra=["G06"], evidence=["E24", "E28", "E23"], rung="Keep what works", checkpoint=True,
         lesson="Twelve weeks. You don't need all of it. You need what you'll actually keep."),
]

program(id="GUT", name="Gut Reset with Sun Yoon",
    promise="Twelve weeks of fiber, fermented foods and protein at every meal, climbed slowly, with 26 new recipes and weekly grocery lists.",
    who="Adults 60+ who want to eat more fiber and protein and feel more regular, cooking Korean and Chinese home food at home. Not a treatment for any bowel condition.",
    ask_first="Kidney disease (protein and potassium limits), a past bowel blockage, Crohn's disease or a narrowed bowel, trouble swallowing, a low-fiber diet ordered by your doctor, or warfarin (keep greens steady). Not for the ladder, for your doctor, today: blood in the stool, black stool, unexplained weight loss, severe belly pain, or a change in bowel habits lasting more than a few weeks.",
    equipment="A kitchen, a rice cooker or pot, a steamer basket, a kitchen scale (helpful), jars for banchan.",
    evidence=["E23", "E24", "E25", "E26", "E27", "E28", "E32", "E33", "E35", "E52", "E53", "E54", "E55", "E58"],
    checkpoints=[("Fiber grams", "Average of 3 days, using the recipe numbers and the fiber list. Goal zone: 25–29 g/day", "E24"),
                 ("Protein breakfasts", "Days last week with 25 g+ protein at breakfast (0–7)", "E28"),
                 ("After-meal walks", "Days last week with a walk after your biggest meal (0–7)", "E23"),
                 ("Regularity", "Bowel movements per week and how easy (easy / some effort / hard). A self-check, not a diagnosis", "self-rating"),
                 ("Fermented food servings", "Small servings last week", "E26")],
    weeks=GUT_WEEKS)
