"""Sun Yoon's Strong Kitchen: 24 recipes. Ingredient grams are the calculation basis (USDA FDC SR Legacy, E52).

Ingredient tuple: (amount shown to reader, ingredient text, grams used in the calculation, source)
source = USDA FDC ID (int) | "gochujang" | "chunjang" (label data, E53) | None (water, negligible spices)
"""

R = []


def recipe(**k):
    R.append(k)


# ============================================================== BREAKFAST
recipe(id="B1", cat="Breakfast", name="Chicken and ginger rice porridge", native="dak-juk (Korean) / jī zhōu (Chinese)",
       serves=4, active=15, total=55,
       intro="When someone in my house is tired, sick, or just old, I make this. Soft, warm, a lot of protein hiding in it. Chang eats three bowls and says he's 'testing it'.",
       ings=[("3/4 cup", "short-grain white rice (sushi rice), rinsed", 150, 168931),
             ("1 lb", "boneless, skinless chicken breast, whole", 454, 171077),
             ("4 cups", "low-sodium chicken broth", 960, 171609),
             ("4 cups", "water", 0, None),
             ("2-inch piece", "fresh ginger, peeled and thinly sliced", 22, 169231),
             ("4", "garlic cloves, smashed", 12, 169230),
             ("4", "large eggs, beaten", 200, 171287),
             ("3 cups (3 oz)", "baby spinach", 85, 168462),
             ("4", "scallions, thinly sliced", 60, 170005),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("2 tsp", "toasted sesame oil", 9, 171016),
             ("1/4 tsp", "salt", 1.5, 173468),
             ("pinch", "white or black pepper", 0, None)],
       steps=["Rinse the rice in a bowl of cold water, swishing with your hand, until the water is mostly clear. Drain.",
              "Put the broth, water, ginger, garlic and the whole chicken breast in a large pot. Bring to a boil, then turn down to a gentle simmer. Cover and cook 15 minutes, until the thickest part of the chicken reads 165°F.",
              "Lift the chicken onto a plate. Add the rice to the pot. Simmer uncovered, stirring every 5 minutes and scraping the bottom, for 35 to 40 minutes, until the grains break open and it looks creamy.",
              "While it cooks, shred the chicken with two forks.",
              "Stir the spinach into the porridge until it wilts, about 1 minute.",
              "Keep the pot at a gentle simmer. Pour in the beaten eggs in a thin stream while you stir slowly. Keep simmering 2 minutes, until the egg is fully cooked and firm.",
              "Stir the chicken back in. Season with the soy sauce and salt. Taste before adding more.",
              "Serve topped with scallions, a few drops of sesame oil and pepper. Fish out the ginger slices if you don't like biting them."],
       soft="Already soft. For a smoother texture, blend 1 minute with an immersion blender before adding the chicken, and chop the chicken finely.",
       store="Fridge up to 4 days. It thickens as it sits: add water when you reheat, and reheat to 165°F (steaming hot all the way through).",
       tags=["leafy_greens", "eggs"])

recipe(id="B2", cat="Breakfast", name="Steamed egg custard with soft tofu", native="gyeran-jjim (Korean)",
       serves=2, active=8, total=20,
       intro="Soft enough for new dentures. Strong enough for Chang. Don't walk away from the pot. Eggs punish people who walk away.",
       ings=[("5", "large eggs", 250, 171287),
             ("1/2 block (7 oz)", "soft tofu, drained and cut into small cubes", 198, 172449),
             ("3/4 cup", "low-sodium chicken broth", 180, 171609),
             ("2", "scallions, finely chopped", 30, 170005),
             ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1/2 tsp", "toasted sesame oil", 2.3, 171016),
             ("1 tsp", "toasted sesame seeds", 3, 170151),
             ("1 cup", "cooked brown rice, to serve (1/2 cup each)", 195, 169704)],
       steps=["Whisk the eggs, broth and soy sauce in a bowl until smooth, about 30 seconds.",
              "Put the tofu cubes in a small heatproof bowl or a small pot (2 to 3 cups). Pour the egg mixture over the tofu. Stir in most of the scallions.",
              "Set the bowl on a folded towel in a larger pot with 1 inch of simmering water (or cook the small pot directly over low heat). Cover.",
              "Steam on low for 12 to 15 minutes, until the center no longer jiggles like liquid and a knife comes out clean. The custard should be fully set, not runny.",
              "Top with the rest of the scallions, sesame oil and sesame seeds. Serve with rice."],
       soft="Already soft. Skip the rice, or cook it softer with extra water.",
       store="Best eaten right away. Leftovers keep 2 days in the fridge; reheat until steaming.",
       tags=["eggs"])

recipe(id="B3", cat="Breakfast", name="Savory oatmeal with egg, edamame and kimchi", native="Sun's oat juk",
       serves=1, active=5, total=10,
       intro="Oatmeal does not have to be sweet. Sweet is for dessert. This one has 28 grams of protein and tastes like lunch at my counter.",
       ings=[("1/2 cup", "old-fashioned rolled oats", 40, 173904),
             ("1 cup", "unsweetened soy milk", 243, 175215),
             ("1/2 cup", "water", 0, None),
             ("1/2 cup", "frozen shelled edamame", 78, 168410),
             ("1", "large egg, beaten", 50, 171287),
             ("1/4 cup", "kimchi, chopped", 38, 170392),
             ("1", "scallion, sliced", 15, 170005),
             ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1/2 tsp", "toasted sesame oil", 2.3, 171016),
             ("1 tsp", "toasted sesame seeds", 3, 170151)],
       steps=["Put the oats, soy milk, water and edamame in a small pot. Bring to a simmer over medium heat, stirring.",
              "Cook 4 to 5 minutes, stirring often, until thick.",
              "Stir in the beaten egg and keep stirring over low heat for 1 to 2 minutes, until no runny egg is left.",
              "Stir in the soy sauce. Top with kimchi, scallion, sesame oil and sesame seeds."],
       soft="Cook the oats 2 minutes longer with a splash more water. Use quick oats. Chop the kimchi very finely, or leave it out.",
       store="Best fresh. Cooked oats keep 3 days; reheat with a splash of water until steaming.",
       tags=["kimchi", "fiber", "eggs"])

recipe(id="B4", cat="Breakfast", name="Morning yogurt bowl with kiwi and walnuts", native="Sun's fridge breakfast",
       serves=1, active=5, total=5,
       intro="Two kiwis a day did as well as prunes for constipation in a small study, with fewer side effects. So I put them in breakfast, where you can't forget them.",
       ings=[("1 cup (8 oz)", "plain nonfat Greek yogurt", 227, 170894),
             ("2", "green kiwis, peeled and sliced", 150, 168153),
             ("2 Tbsp", "chopped walnuts", 14, 170187),
             ("1 Tbsp", "ground flaxseed", 7, 169414),
             ("1 tsp (optional)", "honey", 7, 169640)],
       steps=["Spoon the yogurt into a bowl.",
              "Top with kiwi slices, walnuts and flaxseed.",
              "Drizzle with honey if you want it. You don't need it. The kiwi is sweet."],
       soft="Use seedless fruit if kiwi seeds bother your dentures: a ripe persimmon or a banana. Swap the walnuts for 1 Tbsp smooth peanut butter stirred in.",
       store="Assemble fresh. Ground flaxseed keeps best in the fridge.",
       tags=["honey", "fiber", "kiwi"])

recipe(id="B5", cat="Breakfast", name="Tomato and egg on toast", native="fānqié chǎo dàn (Chinese)",
       serves=2, active=12, total=15,
       intro="Every Chinese kitchen has this. Chang makes it when it's his turn. It's the one thing I give an eight. Don't tell him.",
       ings=[("5", "large eggs", 250, 171287),
             ("3 medium", "ripe tomatoes, cut into wedges", 369, 170457),
             ("2", "scallions, sliced", 30, 170005),
             ("1 tsp", "sugar", 4.2, 169655),
             ("1/4 tsp", "salt", 1.5, 173468),
             ("1 Tbsp", "canola oil", 14, 172336),
             ("4 slices", "whole-wheat bread, toasted", 128, 172688)],
       steps=["Beat the eggs with a pinch of the salt.",
              "Heat half the oil in a nonstick pan over medium heat. Add the eggs and stir gently until just set in soft, fully cooked curds, about 2 minutes. Slide onto a plate.",
              "Add the rest of the oil and the tomatoes. Cook, stirring, 3 to 4 minutes, until juicy and soft. Add the sugar and remaining salt.",
              "Return the eggs to the pan. Stir together 1 minute until the eggs are hot and firm.",
              "Top with scallions. Spoon over the toast."],
       soft="Skip the toast crust, or serve over soft rice. Peel the tomatoes if the skins bother you.",
       store="Best fresh. Keeps 1 day in the fridge; reheat until steaming.",
       tags=["eggs", "fiber"])

# ============================================================== LUNCH
recipe(id="L1", cat="Lunch", name="Turkey bibimbap bowl", native="bibimbap (Korean)",
       serves=4, active=30, total=35,
       intro="Bibimbap means mixed rice. It's how Korean mothers use up vegetables. I use turkey because it's cheap and Chang can't tell.",
       ings=[("1 lb", "ground turkey", 454, 171505),
             ("3 cups", "cooked brown rice", 585, 169704),
             ("10 oz", "fresh spinach", 284, 168462),
             ("3 cups", "mung bean sprouts (always cooked, below)", 312, 169957),
             ("2 medium", "carrots, cut in thin matchsticks", 122, 170393),
             ("1 medium", "zucchini, cut in thin matchsticks", 196, 169291),
             ("4", "large eggs", 200, 171287),
             ("4", "garlic cloves, minced", 12, 169230),
             ("2 Tbsp", "low-sodium soy sauce (divided)", 32, 172473),
             ("1 Tbsp", "toasted sesame oil (divided)", 13.6, 171016),
             ("1 Tbsp", "canola oil (divided)", 14, 172336),
             ("1 Tbsp", "toasted sesame seeds", 9, 170151),
             ("2 Tbsp", "gochujang (Korean chili paste), for the sauce", 38, "gochujang"),
             ("1 tsp", "honey, for the sauce", 7, 169640),
             ("1 Tbsp", "rice or white vinegar, for the sauce", 15, 172237)],
       steps=["Sauce: stir the gochujang, honey, vinegar and 1 Tbsp water together. Set aside.",
              "Bring a large pot of water to a boil. Add the bean sprouts and cook 3 minutes. Lift them out with a slotted spoon, drain, and toss with 1 tsp sesame oil and a pinch of the garlic. Sprouts are always cooked in this house.",
              "Add the spinach to the same boiling water for 30 seconds. Drain, rinse with cold water, squeeze dry, chop, and toss with 1 tsp soy sauce, 1 tsp sesame oil and a little garlic.",
              "Heat 1 tsp canola oil in a large skillet. Stir-fry the carrots 2 minutes, then the zucchini 2 minutes, with a pinch of salt if you like. Set aside.",
              "In the same skillet, cook the turkey with the rest of the garlic and soy sauce, breaking it up, 6 to 8 minutes, until no pink remains and it reads 165°F.",
              "Fry the eggs in the remaining oil until the whites and yolks are firm, about 4 minutes. Cover the pan for the last minute so the tops set.",
              "Build each bowl: 3/4 cup rice, a quarter of the turkey and each vegetable in little piles, an egg on top. Sprinkle with sesame seeds and the last sesame oil. Mix in sauce to taste at the table."],
       soft="Chop all the vegetables finely and cook them 1 to 2 minutes longer. Use softer white rice cooked with extra water.",
       store="Components keep 3 days in the fridge in separate containers. Cook eggs fresh. Reheat turkey and rice to 165°F.",
       tags=["leafy_greens", "high_protein", "fiber", "honey", "eggs"])

recipe(id="L2", cat="Lunch", name="Kimchi fried rice with tofu and egg", native="kimchi-bokkeumbap (Korean)",
       serves=2, active=15, total=20,
       intro="Old kimchi plus old rice equals the best lunch in Korea. Nothing wasted. Tofu makes it a real meal, not a snack pretending.",
       ings=[("2 cups", "cooked brown rice, ideally a day old and cold", 390, 169704),
             ("1 cup", "well-fermented kimchi, chopped", 150, 170392),
             ("1/2 block (7 oz)", "extra-firm tofu, patted dry, in 1/2-inch cubes", 198, 174290),
             ("2", "large eggs", 100, 171287),
             ("1 cup", "frozen peas", 134, 170016),
             ("2", "scallions, sliced", 30, 170005),
             ("1 Tbsp (optional)", "gochujang", 19, "gochujang"),
             ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1 Tbsp", "canola oil", 14, 172336),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("1 sheet", "roasted seaweed (gim or nori), crumbled", 2.5, 168458)],
       steps=["Heat the canola oil in a large nonstick skillet over medium-high heat. Add the tofu and cook, turning, until golden on a few sides, 5 to 6 minutes.",
              "Add the kimchi and cook 3 minutes, until it smells toasty.",
              "Add the rice, peas, gochujang (if using) and soy sauce. Stir and press the rice into the pan. Cook 4 to 5 minutes, stirring every minute, until hot all the way through (165°F).",
              "Push the rice to one side. Fry the eggs in the empty space until the whites and yolks are firm.",
              "Drizzle with sesame oil. Serve with an egg on each plate, scallions and seaweed on top."],
       soft="Use soft tofu instead of extra-firm (add it at the end so it holds together), chop the kimchi finely, and use white rice.",
       store="Keeps 3 days in the fridge. Reheat until steaming. Cook the eggs fresh.",
       tags=["kimchi", "fiber", "eggs"])

recipe(id="L3", cat="Lunch", name="Cold sesame noodles with chicken and cucumber", native="liáng miàn (Chinese)",
       serves=2, active=20, total=25,
       intro="For hot days when nobody wants the stove on long. The sauce is sesame, not peanut. If you want peanut, use peanut. I'm not the police.",
       ings=[("4 oz dry (about 2 cups cooked)", "whole-wheat spaghetti", 280, 168910),
             ("8 oz", "boneless, skinless chicken breast", 227, 171077),
             ("1/2 cup", "frozen shelled edamame", 78, 168410),
             ("1 medium", "cucumber, cut in matchsticks", 200, 168409),
             ("1 medium", "carrot, shredded", 61, 170393),
             ("2 Tbsp", "tahini (or Chinese sesame paste)", 30, 170189),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1 Tbsp", "rice or white vinegar", 15, 172237),
             ("1 tsp", "honey", 7, 169640),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("1", "garlic clove, grated", 3, 169230),
             ("1 tsp", "toasted sesame seeds", 3, 170151)],
       steps=["Put the chicken in a small pot, cover with water by an inch, bring to a boil, then turn to the lowest simmer. Cover and cook 12 to 15 minutes, until it reads 165°F in the thickest part. Cool 5 minutes and shred.",
              "Cook the spaghetti in plenty of boiling water according to the package, adding the edamame for the last 3 minutes. Drain and rinse under cold water until cool.",
              "Sauce: whisk the tahini, soy sauce, vinegar, honey, sesame oil, garlic and 2 to 3 Tbsp warm water until smooth and pourable.",
              "Toss the noodles and edamame with the sauce. Top with chicken, cucumber, carrot and sesame seeds."],
       soft="Cook the noodles 2 minutes past the package time and cut them shorter. Peel and seed the cucumber, or skip it and use cooked, cooled zucchini.",
       store="Keeps 2 days in the fridge, sauce separate. Eat cold, straight from the fridge; don't leave it out more than 2 hours.",
       tags=["high_protein", "fiber", "honey"])

recipe(id="L4", cat="Lunch", name="Tuna mayo rice bowl", native="chamchi-mayo deopbap (Korean)",
       serves=1, active=8, total=10,
       intro="Korean students live on this. So do grandmothers who don't want to cook for one. Ten minutes. Thirty-six grams of protein. No excuses.",
       ings=[("1 can (5 oz)", "light tuna in water, drained", 113, 173709),
             ("1 Tbsp", "reduced-fat mayonnaise", 15, 171443),
             ("3/4 cup", "cooked brown rice, warm", 146, 169704),
             ("1/2 cup", "frozen shelled edamame, thawed in hot water", 78, 168410),
             ("1/2 cup", "diced cucumber", 52, 168409),
             ("1", "scallion, sliced", 15, 170005),
             ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1/2 tsp", "toasted sesame oil", 2.3, 171016),
             ("1 sheet", "roasted seaweed, cut in strips", 2.5, 168458)],
       steps=["Mix the tuna and mayonnaise with a fork.",
              "Put the warm rice in a bowl. Drizzle with the soy sauce and sesame oil.",
              "Top with the tuna, edamame, cucumber and scallion.",
              "Scatter the seaweed over just before eating so it stays crisp. Wrap bites of rice and tuna in the seaweed with your chopsticks."],
       soft="Use soft white rice and skip the cucumber. Mash the edamame lightly with a fork.",
       store="Mixed tuna keeps 2 days in the fridge. Assemble fresh.",
       tags=["high_protein", "fiber"])

recipe(id="L5", cat="Lunch", name="Chicken lettuce wraps with ssamjang", native="dak ssam (Korean)",
       serves=2, active=20, total=25,
       intro="You eat with your hands. The lettuce is the plate. Chang wraps too much in one leaf and it falls apart every time. Forty years. Same leaf.",
       ings=[("12 oz", "boneless, skinless chicken thighs", 340, 173627),
             ("1 Tbsp", "low-sodium soy sauce (marinade)", 16, 172473),
             ("1 tsp", "honey (marinade)", 7, 169640),
             ("1 tsp", "grated ginger (marinade)", 2, 169231),
             ("2", "garlic cloves, grated (1 marinade, 1 sauce)", 6, 169230),
             ("1 tsp", "canola oil", 4.7, 172336),
             ("12 leaves", "green-leaf or romaine lettuce", 200, 169247),
             ("1 cup", "cooked brown rice", 195, 169704),
             ("1 medium", "cucumber, cut in sticks", 200, 168409),
             ("1 medium", "carrot, cut in sticks", 61, 170393),
             ("1 Tbsp", "miso or Korean doenjang (sauce)", 17, 172442),
             ("1 tsp", "gochujang (sauce)", 6, "gochujang"),
             ("1 tsp", "toasted sesame oil (sauce)", 4.5, 171016),
             ("1 tsp", "toasted sesame seeds (sauce)", 3, 170151),
             ("1", "scallion, finely chopped (sauce)", 15, 170005)],
       steps=["Mix the soy sauce, honey, ginger and one grated garlic clove. Coat the chicken and leave 15 minutes (or up to a day in the fridge).",
              "Ssamjang: stir the miso, gochujang, sesame oil, sesame seeds, scallion and the other garlic clove together.",
              "Heat the oil in a skillet over medium heat. Cook the chicken 5 to 6 minutes a side, until it reads 165°F. Rest 3 minutes, then slice thin.",
              "At the table: a lettuce leaf, a spoon of rice, chicken, a cucumber and carrot stick, a dab of ssamjang. Wrap and eat. Small wraps. Learn from Chang."],
       soft="Chop the chicken small, use soft butter lettuce, and skip the raw carrot (or steam it 4 minutes).",
       store="Cooked chicken keeps 3 days in the fridge. Sauce keeps a week. Wash lettuce fresh.",
       tags=["leafy_greens", "high_protein", "honey"])

# ============================================================== DINNER
recipe(id="D1", cat="Dinner", name="Chang's Sunday black bean noodles", native="jajangmyeon (Korean-Chinese)",
       serves=4, active=25, total=40,
       intro="This is his dish. From his father's shop in Incheon, in our story. He makes it every Sunday and I critique it every Sunday. I made it lighter: lean pork, more vegetables, whole-wheat noodles. He complained. Then he had two bowls.",
       ings=[("1 lb", "pork loin, trimmed, in 1/2-inch cubes", 454, 168230),
             ("1/4 cup", "chunjang (Korean black bean paste)", 72, "chunjang"),
             ("2 Tbsp", "canola oil (divided)", 28, 172336),
             ("1 large", "onion, diced", 150, 170000),
             ("1 medium", "zucchini, diced", 196, 169291),
             ("1 medium", "russet potato, peeled, diced small", 213, 170027),
             ("1 cup", "green cabbage, chopped", 89, 169975),
             ("2 cups", "low-sodium chicken broth", 480, 171609),
             ("1 tsp", "sugar", 4.2, 169655),
             ("1 Tbsp + 3 Tbsp water", "cornstarch", 8, 169698),
             ("8 oz dry (about 4 cups cooked)", "whole-wheat spaghetti (or fresh jajang noodles)", 560, 168910),
             ("1/2 medium", "cucumber, in thin matchsticks, to top", 150, 168409)],
       steps=["Heat 1 Tbsp oil in a small pan over medium-low heat. Add the chunjang and fry, stirring constantly, 3 minutes, until it smells nutty. Set aside. (Frying the paste takes away its raw, bitter taste.)",
              "Heat the other Tbsp oil in a large pot or wok over medium-high heat. Brown the pork 5 minutes.",
              "Add the onion, potato, zucchini and cabbage. Stir-fry 5 minutes.",
              "Stir in the fried chunjang and sugar until everything is coated. Add the broth. Simmer 10 minutes, until the potato is soft and the pork reads 145°F or more.",
              "Stir the cornstarch into the water, then into the sauce. Simmer 1 to 2 minutes until glossy and thick.",
              "Meanwhile, cook the noodles according to the package. Drain.",
              "Serve 1 cup of noodles per bowl with a quarter of the sauce and cucumber on top. Mix with chopsticks before eating. Wear a dark shirt."],
       soft="Dice everything small, cook the potato until very soft, and cut the noodles short. The sauce alone over soft rice works too.",
       store="Sauce keeps 4 days in the fridge or 3 months in the freezer. Cook noodles fresh.",
       tags=["high_protein", "fiber", "salty"])

recipe(id="D2", cat="Dinner", name="Beef bulgogi with broccoli and brown rice", native="bulgogi (Korean)",
       serves=4, active=20, total=30,
       intro="The pear is not decoration. It softens the beef. Old Korean trick, and there's nothing magic about it: fruit enzymes and a sharp knife. Thin slices are easier to chew.",
       ings=[("1 1/4 lb", "top sirloin, very thinly sliced (freeze 30 minutes first to slice easily)", 567, 174055),
             ("1/2 large", "Asian pear (or 1 small ripe Bosc pear), grated", 120, 168177),
             ("1 small + 1 medium", "onion (small one grated for marinade, medium one sliced)", 180, 170000),
             ("4", "garlic cloves, grated", 12, 169230),
             ("1 Tbsp", "grated ginger", 6, 169231),
             ("3 Tbsp", "low-sodium soy sauce", 48, 172473),
             ("1 Tbsp", "honey", 21, 169640),
             ("1 Tbsp", "toasted sesame oil", 13.6, 171016),
             ("1 Tbsp", "canola oil", 14, 172336),
             ("4", "scallions, cut in 2-inch pieces", 60, 170005),
             ("1 lb", "broccoli florets", 454, 170379),
             ("3 cups", "cooked brown rice", 585, 169704),
             ("1 Tbsp", "toasted sesame seeds", 9, 170151)],
       steps=["Marinade: mix the grated pear, grated small onion, garlic, ginger, soy sauce, honey and sesame oil in a bowl. Add the beef and toss. Marinate 30 minutes in the fridge (up to overnight).",
              "Steam the broccoli over boiling water 5 to 6 minutes, until tender enough to pierce easily with a fork.",
              "Heat the canola oil in a large skillet over high heat. Add the sliced onion and half the beef in a single layer (don't crowd it). Cook 2 to 3 minutes, turning once, until browned and no pink remains. Repeat with the rest. Add scallions for the last minute.",
              "Serve each plate with 3/4 cup rice, a quarter of the beef and a quarter of the broccoli. Sprinkle with sesame seeds."],
       soft="Slice the beef as thin as paper, or use lean ground beef in the same marinade (cook to 160°F). Steam the broccoli 8 minutes.",
       store="Cooked bulgogi keeps 3 days in the fridge. Raw marinated beef can be frozen flat in a bag for 3 months.",
       tags=["high_protein", "fiber", "honey", "leafy_greens"])

recipe(id="D3", cat="Dinner", name="Mild mapo tofu with bok choy", native="mápó dòufu (Chinese)",
       serves=4, active=20, total=25,
       intro="Real mapo tofu makes your mouth numb. This one is polite. Chang adds chili oil at the table, sweats, and tells me he's 'training'. He's not training. He's sweating.",
       ings=[("1 block (14 oz)", "firm tofu, in 3/4-inch cubes", 397, 172448),
             ("8 oz", "90% lean ground beef (or lean ground pork)", 227, 174030),
             ("1 Tbsp", "miso (or 2 tsp doubanjiang chili bean paste, if you have it)", 17, 172442),
             ("3", "garlic cloves, minced", 9, 169230),
             ("1 Tbsp", "minced ginger", 6, 169231),
             ("1 cup", "low-sodium chicken broth", 240, 171609),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1 Tbsp + 2 Tbsp water", "cornstarch", 8, 169698),
             ("1 Tbsp", "canola oil", 14, 172336),
             ("1/2 tsp", "red pepper flakes (optional)", 0.9, 170932),
             ("3", "scallions, sliced", 45, 170005),
             ("1 lb", "bok choy, cut in 2-inch pieces", 454, 170390),
             ("3 cups", "cooked brown rice", 585, 169704)],
       steps=["Put the tofu cubes in a bowl and cover with just-boiled water for 5 minutes. This firms them up so they don't break. Drain.",
              "Heat the oil in a large skillet over medium-high heat. Cook the beef, breaking it up, 5 minutes, until no pink remains (160°F).",
              "Add the garlic, ginger, miso and pepper flakes. Stir 1 minute.",
              "Add the broth and soy sauce. Slide in the tofu and gently push it around (don't stir hard). Simmer 5 minutes.",
              "Stir the cornstarch into the water, pour it in and gently fold until the sauce is glossy, 1 minute. Top with scallions.",
              "Meanwhile, steam or stir-fry the bok choy 3 to 4 minutes, until the stems are just tender.",
              "Serve each plate with 3/4 cup rice, a quarter of the tofu and a quarter of the bok choy."],
       soft="Use soft tofu, skip the pepper flakes, and chop the bok choy small. It's already one of the softest dinners in this book.",
       store="Keeps 3 days in the fridge. Reheat gently until steaming.",
       tags=["leafy_greens"])

recipe(id="D4", cat="Dinner", name="Soy-braised chicken with potatoes and carrots", native="dakjjim (Korean)",
       serves=4, active=15, total=50,
       intro="One pot. The potatoes soak up the sauce and the chicken falls apart. This is what I cooked on Tuesdays at the counter for thirty years, in our story. People came on Tuesdays.",
       ings=[("1 1/2 lb", "boneless, skinless chicken thighs, halved", 680, 173627),
             ("1 lb (2 small)", "russet potatoes, peeled, in 1 1/2-inch chunks", 454, 170027),
             ("2 medium", "carrots, in 1-inch chunks", 122, 170393),
             ("1 medium", "onion, in wedges", 110, 170000),
             ("4 oz", "fresh shiitake mushrooms, stems removed, halved", 113, 169242),
             ("4", "garlic cloves, minced", 12, 169230),
             ("1 Tbsp", "minced ginger", 6, 169231),
             ("1/4 cup", "low-sodium soy sauce", 64, 172473),
             ("1 Tbsp", "honey", 21, 169640),
             ("1 cup", "water", 0, None),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("2", "scallions, sliced", 30, 170005),
             ("2 cups", "cooked brown rice, to serve (1/2 cup each)", 390, 169704)],
       steps=["Mix the soy sauce, honey, garlic, ginger and water in a large pot.",
              "Add the chicken, potatoes, carrots, onion and mushrooms. Stir to coat.",
              "Bring to a boil, then cover and simmer on low 25 minutes, stirring once or twice.",
              "Uncover and simmer 10 more minutes, until the sauce thickens a little, the potatoes are soft and the chicken reads 165°F.",
              "Stir in the sesame oil. Top with scallions. Serve with rice."],
       soft="Cook 10 minutes longer, until the chicken shreds with a spoon. Cut the carrots thinner.",
       store="Better the next day. Keeps 4 days in the fridge or 3 months frozen. Reheat to 165°F.",
       tags=["high_protein", "honey", "salty"])

recipe(id="D5", cat="Dinner", name="Steamed salmon with ginger and scallion", native="qīng zhēng yú (Chinese)",
       serves=2, active=15, total=25,
       intro="The hot oil at the end hisses. That's the point. Stand back when you pour it. I've seen people get excited and pour toward their own hand.",
       ings=[("2 fillets (5 oz each)", "salmon, skin on or off", 283, 175167),
             ("2-inch piece", "fresh ginger, in very thin matchsticks", 22, 169231),
             ("4", "scallions, in thin 2-inch strips", 60, 170005),
             ("1", "garlic clove, sliced", 3, 169230),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1 Tbsp", "canola oil", 14, 172336),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("4 heads (about 12 oz)", "baby bok choy, halved", 340, 170390),
             ("1 1/2 cups", "cooked brown rice", 293, 169704)],
       steps=["Put the salmon on a heatproof plate that fits in your steamer or a large pot with a rack. Scatter half the ginger and the garlic on top.",
              "Steam over boiling water, covered, 8 to 10 minutes, until the fish flakes easily and reads 145°F. Add the bok choy around the fish (or in a second basket) for the last 4 minutes.",
              "Carefully lift out the plate with oven mitts. Pour off the cooking water on the plate. Scatter the rest of the ginger and the scallions on the fish. Drizzle the soy sauce over.",
              "Heat the canola and sesame oils in a small pan until shimmering, about 1 minute. Standing back, pour the hot oil over the scallions and ginger. It will sizzle.",
              "Serve with rice and bok choy."],
       soft="Salmon is naturally soft. Chop the bok choy leaves and skip the stems.",
       store="Best fresh. Leftover salmon keeps 2 days in the fridge; eat cold on rice or reheat gently.",
       tags=["high_protein", "leafy_greens", "hot_oil"])

recipe(id="D6", cat="Dinner", name="Shrimp and egg stir-fry with peas and broccoli", native="huá dàn xiā rén (Chinese)",
       serves=2, active=15, total=20,
       intro="Fast, soft, cheap if you buy frozen shrimp. Forty-four grams of protein. Chang calls it 'the gym plate'. I call it Tuesday.",
       ings=[("8 oz", "raw shrimp, peeled and deveined (frozen is fine, thawed)", 227, 175179),
             ("4", "large eggs", 200, 171287),
             ("1 cup", "frozen peas", 134, 170016),
             ("2 cups", "small broccoli florets", 182, 170379),
             ("1 cup", "cooked brown rice", 195, 169704),
             ("2", "scallions, sliced", 30, 170005),
             ("1 tsp", "cornstarch", 2.7, 169698),
             ("1/4 tsp", "salt", 1.5, 173468),
             ("1 Tbsp", "canola oil (divided)", 14, 172336),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("pinch", "white pepper", 0, None)],
       steps=["Toss the shrimp with the cornstarch and a pinch of salt.",
              "Heat 1 tsp oil in a large nonstick skillet over medium-high heat. Stir-fry the broccoli with 2 Tbsp water, covered, 3 minutes. Add the peas for 1 minute. Move to a plate.",
              "Add 1 tsp oil and the shrimp. Cook 1 to 2 minutes a side, until pink and opaque all the way through. Move to the plate.",
              "Beat the eggs with the rest of the salt and pepper. Add the last oil, pour in the eggs and stir slowly until just set in large, fully cooked curds.",
              "Return the shrimp and vegetables. Fold together 30 seconds. Drizzle sesame oil, top with scallions, serve with rice."],
       soft="Chop the shrimp into small pieces before cooking. Cook the broccoli 2 minutes longer.",
       store="Best fresh. Keeps 1 day in the fridge; reheat until steaming.",
       tags=["high_protein", "shellfish", "fiber", "eggs", "leafy_greens"])

# ============================================================== SOUPS
recipe(id="S1", cat="Soup", name="Seaweed soup with beef and tofu", native="miyeok-guk (Korean)",
       serves=4, active=15, total=45,
       intro="Koreans eat this on birthdays and after having a baby. I make it for everyone's birthday, including the cat's. Tradition, not medicine. Delicious tradition.",
       ings=[("1/2 oz (about 1 cup soaked)", "dried wakame seaweed (calculated as 140 g soaked)", 140, 170496),
             ("12 oz", "lean beef chuck or brisket, in small thin pieces", 340, 174051),
             ("1/2 block (7 oz)", "firm tofu, in small cubes", 198, 172448),
             ("1 Tbsp", "toasted sesame oil", 13.6, 171016),
             ("3", "garlic cloves, minced", 9, 169230),
             ("2 Tbsp", "low-sodium soy sauce", 32, 172473),
             ("8 cups", "water", 0, None),
             ("1/4 tsp", "salt", 1.5, 173468),
             ("2 cups", "cooked brown rice, to serve (1/2 cup each)", 390, 169704)],
       steps=["Soak the wakame in a big bowl of cold water 15 minutes. It grows a lot. Drain, squeeze out the water, and cut into 2-inch pieces with scissors.",
              "Heat the sesame oil in a large pot over medium heat. Add the beef and garlic and cook, stirring, 3 minutes.",
              "Add the wakame and 1 Tbsp of the soy sauce. Stir 2 minutes.",
              "Add the water. Bring to a boil, then simmer, partly covered, 25 minutes, until the beef is tender.",
              "Add the tofu and the rest of the soy sauce. Simmer 5 more minutes. Taste, then add salt only if it needs it.",
              "Serve with a bowl of rice on the side."],
       soft="Cut the beef into tiny pieces or use lean ground beef (cook to 160°F). Chop the seaweed finely.",
       store="Keeps 4 days in the fridge, 3 months frozen. It gets better on day two.",
       tags=["seaweed"])

recipe(id="S2", cat="Soup", name="Kimchi stew with pork and tofu", native="kimchi-jjigae (Korean)",
       serves=4, active=15, total=35,
       intro="When the kimchi gets too sour to eat plain, it's ready for this. Sour kimchi is not spoiled. It's promoted.",
       ings=[("2 cups", "well-fermented (sour) kimchi, chopped, plus 1/4 cup of its juice", 300, 170392),
             ("8 oz", "lean pork shoulder, in thin bite-size slices", 227, 168258),
             ("1 block (14 oz)", "firm tofu, in 1/2-inch slices", 397, 172448),
             ("1 medium", "onion, sliced", 110, 170000),
             ("1 cup", "white mushrooms, sliced", 70, 169251),
             ("1 Tbsp", "gochujang", 19, "gochujang"),
             ("1 tsp", "Korean chili flakes (gochugaru) or 1/4 tsp red pepper flakes", 1.8, 170932),
             ("1 tsp", "sugar", 4.2, 169655),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("4 cups", "water", 0, None),
             ("2", "scallions, sliced", 30, 170005),
             ("2 cups", "cooked brown rice, to serve (1/2 cup each)", 390, 169704)],
       steps=["Heat the sesame oil in a medium pot over medium heat. Add the pork and cook 3 minutes.",
              "Add the kimchi, onion, gochujang, chili flakes and sugar. Stir-fry 5 minutes, until the kimchi softens and smells toasty.",
              "Add the water and kimchi juice. Bring to a boil, then simmer 15 minutes.",
              "Lay the tofu slices and mushrooms on top. Simmer 5 more minutes, until the pork is tender and everything is hot (the pork is well past 145°F).",
              "Top with scallions. Serve bubbling, with rice."],
       soft="Use soft tofu and chop the kimchi and pork very small.",
       store="Keeps 4 days in the fridge. Many people like it best on day two.",
       tags=["kimchi", "salty"])

recipe(id="S3", cat="Soup", name="Soft tofu stew with shrimp and egg", native="sundubu-jjigae (Korean)",
       serves=2, active=15, total=25,
       intro="Silky tofu, spicy broth. The egg goes in at the end and you cook it until it's set. Not runny. We're too old for runny eggs, and so is your stomach.",
       ings=[("12 oz", "soft tofu (a tube of sundubu or a block of soft tofu)", 340, 172449),
             ("4 oz", "raw shrimp, peeled, chopped", 113, 175179),
             ("2", "large eggs", 100, 171287),
             ("1/2 cup", "kimchi, chopped", 75, 170392),
             ("1/2 medium", "zucchini, diced", 98, 169291),
             ("1/2 medium", "onion, diced", 55, 170000),
             ("2", "garlic cloves, minced", 6, 169230),
             ("2 tsp", "Korean chili flakes (gochugaru) or 1/2 tsp red pepper flakes", 3.6, 170932),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1 1/2 cups", "low-sodium chicken broth", 360, 171609),
             ("1", "scallion, sliced", 15, 170005),
             ("1 cup", "cooked brown rice, to serve", 195, 169704)],
       steps=["Heat the sesame oil in a small pot over medium-low heat. Add the chili flakes and garlic and stir 30 seconds. Don't let them burn.",
              "Add the onion, zucchini and kimchi. Cook 3 minutes.",
              "Add the broth and soy sauce. Bring to a boil.",
              "Spoon in the tofu in big pieces. Add the shrimp. Simmer 4 minutes, until the shrimp are pink and opaque.",
              "Crack in the eggs. Simmer 4 to 5 minutes more, spooning broth over them, until the whites and yolks are completely firm.",
              "Top with scallion. Serve with rice."],
       soft="It's already soft. Chop the shrimp small and break the cooked egg up in the bowl.",
       store="Best fresh. Keeps 1 day in the fridge (without the egg if possible). Reheat until steaming.",
       tags=["kimchi", "shellfish", "high_protein", "eggs"])

recipe(id="S4", cat="Soup", name="Egg-drop soup with tofu, spinach and peas", native="dàn huā tāng (Chinese)",
       serves=2, active=10, total=15,
       intro="Fifteen minutes. Thirty grams of protein. For the night you say 'I'm not hungry' but you are.",
       ings=[("4 cups", "low-sodium chicken broth", 960, 171609),
             ("1/2 block (7 oz)", "soft tofu, in small cubes", 198, 172449),
             ("3", "large eggs, beaten", 150, 171287),
             ("3 cups (3 oz)", "baby spinach", 85, 168462),
             ("1/2 cup", "frozen peas", 67, 170016),
             ("1 cup", "white mushrooms, sliced", 70, 169251),
             ("1 tsp", "grated ginger", 2, 169231),
             ("1 tsp", "low-sodium soy sauce", 5, 172473),
             ("1 Tbsp + 2 Tbsp water", "cornstarch", 8, 169698),
             ("1/2 tsp", "toasted sesame oil", 2.3, 171016),
             ("1", "scallion, sliced", 15, 170005),
             ("pinch", "white pepper", 0, None)],
       steps=["Bring the broth, ginger and mushrooms to a simmer in a pot. Cook 3 minutes.",
              "Add the tofu and peas. Simmer 2 minutes.",
              "Stir the cornstarch into the water, then stir it into the soup. Simmer 1 minute until slightly thick.",
              "Stir the soup in a slow circle. While it's moving, pour the beaten eggs in a thin stream. Let them set into ribbons, then simmer 1 more minute so the egg is fully cooked.",
              "Stir in the spinach until wilted. Add soy sauce, sesame oil and pepper. Top with scallion."],
       soft="Already soft. Chop the spinach before adding.",
       store="Keeps 2 days in the fridge. Reheat until steaming.",
       tags=["leafy_greens", "eggs"])

recipe(id="S5", cat="Soup", name="Chicken, ginger and jujube soup", native="weeknight samgyetang (Korean)",
       serves=4, active=15, total=60,
       intro="Koreans eat this on the hottest days of summer. I don't know why either. It's good in winter too. Jujubes are red dates: sweet, a little chewy. Tradition says a lot about them. I say they're tasty. That's enough.",
       ings=[("1 1/4 lb", "boneless, skinless chicken thighs (or 2 lb bone-in drumsticks)", 567, 173627),
             ("1/3 cup", "short-grain rice, rinsed", 67, 168931),
             ("10", "garlic cloves, peeled, whole", 30, 169230),
             ("3-inch piece", "fresh ginger, sliced", 33, 169231),
             ("8", "dried jujubes (red dates)", 32, 168152),
             ("1", "leek, white and light green parts, sliced and washed", 89, 169246),
             ("1 cup", "daikon radish, peeled and diced", 116, 168451),
             ("8 cups", "water", 0, None),
             ("1/2 tsp", "salt", 3, 173468),
             ("3", "scallions, sliced", 45, 170005),
             ("pinch", "black pepper", 0, None)],
       steps=["Put everything except the salt, scallions and pepper in a large pot.",
              "Bring to a boil, skim off any foam, then simmer partly covered 45 minutes, until the rice has softened into the broth and the chicken is very tender (well past 165°F).",
              "Lift out the chicken, shred it, and return it to the pot. Remove the ginger slices if you like.",
              "Season with the salt. Serve with scallions and pepper. Eat the jujubes (watch for the pits) and the soft garlic cloves."],
       soft="Already soft. Pit and chop the jujubes before serving. Mash the garlic into the broth.",
       store="Keeps 4 days in the fridge, 3 months frozen. Reheat to 165°F.",
       tags=["high_protein"])

# ============================================================== SNACKS
recipe(id="N1", cat="Snack", name="Warm edamame with sesame and chili", native="Sun's TV snack",
       serves=2, active=3, total=8,
       intro="Better than chips. Fourteen grams of protein. Your hands stay busy during the K-drama. Mine do.",
       ings=[("1 1/2 cups", "frozen shelled edamame", 233, 168411),
             ("1/2 tsp", "toasted sesame oil", 2.3, 171016),
             ("1/4 tsp", "flaky or coarse salt", 1.2, 173468),
             ("pinch", "red pepper flakes, and a squeeze of lemon", 0, None)],
       steps=["Microwave or boil the edamame 4 to 5 minutes, until hot and tender. Drain.",
              "Toss with sesame oil, salt, pepper flakes and lemon."],
       soft="Cook 2 minutes longer and mash lightly with a fork; spread on toast.",
       store="Cooked edamame keeps 4 days in the fridge. Good cold.",
       tags=["fiber"])

recipe(id="N2", cat="Snack", name="Soy-braised eggs", native="gyeran-jangjorim (Korean)",
       serves=3, active=10, total=30,
       intro="Make six on Sunday. Grab two when you're hungry and lazy. Everybody is hungry and lazy at four o'clock.",
       ings=[("6", "large eggs", 300, 171287),
             ("3 Tbsp", "low-sodium soy sauce", 48, 172473),
             ("3/4 cup", "water", 0, None),
             ("1 Tbsp", "honey", 21, 169640),
             ("4", "garlic cloves, smashed", 12, 169230)],
       steps=["Hard-boil the eggs: cover with cold water, bring to a boil, then simmer 10 minutes, until the yolks are completely firm. Cool in cold water and peel.",
              "Bring the soy sauce, water, honey and garlic to a boil in a small pot.",
              "Add the peeled eggs. Simmer 10 minutes on low, rolling them every few minutes so they color evenly.",
              "Store the eggs in the liquid in a covered container in the fridge. Eat two at a time."],
       soft="Chop and mix with a little of the liquid over soft rice.",
       store="Keeps 4 days in the fridge in the liquid. Don't leave them out more than 2 hours.",
       tags=["honey", "eggs", "braise_overcount"])

recipe(id="N3", cat="Snack", name="Chilled tofu with scallion-soy sauce", native="liángbàn dòufu (Chinese) / naeng-dubu (Korean)",
       serves=2, active=5, total=5,
       intro="No cooking. Five minutes. Fifteen grams of protein. If you say you don't have time for this, you're lying to me and I'm AI, so I know.",
       ings=[("1 block (14 oz)", "soft tofu, well chilled", 397, 172449),
             ("1 Tbsp", "low-sodium soy sauce", 16, 172473),
             ("1 tsp", "rice or white vinegar", 5, 172237),
             ("1 tsp", "toasted sesame oil", 4.5, 171016),
             ("1", "scallion, finely chopped", 15, 170005),
             ("1 tsp", "toasted sesame seeds", 3, 170151),
             ("1/2 tsp", "Korean chili flakes (optional)", 0.9, 170932),
             ("1/2 cup", "diced cucumber", 52, 168409)],
       steps=["Drain the tofu and set it on a plate. Cut into thick slices, keeping the block shape.",
              "Mix the soy sauce, vinegar, sesame oil, scallion, sesame seeds and chili flakes.",
              "Spoon the sauce over the tofu. Scatter the cucumber around. Eat cold, with a spoon."],
       soft="Already soft. Skip the cucumber.",
       store="Best fresh. Opened tofu keeps 3 days in the fridge covered in fresh water, changed daily.",
       tags=[])
