"""Daily Practice Sessions 1–14 (Strong Years). Weekday rotation per OFFER.md §1.2:
Mon strength, Tue mobility, Wed balance, Thu strength, Fri breath + qigong, Sat walk-and-talk, Sun rest + stretch.

Each segment: dict(name, kind, secs, tracks={rebuild, steady, strong, iron: (exercise_id, version, dose)}, vo=[lines], ost=[...])
version: "easier" | "main" | "harder". A dose containing "advanced" is labelled Advanced on screen (SAFETY M-06).
Rebuild = chair-based: seated, or standing with both hands on the counter and the chair right behind you.
"""

def same(ex, dose_r, dose_s, dose_st, dose_i, v=("easier", "main", "main", "harder")):
    return dict(rebuild=(ex, v[0], dose_r), steady=(ex, v[1], dose_s), strong=(ex, v[2], dose_st), iron=(ex, v[3], dose_i))


def seg(name, kind, secs, tracks=None, vo=(), ost=(), sun=()):
    return dict(name=name, kind=kind, secs=secs, tracks=tracks, vo=list(vo), ost=list(ost), sun=list(sun))


SESSIONS = []


def session(**k):
    SESSIONS.append(k)


# ------------------------------------------------------------------ WEEK 1
session(n=1, weekday="Monday", type="Strength", title="Legs first", set="SET-GARAGE", wardrobe="C-TRAIN-A",
        swaps=dict(sore_knee="Sit-to-stand from a higher seat (cushion) and only halfway down; swap the wall sit for seated knee straightening.",
                   sore_back="Keep the row upright with the towel pull-apart instead of the hinged jug row.",
                   low_energy="Do one set of everything and the cool-down. That still counts."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Good morning. I'm Chang. AI character. Real chair.",
        "Today is strength. Legs first.",
        "Push your chair against the wall. Shoes on. Kitchen counter close by.",
        "Pick your level on the screen. Rebuild, Steady, Strong or Iron.",
        "Chest pain, dizziness, sharp pain? Stop. Sit down. Call your doctor."],
        ost=["Day 1 · Strength", "Chair against the wall", "Stop if chest pain, dizziness or sharp pain"]),
    seg("Ankle pumps", "warmup", 20, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4),
        vo=["Sit down first. Toes away, toes to you.", "Wake up the calves. They pump blood back up."]),
    seg("March", "warmup", 40, dict(rebuild=("seated_march", "main", "40 seconds, seated"), steady=("standing_march", "main", "40 seconds, hand on the counter"),
                                      strong=("standing_march", "harder", "40 seconds, knees higher"), iron=("standing_march", "harder", "40 seconds, brisk")),
        vo=["Rebuild, stay seated. Everyone else, stand slowly. Hand on the counter.", "March. Easy rhythm. Talk to me if you want. I'm listening. Sort of."]),
    seg("Shoulder rolls", "warmup", 20, same("shoulder_rolls", "8 rolls", "8 rolls", "8 rolls", "8 rolls + arm circles", ("main", "main", "main", "harder")),
        vo=["Shoulders up. Back. Down.", "Breathe in up, breathe out down."]),
    seg("Chair sit-to-stand", "block", 140,
        dict(rebuild=("sit_to_stand", "easier", "2 sets of 6, hands on thighs, cushion on the seat"),
             steady=("sit_to_stand", "main", "2 sets of 8, arms crossed"),
             strong=("sit_to_stand", "harder", "3 sets of 8, 3-second lower"),
             iron=("sit_to_stand", "harder", "3 sets of 10, gallon jug at chest, 1-second pause above the seat (advanced)")),
        vo=["Chair against the wall. Sit in the middle. Feet flat, a little behind your knees.",
            "Nose over toes. Push the floor away. Stand tall.",
            "Sit down slow. The chair is farther away than you think.",
            "Breathe out as you stand.",
            "Rest. Shake the legs. Next set when you're ready.",
            "Knees point where your toes point. Good."],
        ost=["Breathe out as you stand", "Knees over toes"]),
    seg("Push", "block", 110,
        dict(rebuild=("seated_chest_press", "main", "2 sets of 8, seated"),
             steady=("wall_pushup", "main", "2 sets of 8"),
             strong=("wall_pushup", "harder", "2 sets of 10, feet farther back"),
             iron=("counter_pushup", "harder", "3 sets of 10, 3-second lower")),
        vo=["Now arms. Rebuild, sit and press forward. Steady and Strong, the wall. Iron, the counter.",
            "Body in one straight line. Chest to the wall, not your chin.",
            "Breathe out as you push away.",
            "Muscle is a savings account. Deposit now."],
        ost=["Breathe out as you push"]),
    seg("Heel raises", "block", 60,
        dict(rebuild=("heel_raise", "easier", "2 sets of 12, seated"), steady=("heel_raise", "main", "2 sets of 10, both hands on the counter"),
             strong=("heel_raise", "harder", "2 sets of 12, one hand on the counter"), iron=("heel_raise", "harder", "2 sets of 8 each leg, single leg, both hands on the counter")),
        vo=["Hands on the counter. Up on your toes. Pause. Down for three.", "Breathe out as you rise.", "Calves are your second heart pump. Treat them nicely."]),
    seg("Row", "block", 100,
        dict(rebuild=("towel_row", "main", "3 pulls, 3-second squeeze"), steady=("jug_row", "main", "2 sets of 8 each arm, half-gallon jug"),
             strong=("jug_row", "harder", "2 sets of 10 each arm, gallon jug"), iron=("jug_row", "harder", "3 sets of 10 each arm, gallon jug, 1-second pause")),
        vo=["Now pull. Hand on the counter. Long back.", "Pull with your elbow, not your hand.", "Breathe out as you pull. Lower slow.", "Switch sides."]),
    seg("Finisher", "block", 55,
        dict(rebuild=("seated_knee_ext", "main", "1 set of 8 each leg"), steady=("wall_sit_high", "main", "2 holds of 15 seconds"),
             strong=("wall_sit_high", "main", "2 holds of 20 seconds"), iron=("wall_sit_high", "harder", "2 holds of 30 seconds, a little lower (advanced)")),
        vo=["Last one. Back on the wall. Slide down a few inches. Chair beside you.",
            "Keep breathing. Count out loud with me. Talking means you're not holding your breath.",
            "High blood pressure or a heart condition? Keep it short and ask your doctor about long holds."],
        ost=["Keep breathing: count out loud", "High BP? Ask your doctor before long holds"]),
    seg("Cool-down", "cooldown", 70,
        dict(rebuild=("calf_stretch", "easier", "20 seconds each leg"), steady=("calf_stretch", "main", "20 seconds each leg"),
             strong=("calf_stretch", "main", "20 seconds each leg"), iron=("calf_stretch", "harder", "20 seconds each leg")),
        vo=["Hands on the wall. One foot back. Heel down.", "Breathe slow.", "Now sit. Two sniffs in through the nose, one long sigh out."]),
    seg("Close", "close", 25, vo=["That's Day 1. Write your number in the log.", "Strong is a habit. Same time tomorrow."],
        ost=["Log today's session"]),
])

session(n=2, weekday="Tuesday", type="Mobility", title="Loosen the hinges", set="SET-LIVING", wardrobe="C-CASUAL",
        swaps=dict(sore_knee="Skip the figure-4; do extra ankle pumps and the seated hamstring stretch.",
                   sore_back="Keep the turns tiny and do the chest lift slowly; skip the bird-dog.",
                   low_energy="Do the seated part only, then the breathing."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Tuesday. Mobility day. My least favorite.",
        "Sun is standing behind the camera. So we do it properly.",
        "Nothing forced today. Only as far as comfortable.",
        "Stop if anything is sharp, or you feel dizzy."],
        ost=["Day 2 · Mobility", "Only as far as comfortable"], sun=["Hips. Now."]),
    seg("Ankle pumps", "warmup", 30, same("ankle_pumps", "10 pumps + 5 circles", "10 pumps + 5 circles", "10 pumps + 5 circles", "10 pumps + 5 circles, foot lifted", ("main", "main", "main", "harder")),
        vo=["Sit tall. Toes away, toes back. Then circles.", "Breathe slowly."]),
    seg("Neck nods and half-turns", "block", 45, same("neck_nods", "5 nods, 3 turns each side, tiny", "5 nods, 3 turns each side", "5 nods, 3 turns each side", "5 nods, 3 turns each side + chin tucks", ("easier", "main", "main", "harder")),
        vo=["Nod yes. Small. Slow.", "Turn right, only as far as comfortable. Back. Left.", "No big circles with the neck. Ever. Nods and half-turns."],
        ost=["Nods and half-turns only"]),
    seg("Chest lift", "block", 40, same("chest_lift", "6 lifts", "8 lifts", "8 lifts", "8 lifts, 3-second hold", ("easier", "main", "main", "harder")),
        vo=["Sit near the front of the chair. Lift your chest. Grow tall.", "Breathe in as you lift. Out as you relax."]),
    seg("Gentle seated turn", "block", 50, same("seated_rotation", "4 each side, small", "6 each side", "6 each side", "6 each side, hand on knee as a guide", ("easier", "main", "main", "harder")),
        vo=["Arms crossed. Grow tall first. Then turn.", "Breathe out as you turn. Only as far as comfortable.", "Osteoporosis? Small and gentle. Never force it."],
        ost=["Osteoporosis: small and gentle"]),
    seg("Seated hamstring stretch", "block", 60, same("hamstring_seated", "20 seconds each leg, lean 1 inch", "20 seconds each leg", "2 × 20 seconds each leg", "2 × 20 seconds each leg, toes pulled back", ("easier", "main", "main", "harder")),
        vo=["One leg straight. Heel down. Toes up.", "Long back. Hinge from the hips. Not the belly.", "Breathe slow. A gentle stretch is enough."]),
    seg("Figure-4 hip stretch", "block", 50, same("figure4", "20 seconds each side, ankle on shin", "20 seconds each side", "20 seconds each side", "30 seconds each side, hinge forward", ("easier", "main", "main", "harder")),
        vo=["Ankle on the other knee, or on the shin. Sit tall.", "Let the knee relax. Don't push it.", "New hip? Follow your surgeon's precautions. Skip this one if they said no crossing."],
        ost=["New hip? Follow your surgeon's precautions"]),
    seg("Standing hip-front stretch", "block", 60, dict(rebuild=("hip_flexor", "easier", "20 seconds each side, both hands on the counter"), steady=("hip_flexor", "main", "20 seconds each side"),
                                                      strong=("hip_flexor", "main", "2 × 20 seconds each side"), iron=("hip_flexor", "harder", "2 × 20 seconds each side, arm reaching up")),
        vo=["Stand slowly. Hand on the counter. Small step back.", "Tuck the tailbone. Squeeze the back buttock.", "Breathe slow. Switch."],
        sun=["He skips this one when I'm not home. I'm always home."]),
    seg("Calf stretch", "block", 45, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg, bent-knee version too", ("easier", "main", "main", "harder")),
        vo=["Hands on the counter. One foot back. Heel down.", "Breathe slowly through the stretch."]),
    seg("Standing bird-dog", "block", 50, dict(rebuild=("standing_birddog", "easier", "4 each side, leg only, both hands on the counter"), steady=("standing_birddog", "main", "6 each side"),
                                              strong=("standing_birddog", "main", "8 each side"), iron=("standing_birddog", "harder", "8 each side, 3-second reach")),
        vo=["Both hands on the counter. Slide one foot back.", "Reach the other arm forward if you're steady.", "Long back. Breathe out as you reach."]),
    seg("Wall slides", "block", 40, same("wall_slide", "6 finger walks", "6 slides", "8 slides", "8 slides, 2-second hold", ("easier", "main", "main", "harder")),
        vo=["Back on the wall. Arms like a goalpost.", "Slide up only as far as comfortable. Ribs down."]),
    seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute, in 3 out 4", "1 minute", "1 minute", "1 minute", ("easier", "main", "main", "main")),
        vo=["Sit. In for four. Out for six. No holding.", "About six breaths a minute. Slow breathing like this raises heart-rate variability while you do it."]),
    seg("Close", "close", 25, vo=["That's mobility. Sun says seven out of ten.", "Tomorrow, balance. Same time."], sun=["Seven. Because I love you."]),
])

session(n=3, weekday="Wednesday", type="Balance", title="Steady feet", set="SET-KITCHEN", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Keep feet wider and holds shorter; skip the heel-to-toe walk.",
                   sore_back="Skip the clock reach behind you; reach front and side only.",
                   low_energy="Weight shifts, heel-to-toe stand and one-leg stand only."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Wednesday. Balance. We live at the counter today.",
        "Shoes on. No rugs. Chair right behind you.",
        "Balance drills always start with support. Hands hover. They don't wander.",
        "Dizzy? Sit down. Tell your doctor if it keeps happening."],
        ost=["Day 3 · Balance", "Stand at the counter", "Stop if dizzy"]),
    seg("Weight shifts", "warmup", 45, same("weight_shift", "5 each way, seated", "5 each way", "8 each way", "8 each way, one hand hovering", ("easier", "main", "main", "harder")),
        vo=["Both hands on the counter. Shift right. Pause. Shift left.", "Like a tree in wind. Feet stay flat."]),
    seg("Heel-to-toe stand", "block", 75,
        dict(rebuild=("tandem_stand", "easier", "3 × 10 seconds each side, half-step, both hands on the counter"), steady=("tandem_stand", "main", "3 × 10 seconds each side, hands on the counter"),
             strong=("tandem_stand", "harder", "3 × 15 seconds each side, one hand hovering"), iron=("tandem_stand", "harder", "3 × 20 seconds each side, both hands hovering")),
        vo=["Hands on the counter. One foot in front of the other. Heel to toe.",
            "Eyes on something still. Soft knees.", "Breathe slowly. Ten, nine, eight...", "Switch feet.",
            "Rebuild: half a step, both hands down. That's real practice."],
        ost=["Hands hover, they don't wander"]),
    seg("One-leg stand", "block", 75,
        dict(rebuild=("single_leg", "easier", "3 × 10 seconds each side, toe stays down"), steady=("single_leg", "main", "3 × 10 seconds each side, both hands on the counter"),
             strong=("single_leg", "harder", "3 × 15 seconds each side, one hand hovering"), iron=("single_leg", "harder", "3 × 20 seconds each side, both hands hovering")),
        vo=["Hands on the counter. Weight on the left foot. Lift the right a few inches.",
            "Stand tall. Squeeze the buttock of the standing leg.", "Count out loud. Breathe.",
            "This is my level. Thirty seconds, hands hovering, right beside the counter. Not your starting point."],
        ost=["Chang's level — not your starting point"]),
    seg("Heel-to-toe walk", "block", 60,
        dict(rebuild=("heel_toe_walk", "easier", "2 lengths, feet apart, holding the counter"), steady=("heel_toe_walk", "main", "2 lengths, hand on the counter"),
             strong=("heel_toe_walk", "harder", "2 lengths, hand hovering"), iron=("heel_toe_walk", "harder", "2 lengths forward, hand hovering + 1 length backward, hand on the counter")),
        vo=["One hand on the counter. Heel in front of toes. Ten steps.", "Eyes forward. Slow is correct.", "Turn carefully. Walk back."]),
    seg("Side steps", "block", 50, same("side_step", "1 set of 6 each way", "2 sets of 10 each way", "2 sets of 10 each way, knees bent", "2 sets of 12 each way, knees bent", ("easier", "main", "harder", "harder")),
        vo=["Face the counter. Step right. Feet meet. Ten steps.", "Toes forward. Stay tall. Back to the left."]),
    seg("Sit-to-stand, no hands", "block", 50,
        dict(rebuild=("sit_to_stand", "easier", "1 set of 5, hands on thighs"), steady=("sit_stand_nohands", "main", "1 set of 6"),
             strong=("sit_stand_nohands", "harder", "1 set of 6, feet together"), iron=("sit_stand_nohands", "harder", "2 sets of 6, feet together, 3-second lower")),
        vo=["Chair against the wall. Stand. Find your balance at the top. Two seconds.", "Breathe out as you stand. Sit slow."]),
    seg("Clock reach", "block", 50, same("clock_reach", "3 each way, front and side only", "3 each direction", "4 each direction", "4 each direction, on one foot for 12 o'clock", ("easier", "main", "main", "harder")),
        vo=["Side-on to the counter. Near hand down.", "Reach to twelve o'clock. Back. Three o'clock. Back.", "Behind you, only as far as comfortable. Breathe out as you reach."]),
    seg("Heel raises", "block", 40, same("heel_raise", "1 set of 10, seated", "1 set of 10", "1 set of 12, one hand", "1 set of 8 each leg", ("easier", "main", "harder", "harder")),
        vo=["Both hands on the counter. Up. Pause. Down for three.", "Breathe out as you rise."]),
    seg("Cyclic sighing", "cooldown", 30, same("cyclic_sigh", "30 seconds", "30 seconds", "30 seconds", "30 seconds", ("main",) * 4),
        vo=["Sit. Two sniffs in. One long sigh out."]),
    seg("Close", "close", 25, vo=["Good. Balance is a skill. Skills get better with practice.", "Brush your teeth heel-to-toe tonight. Hand on the sink."],
        ost=["Tonight: toothbrush balance"]),
])

session(n=4, weekday="Thursday", type="Strength", title="Push, pull, carry", set="SET-GARAGE", wardrobe="C-TRAIN-A",
        swaps=dict(sore_knee="Replace step-ups with seated knee straightening; power stands from a higher seat, normal speed.",
                   sore_back="Use the seated hinge instead of the jug pick-up; carry one light bag only.",
                   low_energy="Do the power stands, the curls and the carry. One set each."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Thursday. Second strength day.",
        "Today we stand up faster. Not sloppy. Faster.",
        "Lifting quick and lowering slow helps older adults move better in daily life, in the research.",
        "Chair against the wall. Bottom stair with a rail, if you have one. Stop if anything feels wrong."],
        ost=["Day 4 · Strength", "Fast up, slow down", "Stop if chest pain, dizziness or sharp pain"]),
    seg("March", "warmup", 40, dict(rebuild=("seated_march", "main", "40 seconds"), steady=("standing_march", "main", "40 seconds"),
                                      strong=("standing_march", "harder", "40 seconds"), iron=("standing_march", "harder", "40 seconds")),
        vo=["Hand on the counter. March. Warm up the hips.", "Breathe steady. You should be able to talk."]),
    seg("Shoulder rolls", "warmup", 25, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls", "8 rolls + arm circles", ("main", "main", "main", "harder")),
        vo=["Up, back, down. Breathe in up, out down."]),
    seg("Easy sit-to-stands", "warmup", 30, same("sit_to_stand", "3 easy reps, hands on thighs", "5 easy reps", "5 easy reps", "5 easy reps", ("easier", "main", "main", "main")),
        vo=["Chair against the wall. Five easy ones. Just waking the legs.", "Breathe out as you stand."]),
    seg("Power stands", "block", 110,
        dict(rebuild=("sit_to_stand", "easier", "2 sets of 5, normal speed, hands on thighs"), steady=("power_stand", "main", "2 sets of 5"),
             strong=("power_stand", "main", "3 sets of 5"), iron=("power_stand", "harder", "3 sets of 6, gallon jug at chest (advanced)")),
        vo=["Sit tall. Pop up. Stand tall one second. Lower for three.",
            "Fast up, slow down. Breathe out hard as you stand.",
            "If standing fast makes you dizzy, go back to normal speed.",
            "Getting up quick is what saves you when you trip. Legs first."],
        ost=["Dizzy? Normal speed"]),
    seg("Step-ups", "block", 110,
        dict(rebuild=("seated_march", "harder", "2 × 30 seconds, knees high, seated"), steady=("step_up", "easier", "2 sets of 10 toe taps, hand on the rail"),
             strong=("step_up", "main", "2 sets of 6 each leg, hand on the rail"), iron=("step_up", "harder", "2 sets of 8 each leg, bag in the free hand (advanced)")),
        vo=["Bottom stair. Hand on the rail. The whole time.",
            "Whole foot on the step. Push through the heel.", "Breathe out as you step up. Step down slow.",
            "Rebuild: stay seated, knees high. Same muscles."],
        ost=["Rail hand stays on the rail"]),
    seg("Hinge", "block", 80,
        dict(rebuild=("seated_hinge", "main", "2 sets of 6"), steady=("hip_hinge", "main", "2 sets of 8"),
             strong=("hip_hinge", "harder", "2 sets of 8, jug from the chair seat"), iron=("hip_hinge", "harder", "3 sets of 8, jug from the bottom step")),
        vo=["Hands on the counter. Hips back like closing a car door.", "Long back. Chest proud. No rounding.",
            "Squeeze your buttocks to stand. Breathe out.", "Osteoporosis? This is the safe way to bend. Long back."],
        ost=["Long back. No rounding."]),
    seg("Curls", "block", 60, same("bottle_curl", "2 sets of 8, light bottles", "2 sets of 10, bottles", "2 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", ("main", "main", "harder", "harder")),
        vo=["Sit tall. Elbows by your sides. Curl up. Lower slow.", "Breathe out as you curl.", "Yes, I'm flexing. Sun, don't look."],
        sun=["NO MIRROR FLEXING."]),
    seg("Carry", "block", 60,
        dict(rebuild=("towel_wring", "main", "3 wrings each direction (seated grip work)"), steady=("carry", "easier", "2 walks of 20 seconds, one light bag, hand on the counter"),
             strong=("carry", "main", "2 walks of 30 seconds, two bags"), iron=("carry", "harder", "3 walks of 40 seconds, two heavy bags")),
        vo=["Pick the bags up with a hinge. Long back.", "Stand tall. Short steady steps.", "Breathe. You should be able to talk.", "Put them down the same way. Hinge."]),
    seg("Towel wring", "block", 40, same("towel_wring", "2 wrings each way", "3 wrings each way", "3 wrings each way", "3 wrings each way, damp towel", ("easier", "main", "main", "harder")),
        vo=["Wring it like laundry. Three seconds.", "Breathe out as you squeeze."]),
    seg("Cool-down", "cooldown", 60, dict(rebuild=("chest_lift", "main", "6 lifts"), steady=("chest_lift", "main", "6 lifts"),
                                            strong=("chest_lift", "main", "6 lifts"), iron=("chest_lift", "main", "6 lifts")),
        vo=["Sit. Lift the chest. Relax.", "Two sniffs in. Long sigh out. Twice more."]),
    seg("Close", "close", 25, vo=["Push, pull, carry. That's daily life. You trained it.", "One more. A good one. Tomorrow."]),
])

session(n=5, weekday="Friday", type="Breath + qigong", title="Breathe and flow", set="SET-PROM", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Do every piece seated or with a narrow, tall stance.",
                   sore_back="Seated versions; skip the looking-back turn if it bothers you.",
                   low_energy="Breathing plus two pieces. That's enough."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Friday. Breath and flow.",
        "Tai chi and qigong are exercise. That's how we teach them. Movement you can measure.",
        "Today: slow breathing, then five pieces of a qigong set called baduanjin.",
        "We skip two pieces. They round the spine and put your head below your heart. Not for everyone. So not for us.",
        "Chair behind you. Sit down anytime.",
        "Stop if you feel dizzy, light-headed or any chest pain."],
        ost=["Day 5 · Breath + qigong", "Chair behind you", "Stop if dizzy or chest pain"]),
    seg("Cyclic sighing", "block", 120, same("cyclic_sigh", "90 seconds, seated", "2 minutes", "2 minutes", "2 minutes", ("easier", "main", "main", "main")),
        vo=["Sit comfortably. Breathe in through the nose.", "At the top, sip a little more air.", "Now a long, slow sigh out through the mouth.",
            "No holding. Ever. The out-breath is longer.", "In a one-month study, five minutes of this a day lifted mood more than meditation.",
            "Light-headed? Go back to normal breathing."],
        ost=["2 sniffs in · 1 long sigh out", "No breath holds"]),
    seg("Holding up the sky", "block", 60, same("sky_lift", "4 reps, seated, to shoulder height", "4 reps", "5 reps, slower", "5 reps, rise onto toes, chair back in one hand", ("easier", "main", "main", "harder")),
        vo=["Stand slowly. Fingers laced at your belly.", "Breathe in. Hands float up. Palms to the sky.", "Only to comfortable height. Breathe out. Arms float down."]),
    seg("Drawing the bow", "block", 60, same("draw_bow", "3 each side, seated", "3 each side", "4 each side", "4 each side, knees a little more bent", ("easier", "main", "main", "harder")),
        vo=["Feet a little wide. High stance. Not a squat.", "Push the left hand out. Pull the right elbow back. Eyes follow.", "Breathe out as you draw. Switch."]),
    seg("Separating heaven and earth", "block", 60, same("heaven_earth", "3 each side, seated", "3 each side", "4 each side", "4 each side, slower", ("easier", "main", "main", "harder")),
        vo=["One hand presses up. One presses down.", "Breathe in as you separate. Out as you return.", "Shoulder sore? Only to shoulder height."]),
    seg("Looking back", "block", 50, same("owl_look", "3 each side, eyes more than head", "3 each side", "3 each side", "3 each side, hold one breath", ("easier", "main", "main", "harder")),
        vo=["Stand or sit tall. Turn your head, only as far as comfortable.", "Chin level. Shoulders down. Half-turns only."],
        ost=["Half-turns only"]),
    seg("Punching with a steady gaze", "block", 50, same("fists", "4 each side, seated", "4 each side", "5 each side", "5 each side, lower stance", ("easier", "main", "main", "harder")),
        vo=["Loose fists at the waist. Slow punch forward. Turn the palm down.", "Open, grip the air, pull it back.", "Breathe out as you punch. This is not boxing. Sun asked."]),
    seg("Cloud hands", "block", 60, same("cloud_hands", "1 minute, seated, arms only", "1 minute, near the counter", "1 minute", "1 minute with a side step", ("easier", "main", "main", "harder")),
        vo=["Shift your weight right. Right hand floats past your face.", "Shift left. The hands switch. Like wiping a big window.",
            "In tai chi we call this sinking. Really, it's lowering your center of mass. Soft knees.",
            "Slow weight shifts like this are balance practice. And balance is one of the most trainable things there is."],
        ost=["Soft knees, slow shifts"]),
    seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute, in 3 out 4", "1 minute", "1 minute", "1 minute", ("easier", "main", "main", "main")),
        vo=["Sit. In for four. Out for six.", "No pause at the top. No pause at the bottom."]),
    seg("Close", "close", 25, vo=["Every day, a little.", "Tomorrow we walk. Find your shoes."]),
])

session(n=6, weekday="Saturday", type="Walk-and-talk", title="Walk with me", set="SET-PROM", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Flat route only, easy pace throughout, shorter brisk bits.",
                   sore_back="Easy pace; take the rests on a bench.",
                   low_energy="Easy pace the whole time. Still counts."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Saturday. We walk and talk.",
        "Good shoes. A flat route. No ice. Cane or walker if you use one.",
        "Indoors is fine. Kitchen to front door and back.",
        "Chest pain or unusual breathlessness? Stop, sit, call your doctor."],
        ost=["Day 6 · Walk", "Indoors counts", "Chest pain? Stop and call"], sun=["Visor on. It's fashion."]),
    seg("Easy walk", "block", 120,
        dict(rebuild=("seated_march", "main", "2 minutes seated, or walker lengths of the hallway at your pace"), steady=("walk", "easier", "2 minutes, easy pace"),
             strong=("walk", "main", "2 minutes, easy pace"), iron=("walk", "main", "2 minutes, easy pace")),
        vo=["Easy pace. Tall. Eyes ahead, not at your feet.", "Arms swing. Heel, then toe.",
            "In adults over 60, the benefit linked with daily steps levelled off around six to eight thousand steps a day.",
            "Not ten thousand. Six to eight. Good news for your knees."],
        ost=["Study: adults 60+, 6,000–8,000 steps/day"]),
    seg("Brisk", "block", 60,
        dict(rebuild=("seated_march", "harder", "1 minute, faster"), steady=("walk", "main", "1 minute, a little faster"),
             strong=("walk", "main", "1 minute brisk: can talk, can't sing"), iron=("walk", "harder", "1 minute brisk, uphill if you have one")),
        vo=["Pick it up. Can talk. Can't sing.", "Sun can sing. She's not walking fast enough."], sun=["I'm walking at the correct speed."]),
    seg("Easy", "block", 60,
        dict(rebuild=("seated_march", "main", "1 minute, easy"), steady=("walk", "easier", "1 minute easy"), strong=("walk", "easier", "1 minute easy"), iron=("walk", "easier", "1 minute easy")),
        vo=["Back to easy.", "Walking speed matters. In 34,485 adults over 65, faster walking speed was linked with longer survival.", "It's a link. Not a race. Walk tall."],
        ost=["Study: 34,485 adults 65+"]),
    seg("Brisk", "block", 60,
        dict(rebuild=("seated_march", "harder", "1 minute, faster"), steady=("walk", "main", "1 minute, a little faster"),
             strong=("walk", "main", "1 minute brisk"), iron=("walk", "harder", "1 minute brisk")),
        vo=["One more brisk minute.", "Tall. Arms swing. Breathe."]),
    seg("Easy", "block", 60,
        dict(rebuild=("seated_march", "main", "1 minute, easy"), steady=("walk", "easier", "1 minute easy"), strong=("walk", "easier", "1 minute easy"), iron=("walk", "easier", "1 minute easy")),
        vo=["Easy again.", "Tip: walk after your biggest meal. Even a few minutes lowers the blood-sugar rise after eating."]),
    seg("Cool-down walk", "cooldown", 90,
        dict(rebuild=("seated_march", "easier", "90 seconds, slow"), steady=("walk", "easier", "90 seconds, slow"), strong=("walk", "easier", "90 seconds, slow"), iron=("walk", "easier", "90 seconds, slow")),
        vo=["Slow it down. Let your breathing settle.", "Find a rail or a wall for the stretch."]),
    seg("Calf stretch at the rail", "cooldown", 40, same("calf_stretch", "20 seconds each leg, holding with both hands", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main")),
        vo=["Hands on the rail. One foot back. Heel down.", "Breathe slow. Switch."]),
    seg("Close", "close", 25, vo=["Tell me your steps today. Honest number.", "Tomorrow, rest and stretch. You earned it."]),
])

session(n=7, weekday="Sunday", type="Rest + stretch", title="Easy Sunday", set="SET-LIVING", wardrobe="C-CASUAL",
        swaps=dict(sore_knee="Skip the figure-4.", sore_back="Keep the turn tiny; do the bed bridge only if it feels good.",
                   low_energy="Breathing and the check-in. That's a full Sunday."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Sunday. Rest day. Rest is not nothing.",
        "Gentle stretches, then we look at your week.",
        "Pencil and your log nearby.",
        "Anything sharp, or dizziness? Stop and sit."],
        ost=["Day 7 · Rest + stretch", "Stop if sharp pain or dizziness"], sun=["He calls this rest. He did push-ups at six a.m."]),
    seg("Cyclic sighing", "block", 60, same("cyclic_sigh", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4),
        vo=["Two sniffs in through the nose. Long sigh out.", "No holding."]),
    seg("Neck nods and half-turns", "block", 40, same("neck_nods", "4 nods, 2 turns each side", "5 nods, 3 turns each side", "5 nods, 3 turns each side", "5 nods, 3 turns each side", ("easier", "main", "main", "main")),
        vo=["Small nods. Half-turns. Slow."]),
    seg("Shoulder rolls", "block", 30, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls", "8 rolls", ("main",) * 4),
        vo=["Up, back, down."]),
    seg("Gentle seated turn", "block", 45, same("seated_rotation", "3 each side, small", "5 each side", "5 each side", "5 each side", ("easier", "main", "main", "main")),
        vo=["Tall first. Then turn. Only as far as comfortable."]),
    seg("Seated hamstring stretch", "block", 60, same("hamstring_seated", "20 seconds each leg, small lean", "20 seconds each leg", "30 seconds each leg", "30 seconds each leg", ("easier", "main", "main", "main")),
        vo=["Leg straight. Long back. Hinge from the hips.", "Breathe slow."]),
    seg("Figure-4 hip stretch", "block", 50, same("figure4", "20 seconds each side, ankle on shin", "20 seconds each side", "30 seconds each side", "30 seconds each side", ("easier", "main", "main", "main")),
        vo=["Ankle on knee or shin. Sit tall. Let it relax.", "New hip? Your surgeon's rules first."]),
    seg("Calf stretch", "block", 45, same("calf_stretch", "20 seconds each leg, both hands on the counter", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main")),
        vo=["Stand slowly. Hands on the counter. Heel down."]),
    seg("Bed bridge (optional)", "block", 45, same("bed_bridge", "6 squeezes, no lift", "8 bridges", "8 bridges, 3-second hold", "10 bridges, 3-second hold", ("easier", "main", "harder", "harder")),
        vo=["Optional. On your bed. Knees bent. Squeeze and lift a few inches.", "Breathe out as you lift.", "Sit a moment before you stand. Then stand slowly, holding something."],
        ost=["Sit a moment before you stand"]),
    seg("Ankle pumps", "block", 30, same("ankle_pumps", "10 pumps", "10 pumps", "10 pumps", "10 pumps", ("main",) * 4),
        vo=["Seated. Toes away, toes to you. Before you stand, every time."]),
    seg("Week check-in", "checkin", 60, vo=[
        "Now the log. Three numbers.",
        "How many sessions this week. Your best chair stands. How you slept, one to five.",
        "Anything that hurt more than three out of ten and didn't settle by the next day? Tell the app. We'll swap it.",
        "Your full Strength Age retest is on day 30. Not today."],
        ost=["Sessions · Best chair stands · Sleep 1–5"]),
    seg("Close", "close", 30, vo=["Week one. Done.", "Call someone today. Tell them what you did.", "Same time tomorrow. Legs first."], sun=["And eat something with protein. Grams, not vibes."]),
])

# ------------------------------------------------------------------ WEEK 2
session(n=8, weekday="Monday", type="Strength", title="Legs first, one more set", set="SET-GARAGE", wardrobe="C-TRAIN-A",
        swaps=dict(sore_knee="Higher seat and half range for sit-to-stands; seated knee straightening instead of the split squat and wall sit.",
                   sore_back="Towel pull-apart instead of the jug row; skip the overhead press.",
                   low_energy="Last week's Day 1 numbers. No extra set."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Week two. Monday. Strength.",
        "Same moves. One more set. That's how strength works. A little more, slowly.",
        "Chair against the wall. Counter close.",
        "Stop if you feel chest pain, dizziness or sharp pain."],
        ost=["Day 8 · Strength", "Stop if chest pain, dizziness or sharp pain"]),
    seg("Warm-up march", "warmup", 45, dict(rebuild=("seated_march", "main", "45 seconds"), steady=("standing_march", "main", "45 seconds"),
                                              strong=("standing_march", "harder", "45 seconds"), iron=("standing_march", "harder", "45 seconds")),
        vo=["Ankle pumps first if you've been sitting. Then stand slowly.", "March. Hand on the counter."]),
    seg("Easy sit-to-stands", "warmup", 30, same("sit_to_stand", "3 easy reps", "5 easy reps", "5 easy reps", "5 easy reps", ("easier", "main", "main", "main")),
        vo=["Five easy. Breathe out as you stand."]),
    seg("Legs", "block", 130,
        dict(rebuild=("sit_to_stand", "easier", "3 sets of 6, hands on thighs"), steady=("sit_to_stand", "main", "3 sets of 8, arms crossed"),
             strong=("sit_to_stand", "harder", "3 sets of 10, 3-second lower"), iron=("split_squat", "main", "3 sets of 8 each leg, hand on the counter (advanced)")),
        vo=["Three sets today. Nose over toes. Push the floor away.", "Sit down slow. Breathe out as you stand.",
            "Iron: split squat at the counter. Straight down, like an elevator.", "Rest. Next set."],
        ost=["Iron: advanced"]),
    seg("Push", "block", 110,
        dict(rebuild=("seated_chest_press", "main", "3 sets of 8"), steady=("wall_pushup", "main", "3 sets of 8"),
             strong=("counter_pushup", "main", "3 sets of 8"), iron=("counter_pushup", "harder", "3 sets of 10, 3-second lower")),
        vo=["Strong: move to the counter this week.", "Straight line head to heels. Breathe out as you push."]),
    seg("Heel raises", "block", 60, dict(rebuild=("heel_raise", "easier", "3 sets of 12, seated"), steady=("heel_raise", "main", "3 sets of 10"),
                                           strong=("heel_raise", "harder", "3 sets of 12, one hand"), iron=("heel_raise", "harder", "3 sets of 8 each leg")),
        vo=["Hands on the counter. Up. Pause. Down for three.", "Breathe out as you rise."]),
    seg("Row", "block", 100, dict(rebuild=("towel_row", "main", "4 pulls, 3-second squeeze"), steady=("jug_row", "main", "3 sets of 8 each arm"),
                                    strong=("jug_row", "harder", "3 sets of 10 each arm"), iron=("jug_row", "harder", "3 sets of 12 each arm, 1-second pause")),
        vo=["Hand on the counter. Long back. Pull with the elbow.", "Breathe out as you pull."]),
    seg("Press", "block", 60, dict(rebuild=("seated_press", "easier", "2 sets of 6, one arm at a time"), steady=("seated_press", "main", "2 sets of 8"),
                                     strong=("seated_press", "main", "2 sets of 10"), iron=("seated_press", "harder", "3 sets of 10, half-gallon jugs")),
        vo=["Sit tall. Bottles at the shoulders.", "Press up only to comfortable height. Ribs down.", "Shoulder sore? Press forward at a slant, or skip it today."]),
    seg("Finisher", "block", 55, dict(rebuild=("seated_knee_ext", "main", "2 sets of 8 each leg"), steady=("wall_sit_high", "main", "2 holds of 20 seconds"),
                                        strong=("wall_sit_high", "main", "3 holds of 20 seconds"), iron=("wall_sit_high", "harder", "3 holds of 30 seconds (advanced)")),
        vo=["Back on the wall. A few inches down.", "Count out loud. Keep breathing.", "High blood pressure? Short holds, and ask your doctor about long ones."],
        ost=["Keep breathing: count out loud"]),
    seg("Cool-down", "cooldown", 60, same("calf_stretch", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "harder")),
        vo=["Calf stretch at the wall. Then sit. Two sniffs in, long sigh out."]),
    seg("Close", "close", 25, vo=["One more set than last week. That's the whole game.", "Deposit made. Same time tomorrow."]),
])

session(n=9, weekday="Tuesday", type="Mobility", title="Shoulders and hips", set="SET-YARD", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Skip the figure-4 and the hip-front stretch; extra ankle circles.",
                   sore_back="Chin tucks, wall slides and breathing only.", low_energy="Seated moves only."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Tuesday. Mobility again. I'm told it's good for me.",
        "Today: shoulders, upper back, hips.",
        "Only as far as comfortable. Nothing forced.",
        "Sharp pain or dizziness? Stop."],
        ost=["Day 9 · Mobility", "Stop if sharp pain or dizziness"], sun=["He's told it's good for him because it is."]),
    seg("Chin tucks", "block", 40, same("chin_tuck", "5 small tucks", "6 tucks, 2-second hold", "8 tucks, 2-second hold", "8 tucks, 5-second hold", ("easier", "main", "main", "harder")),
        vo=["Sit tall. Slide your chin straight back. Double chin. Beautiful.", "Eyes level. Breathe normally."]),
    seg("Shoulder rolls", "warmup", 30, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls + arm circles", "8 rolls + arm circles", ("main", "main", "harder", "harder")),
        vo=["Big slow circles backward."]),
    seg("Wall slides", "block", 50, same("wall_slide", "6 finger walks", "8 slides", "8 slides, 2-second hold", "10 slides, 2-second hold", ("easier", "main", "harder", "harder")),
        vo=["Back to the wall. Goalpost arms.", "Slide up only as far as comfortable. Breathe out as you slide down."]),
    seg("Chest lift", "block", 40, same("chest_lift", "6 lifts", "8 lifts", "8 lifts, 3-second hold", "10 lifts, 3-second hold", ("easier", "main", "harder", "harder")),
        vo=["Near the front of the chair. Lift the chest. Grow tall."]),
    seg("Gentle seated turn", "block", 50, same("seated_rotation", "4 each side, small", "6 each side", "6 each side", "8 each side", ("easier", "main", "main", "main")),
        vo=["Grow tall. Turn. Only as far as comfortable.", "Osteoporosis: small and gentle."]),
    seg("Standing hip-front stretch", "block", 60, dict(rebuild=("hip_flexor", "easier", "20 seconds each side, both hands on the counter"), steady=("hip_flexor", "main", "2 × 20 seconds each side"),
                                                      strong=("hip_flexor", "harder", "2 × 20 seconds each side, arm up"), iron=("hip_flexor", "harder", "2 × 30 seconds each side, arm up")),
        vo=["Hand on the fence or counter. Small step back.", "Tuck, squeeze, shift forward a little.", "Breathe slow."]),
    seg("Standing bird-dog", "block", 50, dict(rebuild=("standing_birddog", "easier", "4 each side, leg only"), steady=("standing_birddog", "main", "6 each side"),
                                              strong=("standing_birddog", "harder", "6 each side, 3-second hold"), iron=("standing_birddog", "harder", "8 each side, 3-second hold")),
        vo=["Both hands on the fence. Foot back. Arm forward if steady.", "Long back. Breathe out as you reach."]),
    seg("Figure-4 hip stretch", "block", 50, same("figure4", "20 seconds each side, ankle on shin", "20 seconds each side", "30 seconds each side", "30 seconds each side, hinge forward", ("easier", "main", "main", "harder")),
        vo=["Sit. Ankle on the knee or shin. Relax the knee.", "New hip? Your surgeon's precautions first."]),
    seg("Seated hamstring stretch", "block", 50, same("hamstring_seated", "20 seconds each leg", "20 seconds each leg", "30 seconds each leg", "30 seconds each leg", ("easier", "main", "main", "harder")),
        vo=["Leg straight, heel down. Long back. Hinge from the hips."]),
    seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute, in 3 out 4", "1 minute", "1 minute", "1 minute", ("easier", "main", "main", "main")),
        vo=["In for four. Out for six. No holds."]),
    seg("Close", "close", 25, vo=["Done. My shoulders say thank you. I won't tell Sun.", "Tomorrow: balance."], sun=["I heard that."]),
])

session(n=10, weekday="Wednesday", type="Balance", title="Steadier feet", set="SET-KITCHEN", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Shorter holds, wider feet; skip the backward walk.", sore_back="Front and side reaches only.",
                   low_energy="Heel-to-toe stand, one-leg stand, cloud hands."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Wednesday. Balance, week two.",
        "Holds get longer today. Support stays the same. Counter. Chair behind you.",
        "Balance is one of the most trainable things there is. Practise it and you feel steadier on your feet, and more confident on stairs.",
        "Dizzy? Sit down."],
        ost=["Day 10 · Balance", "Balance is trainable"]),
    seg("Weight shifts", "warmup", 40, same("weight_shift", "5 each way, seated", "6 each way", "8 each way, bigger", "8 each way, one hand hovering", ("easier", "main", "harder", "harder")),
        vo=["Hands on the counter. Side to side. Front to back."]),
    seg("Heel-to-toe stand", "block", 75, dict(rebuild=("tandem_stand", "easier", "3 × 15 seconds each side, half-step, both hands down"), steady=("tandem_stand", "main", "3 × 15 seconds each side"),
                                              strong=("tandem_stand", "harder", "3 × 20 seconds each side, hands hovering"), iron=("tandem_stand", "harder", "3 × 30 seconds each side, hands hovering")),
        vo=["Heel to toe. Hands on the counter, or hovering if you're Strong or Iron.", "Eyes on something still. Breathe.", "Switch."]),
    seg("One-leg stand", "block", 75, dict(rebuild=("single_leg", "easier", "3 × 10 seconds each side, toe down"), steady=("single_leg", "main", "3 × 15 seconds each side"),
                                          strong=("single_leg", "harder", "3 × 20 seconds each side, one hand hovering"), iron=("single_leg", "harder", "3 × 30 seconds each side, hands hovering")),
        vo=["Weight on one foot. Lift the other.", "Count out loud. Squeeze the standing buttock.", "Switch."]),
    seg("Heel-to-toe walk", "block", 60, dict(rebuild=("heel_toe_walk", "easier", "2 lengths, feet apart, holding on"), steady=("heel_toe_walk", "main", "3 lengths"),
                                             strong=("heel_toe_walk", "harder", "2 lengths forward + 1 backward, hand on the counter"), iron=("heel_toe_walk", "harder", "2 forward, hand hovering + 2 backward, hand on the counter")),
        vo=["Hand on the counter. Heel in front of toes.", "Backward walk for Strong and Iron: normal steps, slow, hand resting on the counter."]),
    seg("Side steps", "block", 50, same("side_step", "1 set of 8 each way", "2 sets of 10 each way, knees bent", "2 sets of 12 each way, knees bent", "3 sets of 12 each way, knees bent", ("easier", "harder", "harder", "harder")),
        vo=["Face the counter. Knees a little bent. Step, feet meet."]),
    seg("Sit-to-stand, no hands", "block", 50, dict(rebuild=("sit_to_stand", "easier", "1 set of 6, hands on thighs"), steady=("sit_stand_nohands", "main", "1 set of 8"),
                                                   strong=("sit_stand_nohands", "harder", "2 sets of 6, feet together"), iron=("sit_stand_nohands", "harder", "2 sets of 8, feet together, 3-second lower")),
        vo=["Stand. Balance two seconds at the top. Sit slow.", "Breathe out as you stand."]),
    seg("Clock reach", "block", 50, same("clock_reach", "3 each way, front and side", "4 each direction", "4 each direction, one foot at 12", "5 each direction, one foot at 12", ("easier", "main", "harder", "harder")),
        vo=["Side-on to the counter. Reach to the clock numbers. Eyes follow the hand."]),
    seg("Cloud hands", "block", 60, same("cloud_hands", "1 minute, seated", "1 minute", "1 minute", "1 minute with side steps", ("easier", "main", "main", "harder")),
        vo=["Shift and float. Right, then left.", "Soft knees. Center of mass low."]),
    seg("Cyclic sighing", "cooldown", 30, same("cyclic_sigh", "30 seconds", "30 seconds", "30 seconds", "30 seconds", ("main",) * 4),
        vo=["Sit. Two sniffs in. Long sigh out."]),
    seg("Close", "close", 25, vo=["Update the fridge chart. Longest one-leg time.", "Sun's number is still better. For now."], sun=["For always."]),
])

session(n=11, weekday="Thursday", type="Strength", title="Push, pull, carry, more", set="SET-GARAGE", wardrobe="C-TRAIN-A",
        swaps=dict(sore_knee="Seated knee straightening instead of step-ups; power stands from a higher seat at normal speed.",
                   sore_back="Seated hinge; one light bag for the carry.", low_energy="One set of each block."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Thursday. Strength, week two.",
        "Three sets on the big moves. Fast up, slow down.",
        "Chair against the wall. Stair rail. Counter.",
        "Stop if chest pain, dizziness or sharp pain."],
        ost=["Day 11 · Strength", "Stop if chest pain, dizziness or sharp pain"]),
    seg("Warm-up march", "warmup", 40, dict(rebuild=("seated_march", "main", "40 seconds"), steady=("standing_march", "main", "40 seconds"),
                                              strong=("standing_march", "harder", "40 seconds"), iron=("standing_march", "harder", "40 seconds")),
        vo=["Hand on the counter. March."]),
    seg("Easy sit-to-stands", "warmup", 30, same("sit_to_stand", "3 easy reps", "5 easy reps", "5 easy reps", "5 easy reps", ("easier", "main", "main", "main")),
        vo=["Five easy. Breathe out as you stand."]),
    seg("Power stands", "block", 110, dict(rebuild=("sit_to_stand", "easier", "3 sets of 5, normal speed"), steady=("power_stand", "main", "3 sets of 5"),
                                           strong=("power_stand", "harder", "3 sets of 5, jug at chest"), iron=("power_stand", "harder", "3 sets of 6, gallon jug at chest (advanced)")),
        vo=["Pop up. Stand tall. Lower for three.", "Breathe out hard as you stand.", "Dizzy when you stand fast? Normal speed."]),
    seg("Step-ups", "block", 110, dict(rebuild=("seated_march", "harder", "3 × 30 seconds, knees high"), steady=("step_up", "main", "2 sets of 6 each leg"),
                                       strong=("step_up", "main", "3 sets of 6 each leg"), iron=("step_up", "harder", "3 sets of 8 each leg, bag in free hand (advanced)")),
        vo=["Hand on the rail the whole time.", "Steady: real step-ups this week. Whole foot on the step.", "Breathe out as you step up."]),
    seg("Hinge pick-up", "block", 80, dict(rebuild=("seated_hinge", "main", "2 sets of 8"), steady=("hip_hinge", "harder", "2 sets of 8, jug from the chair seat"),
                                          strong=("hip_hinge", "harder", "3 sets of 8, jug from the chair seat"), iron=("hip_hinge", "harder", "3 sets of 8, heavier bag from the bottom step")),
        vo=["Hips back. Long back. Pick up the jug.", "Squeeze to stand. Breathe out.", "Put it down the same way."]),
    seg("Push", "block", 70, dict(rebuild=("seated_chest_press", "main", "2 sets of 10"), steady=("wall_pushup", "harder", "2 sets of 10, feet farther back"),
                                    strong=("counter_pushup", "main", "2 sets of 10"), iron=("counter_pushup", "harder", "3 sets of 10, 3-second lower")),
        vo=["One straight line. Breathe out as you push."]),
    seg("Curls", "block", 55, same("bottle_curl", "2 sets of 10, bottles", "2 sets of 10, half-gallon jug", "3 sets of 10, half-gallon jug", "3 sets of 10, gallon jug", ("main", "harder", "harder", "harder")),
        vo=["Elbows by your sides. Curl. Lower slow."]),
    seg("Carry", "block", 70, dict(rebuild=("towel_wring", "main", "4 wrings each direction"), steady=("carry", "main", "2 walks of 30 seconds, two bags"),
                                     strong=("carry", "harder", "3 walks of 30 seconds, heavier bags"), iron=("carry", "harder", "3 walks of 45 seconds, heavy bags")),
        vo=["Hinge to pick up. Stand tall. Short steps.", "Breathe. Hinge to put down."]),
    seg("Cool-down", "cooldown", 50, dict(rebuild=("chest_lift", "main", "6 lifts"), steady=("chest_lift", "main", "6 lifts"), strong=("chest_lift", "main", "6 lifts"), iron=("chest_lift", "main", "6 lifts")),
        vo=["Sit. Chest up. Two sniffs in, long sigh out."]),
    seg("Close", "close", 25, vo=["I'm made of pixels. Your muscles are made of protein. Go eat some.", "Tomorrow: breath and flow."]),
])

session(n=12, weekday="Friday", type="Breath + qigong", title="Breathe and flow, longer", set="SET-YARD", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Everything seated or tall-stance; heel raise without the drop.", sore_back="Seated versions.",
                   low_energy="Breathing, sky lift, cloud hands."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Friday. Breath and flow. Six pieces today.",
        "New piece at the end: rise up on the toes. Most of us lower slowly. No jumping.",
        "Chair behind you.",
        "Light-headed, dizzy, or chest pain? Stop and sit."],
        ost=["Day 12 · Breath + qigong", "Stop if dizzy or chest pain"]),
    seg("Cyclic sighing", "block", 90, same("cyclic_sigh", "90 seconds", "90 seconds", "90 seconds", "90 seconds", ("main",) * 4),
        vo=["Two sniffs in. Long sigh out.", "No holding. If you feel light-headed, breathe normally."]),
    seg("Holding up the sky", "block", 55, same("sky_lift", "4 reps, seated", "5 reps", "6 reps, slower", "6 reps, rise onto toes", ("easier", "main", "main", "harder")),
        vo=["Hands rise with the in-breath. Float down with the out-breath."]),
    seg("Drawing the bow", "block", 55, same("draw_bow", "3 each side, seated", "4 each side", "5 each side", "5 each side, knees a little more bent", ("easier", "main", "main", "harder")),
        vo=["High stance. Push out. Draw back. Breathe out as you draw."]),
    seg("Separating heaven and earth", "block", 55, same("heaven_earth", "3 each side, seated", "4 each side", "5 each side", "5 each side, slower", ("easier", "main", "main", "harder")),
        vo=["One hand up, one hand down. Long spine."]),
    seg("Looking back", "block", 45, same("owl_look", "3 each side, eyes more than head", "3 each side", "4 each side", "4 each side, hold one breath", ("easier", "main", "main", "harder")),
        vo=["Half-turns only. Chin level."]),
    seg("Punching with a steady gaze", "block", 50, same("fists", "4 each side, seated", "5 each side", "6 each side", "6 each side, lower stance", ("easier", "main", "main", "harder")),
        vo=["Slow punch. Grip the air. Pull back. Breathe out as you punch."]),
    seg("Heel raise and gentle drop", "block", 50, dict(rebuild=("heel_raise", "easier", "8 seated heel raises"), steady=("heel_drop", "easier", "8 heel raises, slow lower, no drop"),
                                                       strong=("heel_drop", "main", "7 gentle drops, hands on the counter"), iron=("heel_drop", "harder", "10 gentle drops")),
        vo=["Hands on the counter. Up on the toes.", "Most of you: lower slowly. Strong and Iron: a soft bump.",
            "Osteoporosis without a training history, pelvic floor problems, or a joint replacement? No drop. Slow lower."],
        ost=["Gentle impact — slow lower if unsure"]),
    seg("Cloud hands", "block", 60, same("cloud_hands", "1 minute, seated", "1 minute", "1 minute", "1 minute with side steps", ("easier", "main", "main", "harder")),
        vo=["Shift and float. Like wiping a big window."]),
    seg("4-6 breathing", "cooldown", 60, same("breath_46", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4),
        vo=["In for four. Out for six."]),
    seg("Close", "close", 25, vo=["Six pieces. Well done.", "Tomorrow we walk. Longer brisk bits."]),
])

session(n=13, weekday="Saturday", type="Walk-and-talk", title="Walk tall", set="SET-PROM", wardrobe="C-TRAIN-B",
        swaps=dict(sore_knee="Easy pace, flat route, skip the bench stands.", sore_back="Easy pace; rest on benches.", low_energy="Easy pace throughout."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Saturday. Walk, week two. Longer brisk bits.",
        "Same rules. Good shoes. Flat route. Indoors counts.",
        "Chest pain or unusual breathlessness? Stop, sit, call your doctor."],
        ost=["Day 13 · Walk", "Chest pain? Stop and call"]),
    seg("Easy walk", "block", 120, dict(rebuild=("seated_march", "main", "2 minutes, or walker lengths of the hallway"), steady=("walk", "easier", "2 minutes easy"),
                                        strong=("walk", "easier", "2 minutes easy"), iron=("walk", "easier", "2 minutes easy")),
        vo=["Easy pace. Tall. Eyes ahead.", "Posture check: ears over shoulders. Shoulders over hips."]),
    seg("Brisk", "block", 90, dict(rebuild=("seated_march", "harder", "1 minute faster, 30 seconds easy"), steady=("walk", "main", "90 seconds, a little faster"),
                                     strong=("walk", "main", "90 seconds brisk"), iron=("walk", "harder", "90 seconds brisk, uphill if you have one")),
        vo=["Brisk. Can talk, can't sing.", "Push off the back foot. Arms swing."]),
    seg("Easy", "block", 60, dict(rebuild=("seated_march", "main", "1 minute easy"), steady=("walk", "easier", "1 minute easy"), strong=("walk", "easier", "1 minute easy"), iron=("walk", "easier", "1 minute easy")),
        vo=["Easy. Breathe."]),
    seg("Brisk", "block", 90, dict(rebuild=("seated_march", "harder", "1 minute faster, 30 seconds easy"), steady=("walk", "main", "90 seconds, a little faster"),
                                     strong=("walk", "main", "90 seconds brisk"), iron=("walk", "harder", "90 seconds brisk")),
        vo=["Brisk again. Tall walking."], sun=["Chang, you're leaning forward like a question mark."]),
    seg("Bench stands", "block", 45, dict(rebuild=("sit_to_stand", "easier", "3 stands from your chair at home, hands on thighs"), steady=("sit_to_stand", "main", "5 stands from a sturdy bench, hand on the armrest if needed"),
                                          strong=("sit_to_stand", "main", "8 stands from a bench"), iron=("sit_to_stand", "harder", "8 slow stands from a bench")),
        vo=["Find a sturdy bench, or your chair at home.", "Stand up. Sit down slow. Breathe out as you stand."]),
    seg("Cool-down walk", "cooldown", 90, dict(rebuild=("seated_march", "easier", "90 seconds slow"), steady=("walk", "easier", "90 seconds slow"), strong=("walk", "easier", "90 seconds slow"), iron=("walk", "easier", "90 seconds slow")),
        vo=["Slow down. Let your breathing settle.", "Tip: walk after your biggest meal."]),
    seg("Calf stretch at the rail", "cooldown", 40, same("calf_stretch", "20 seconds each leg, both hands on the rail", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main")),
        vo=["Hands on the rail. Heel down. Breathe."]),
    seg("Close", "close", 25, vo=["Tell me your steps. And your fastest brisk minute felt like what, one to five?", "Tomorrow: easy Sunday."]),
])

session(n=14, weekday="Sunday", type="Rest + stretch", title="Two weeks done", set="SET-LIVING", wardrobe="C-CASUAL",
        swaps=dict(sore_knee="Skip the figure-4.", sore_back="Tiny turns; skip the bridge.", low_energy="Breathing and the check-in."),
        segments=[
    seg("Welcome", "intro", 35, vo=[
        "Sunday. Two weeks done.",
        "Gentle stretches. Then a look back, and a look ahead.",
        "Log and pencil nearby.",
        "Anything sharp, or dizziness? Stop and sit."],
        ost=["Day 14 · Rest + stretch", "Stop if sharp pain or dizziness"]),
    seg("Cyclic sighing", "block", 60, same("cyclic_sigh", "1 minute", "1 minute", "1 minute", "1 minute", ("main",) * 4),
        vo=["Two sniffs in. Long sigh out."]),
    seg("Chin tucks", "block", 30, same("chin_tuck", "5 tucks", "6 tucks", "6 tucks", "6 tucks, 5-second hold", ("easier", "main", "main", "harder")),
        vo=["Slide the chin back. Eyes level."]),
    seg("Shoulder rolls", "block", 30, same("shoulder_rolls", "6 rolls", "8 rolls", "8 rolls", "8 rolls", ("main",) * 4),
        vo=["Up, back, down."]),
    seg("Gentle seated turn", "block", 45, same("seated_rotation", "3 each side, small", "5 each side", "5 each side", "5 each side", ("easier", "main", "main", "main")),
        vo=["Tall, then turn. Only as far as comfortable."]),
    seg("Seated hamstring stretch", "block", 60, same("hamstring_seated", "20 seconds each leg", "30 seconds each leg", "30 seconds each leg", "30 seconds each leg", ("easier", "main", "main", "main")),
        vo=["Long back. Hinge. Breathe."]),
    seg("Figure-4 hip stretch", "block", 50, same("figure4", "20 seconds each side, ankle on shin", "30 seconds each side", "30 seconds each side", "30 seconds each side", ("easier", "main", "main", "main")),
        vo=["Ankle on knee or shin. Relax. New hip: surgeon's rules first."]),
    seg("Calf stretch", "block", 45, same("calf_stretch", "20 seconds each leg, both hands on the counter", "20 seconds each leg", "20 seconds each leg", "20 seconds each leg", ("easier", "main", "main", "main")),
        vo=["Stand slowly. Hands on the counter. Heel down."]),
    seg("Bed bridge (optional)", "block", 45, same("bed_bridge", "6 squeezes, no lift", "10 bridges", "10 bridges, 3-second hold", "12 bridges, 3-second hold", ("easier", "main", "harder", "harder")),
        vo=["Optional. On the bed. Squeeze and lift.", "Sit a moment before you stand. Then stand slowly, holding something."],
        ost=["Sit a moment before you stand"]),
    seg("Two-week check-in", "checkin", 75, vo=[
        "Look at your log. Sessions done in fourteen days.",
        "Compare your Day 1 chair stands with this week's sets. Did the last reps feel easier?",
        "If a move felt easy for every rep two sessions in a row, the app will offer the next level. You decide.",
        "Anything that hurt more than three out of ten and didn't settle by morning, tell us. We swap it.",
        "Your Strength Age retest is on day 30."],
        ost=["Easy two sessions in a row? Try the next level", "Retest: day 30"]),
    seg("Close", "close", 30, vo=["Two weeks. That's a habit starting.", "Next week, a new program starts on your dashboard.", "Same time tomorrow."],
        sun=["Eight out of ten. Don't get used to it."]),
])
